### ISSUE TITLE
The op DepthwiseConvolution in model is not supported yet

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/X2Paddle#102]
```
register layer[ROIPooling]
register layer[PriorBox]
register layer[Permute]
register layer[DetectionOutput]
register layer[Normalize]
register layer[Select]
register layer[ShuffleChannel]
register layer[ConvolutionDepthwise]
register layer[Axpy]
Now translating model from caffe to paddle.
...
Traceback (most recent call last):
  File "/Users//anaconda3/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/Users//anaconda3/lib/python3.5/site-packages/x2paddle/convert.py", line 201, in main
    args.caffe_proto)
  File "/Users//anaconda3/lib/python3.5/site-packages/x2paddle/convert.py", line 127, in caffe2paddle
    mapper = CaffeOpMapper(model)
  File "/Users//anaconda3/lib/python3.5/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 55, in __init__
    "The op {} in model is not supported yet.".format(op))
Exception: The op DepthwiseConvolution in model is not supported yet.
```
看到注册的layer里有ConvolutionDepthwise，能直接映射过去吗？

**Comment by SunAhong1993** [comment]
> ```
> register layer[ROIPooling]
> register layer[PriorBox]
> register layer[Permute]
> register layer[DetectionOutput]
> register layer[Normalize]
> register layer[Select]
> register layer[ShuffleChannel]
> register layer[ConvolutionDepthwise]
> register layer[Axpy]
> Now translating model from caffe to paddle.
> ...
> Traceback (most recent call last):
>   File "/Users//anaconda3/bin/x2paddle", line 10, in <module>
>     sys.exit(main())
>   File "/Users//anaconda3/lib/python3.5/site-packages/x2paddle/convert.py", line 201, in main
>     args.caffe_proto)
>   File "/Users//anaconda3/lib/python3.5/site-packages/x2paddle/convert.py", line 127, in caffe2paddle
>     mapper = CaffeOpMapper(model)
>   File "/Users//anaconda3/lib/python3.5/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 55, in __init__
>     "The op {} in model is not supported yet.".format(op))
> Exception: The op DepthwiseConvolution in model is not supported yet.
> ```
> 
> 看到注册的layer里有ConvolutionDepthwise，能直接映射过去吗？

你好，DepthwiseConvolution是属于一个新的op，如若其实现功能与ConvolutionDepthwise一致，可在[代码](https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/op_mapper/caffe_op_mapper.py#L47)中对node的名字直接映射过去；若功能不一致可参考[如何转换Caffe自定义Layer](https://github.com/PaddlePaddle/X2Paddle/blob/develop/add_caffe_custom_layer.md)来实现ConvolutionDepthwise的转换。

**Comment by imistyrain** [comment]
是一样的，ncnn的转换工具[caffe2ncnn](https://github.com/Tencent/ncnn/blob/46e7ac76abad0b3d8649b97c37a4d0e0dc565f9a/tools/caffe/caffe2ncnn.cpp#L467)都提供原生的支持，这个能对齐吗？

**Comment by jiangjiajun** [comment]
> 是一样的，ncnn的转换工具[caffe2ncnn](https://github.com/Tencent/ncnn/blob/46e7ac76abad0b3d8649b97c37a4d0e0dc565f9a/tools/caffe/caffe2ncnn.cpp#L467)都提供原生的支持，这个能对齐吗？

谢谢反馈，我们会验证后，将『ConvolutionDepthwise』加进x2paddle。如果方便的话，也可以告诉我们你所转换的模型对应或参考的github repo。

当前可以先按照上面的回复方式，修改`x2paddle/op_mapper/caffe_op_mapper.py`中代码，然后按如下方式重新安装后，再转换模型
```
cd X2Paddle
pip uninstall x2paddle
python setup.py install
```

**Comment by jiangjiajun** [comment]
已经添加代码中，可更新最新代码使用
https://github.com/PaddlePaddle/X2Paddle/pull/108
