### ISSUE TITLE
minor problems

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/X2Paddle#106]
1. function name:
https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/core/graph.py#L102
Seems conflict with built-in 'print'.
2. function definition:
https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/op_mapper/onnx_op_mapper.py#L97
should be 
```python
def directly_map(self, node, name='', *args,  **kwargs):
```
3. need to handle Unicode string
https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/core/fluid_code.py#L31
https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/core/fluid_code.py#L75

**Comment by jiangjiajun** [comment]
Thanks， We will fix these problem soon.

**Comment by MacroBull** [comment]
> 1. function name:
>    https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/core/graph.py#L102
>    Seems conflict with built-in 'print'.
> 2. function definition:
>    https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/op_mapper/onnx_op_mapper.py#L97
>    should be
> 
> ```python
> def directly_map(self, node, name='', *args,  **kwargs):
> ```
> 
> 1. need to handle Unicode string
>    https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/core/fluid_code.py#L31
>    https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/core/fluid_code.py#L75

Currently X2Paddle requires python >= 3.5, these are all python 3 features.

**Comment by pkuyym** [comment]
@MacroBull OK, however, even for python3, it is better to fix.

**Comment by MacroBull** [comment]
1. `print` can be renamed, it's ok.
2. Python 2 do not support positional / keyword splitting and bypass in arguments, using `kwargs.pop(key)` makes code untidy.
3. Python 3 has the only string type `str`, no unicode-type handling needed, superfluous codes like `isinstance(s, typing.Text)` is quite a paranoid.

**Comment by jiangjiajun** [comment]
Thanks for your advices! @pkuyym @MacroBull 
We just updated the code to make X2Paddle compatible with the python2, some of the problems have been fixed. :)    
https://github.com/PaddlePaddle/X2Paddle/pull/122 & https://github.com/PaddlePaddle/X2Paddle/pull/120
