### ISSUE TITLE
AssertionError: The parameter of my_classifier (type is InnerProduct) is not set. You need to use python package of caffe to set the default value.

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/X2Paddle#109]
转换resnet50模型(来自[caffe-model-zoo](https://github.com/SnailTyan/caffe-model-zoo))，报错
```
register layer[ROIPooling]
register layer[PriorBox]
register layer[Permute]
register layer[DetectionOutput]
register layer[Normalize]
register layer[Select]
register layer[ShuffleChannel]
register layer[ConvolutionDepthwise]
register layer[Axpy]
Now translating model from caffe to paddle.
cost: 1.406264305114746
Ignoring parameters for non-existent layer: fc1000
Total nodes: 229
squeeze idx:1, with kind:Convolution,name:conv1
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 9, in <module>
    load_entry_point('x2paddle==0.4.5', 'console_scripts', 'x2paddle')()
  File "/home/***/CNN/X2Paddle/x2paddle/convert.py", line 211, in main
    args.caffe_proto)
  File "/home/***/CNN/X2Paddle/x2paddle/convert.py", line 137, in caffe2paddle
    mapper = CaffeOpMapper(model)
  File "/home/***/CNN/X2Paddle/x2paddle/op_mapper/caffe_op_mapper.py", line 46, in __init__
    func(node)
  File "/home/***/CNN/X2Paddle/x2paddle/op_mapper/caffe_op_mapper.py", line 346, in InnerProduct
    node.layer_name, node.layer_type)
AssertionError: The parameter of my_classifier (type is InnerProduct) is not set. You need to use python package of caffe to set the default value.
```
转换用的命令为:
```
x2paddle --framework=caffe --prototxt=resnet50.prototxt --weight=resnet50.caffemodel --save_dir=pd_model  --caffe_proto=***/build/include/caffe/proto/caffe_pb2.py
```
0.3之前用的caffe2fluid还好好的呢，怎么升级了就不兼容了？

**Comment by jiangjiajun** [comment]
收到，我们马上定位一下问题。

**Comment by SunAhong1993** [comment]
> 转换resnet50模型(来自[caffe-model-zoo](https://github.com/SnailTyan/caffe-model-zoo))，报错
> 
> ```
> register layer[ROIPooling]
> register layer[PriorBox]
> register layer[Permute]
> register layer[DetectionOutput]
> register layer[Normalize]
> register layer[Select]
> register layer[ShuffleChannel]
> register layer[ConvolutionDepthwise]
> register layer[Axpy]
> Now translating model from caffe to paddle.
> cost: 1.406264305114746
> Ignoring parameters for non-existent layer: fc1000
> Total nodes: 229
> squeeze idx:1, with kind:Convolution,name:conv1
> Traceback (most recent call last):
>   File "/usr/local/bin/x2paddle", line 9, in <module>
>     load_entry_point('x2paddle==0.4.5', 'console_scripts', 'x2paddle')()
>   File "/home/***/CNN/X2Paddle/x2paddle/convert.py", line 211, in main
>     args.caffe_proto)
>   File "/home/***/CNN/X2Paddle/x2paddle/convert.py", line 137, in caffe2paddle
>     mapper = CaffeOpMapper(model)
>   File "/home/***/CNN/X2Paddle/x2paddle/op_mapper/caffe_op_mapper.py", line 46, in __init__
>     func(node)
>   File "/home/***/CNN/X2Paddle/x2paddle/op_mapper/caffe_op_mapper.py", line 346, in InnerProduct
>     node.layer_name, node.layer_type)
> AssertionError: The parameter of my_classifier (type is InnerProduct) is not set. You need to use python package of caffe to set the default value.
> ```
> 
> 转换用的命令为:
> 
> ```
> x2paddle --framework=caffe --prototxt=resnet50.prototxt --weight=resnet50.caffemodel --save_dir=pd_model  --caffe_proto=***/build/include/caffe/proto/caffe_pb2.py
> ```
> 
> 0.3之前用的caffe2fluid还好好的呢，怎么升级了就不兼容了？

你好，目前该问题已经解决，您可按如下方式重新安装后，再转换模型
```
cd X2Paddle
pip uninstall x2paddle
python setup.py install
```
该问题出现的原因主要是由于prototxt和caffemodel中最后一层的命名不一致，转换工具找不到对应参数而出错，当前更新版本对找不到的参数进行0初始化处理；0.3版本由于对未赋值的参数也进行了0初始化，所以也不会出现相应错误。针对这一问题的处理，当前版本已于0.3版本对齐。

**Comment by imistyrain** [comment]
好的，已给原仓库提issue [6](https://github.com/SnailTyan/caffe-model-zoo/issues/6)
