### ISSUE TITLE
AssertionError: The version of protobuf must be larger than 3.6.0!

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/X2Paddle#110]
pip3 list显示python3.5对应的protobuf版本是3.6.0了已经，但是protoc --version的版本是3.4.0.所以那个assert过不去，但是不影响使用。
还有就是python2.7版本的啥时候放出来？

**Comment by jiangjiajun** [comment]
> pip3 list显示python3.5对应的protobuf版本是3.6.0了已经，但是protoc --version的版本是3.4.0.所以那个assert过不去，但是不影响使用。
> 还有就是python2.7版本的啥时候放出来？

这个地方的版本检测之前确实是依赖protoc的版本，目前已经修改成protobuf的版本了。

python2由于即将不被官方支持，因此在项目开发过程中的开发环境都为python3.5，并没有考虑python2的支持。  
但同时也考虑到部分用户仍然还在使用python2的环境，因此现在也已经有同学在帮忙解决python2兼容性的问题，相信在本周内就会解决这个问题。

**Comment by jiangjiajun** [comment]
> pip3 list显示python3.5对应的protobuf版本是3.6.0了已经，但是protoc --version的版本是3.4.0.所以那个assert过不去，但是不影响使用。
> 还有就是python2.7版本的啥时候放出来？

我们更新了代码，并成功在Python2下测试了X2Paddle的转换。这里是代码的PR https://github.com/PaddlePaddle/X2Paddle/pull/122
