### ISSUE TITLE
master caffe2fluid net_template.py有问题

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/X2Paddle#129]
应修改如下
diff --git a/caffe2fluid/kaffe/net_template.py b/caffe2fluid/kaffe/net_template.py
index f9387c9..c6810c6 100644
--- a/caffe2fluid/kaffe/net_template.py
+++ b/caffe2fluid/kaffe/net_template.py
@@ -100,7 +100,7 @@ def main():
     npy_weight = args.npy_path
     fluid_model = args.model_param_path
     outputs = None
-    if len(sys.argv) >= 6:
+    if args.need_layers_name:
         outputs = args.need_layers_name.split(',')
 
     ret = MyNet.convert(npy_weight, fluid_model, outputs)

**Comment by jiangjiajun** [comment]
谢谢反馈，收到，我们会尽快确认。

**Comment by jiangjiajun** [comment]
> 应修改如下
> diff --git a/caffe2fluid/kaffe/net_template.py b/caffe2fluid/kaffe/net_template.py
> index f9387c9..c6810c6 100644
> --- a/caffe2fluid/kaffe/net_template.py
> +++ b/caffe2fluid/kaffe/net_template.py
> @@ -100,7 +100,7 @@ def main():
> npy_weight = args.npy_path
> fluid_model = args.model_param_path
> outputs = None
> 
> * if len(sys.argv) >= 6:
> 
> * if args.need_layers_name:
>   outputs = args.need_layers_name.split(',')
>   ret = MyNet.convert(npy_weight, fluid_model, outputs)

已更新代码https://github.com/PaddlePaddle/X2Paddle/pull/132/files
