### ISSUE TITLE
模型的双向GRU怎么转比较好

### ISSUE THREAD

**Issue by richlaji** [PaddlePaddle/X2Paddle#131]
复现的pytorch代码：
import torch
import torch.nn as nn
rnn = nn.GRU(10,20, bidirectional=True)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input,h0)
torch.onnx.export(rnn, input, 'test.onnx', verbose=True)

转onnx出的结果：
graph(%input : Float(5, 3, 10),
      %weight_ih_l0 : Float(60, 10),
      %weight_hh_l0 : Float(60, 20),
      %bias_ih_l0 : Float(60),
      %bias_hh_l0 : Float(60),
      %weight_ih_l0_reverse : Float(60, 10),
      %weight_hh_l0_reverse : Float(60, 20),
      %bias_ih_l0_reverse : Float(60),
      %bias_hh_l0_reverse : Float(60)):
  %9 : Long() = onnx::Constant[value={1}](), scope: GRU
  %10 : Tensor = onnx::Shape(%input), scope: GRU
  %11 : Long() = onnx::Gather[axis=0](%10, %9), scope: GRU
  %12 : Long() = onnx::Constant[value={2}](), scope: GRU
  %13 : Long() = onnx::Constant[value={20}](), scope: GRU
  %14 : Tensor = onnx::Unsqueeze[axes=[0]](%12)
  %15 : Tensor = onnx::Unsqueeze[axes=[0]](%11)
  %16 : Tensor = onnx::Unsqueeze[axes=[0]](%13)
  %17 : Tensor = onnx::Concat[axis=0](%14, %15, %16)
  %18 : Float(2, 3, 20) = onnx::ConstantOfShape[value={0}](%17), scope: GRU
  %19 : Tensor? = prim::Constant(), scope: GRU
  %20 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%weight_ih_l0), scope: GRU
  %21 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%weight_ih_l0), scope: GRU
  %22 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%weight_ih_l0), scope: GRU
  %23 : Tensor = onnx::Concat[axis=0](%20, %21, %22), scope: GRU
  %24 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%weight_hh_l0), scope: GRU
  %25 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%weight_hh_l0), scope: GRU
  %26 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%weight_hh_l0), scope: GRU
  %27 : Tensor = onnx::Concat[axis=0](%24, %25, %26), scope: GRU
  %28 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%bias_ih_l0), scope: GRU
  %29 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%bias_ih_l0), scope: GRU
  %30 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%bias_ih_l0), scope: GRU
  %31 : Tensor = onnx::Concat[axis=0](%28, %29, %30), scope: GRU
  %32 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%bias_hh_l0), scope: GRU
  %33 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%bias_hh_l0), scope: GRU
  %34 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%bias_hh_l0), scope: GRU
  %35 : Tensor = onnx::Concat[axis=0](%32, %33, %34), scope: GRU
  %36 : Tensor = onnx::Concat[axis=0](%31, %35), scope: GRU
  %37 : Tensor = onnx::Unsqueeze[axes=[0]](%23), scope: GRU
  %38 : Tensor = onnx::Unsqueeze[axes=[0]](%27), scope: GRU
  %39 : Tensor = onnx::Unsqueeze[axes=[0]](%36), scope: GRU
  %40 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%weight_ih_l0_reverse), scope: GRU
  %41 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%weight_ih_l0_reverse), scope: GRU
  %42 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%weight_ih_l0_reverse), scope: GRU
  %43 : Tensor = onnx::Concat[axis=0](%40, %41, %42), scope: GRU
  %44 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%weight_hh_l0_reverse), scope: GRU
  %45 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%weight_hh_l0_reverse), scope: GRU
  %46 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%weight_hh_l0_reverse), scope: GRU
  %47 : Tensor = onnx::Concat[axis=0](%44, %45, %46), scope: GRU
  %48 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%bias_ih_l0_reverse), scope: GRU
  %49 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%bias_ih_l0_reverse), scope: GRU
  %50 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%bias_ih_l0_reverse), scope: GRU
  %51 : Tensor = onnx::Concat[axis=0](%48, %49, %50), scope: GRU
  %52 : Tensor = onnx::Slice[axes=[0], ends=[40], starts=[20]](%bias_hh_l0_reverse), scope: GRU
  %53 : Tensor = onnx::Slice[axes=[0], ends=[20], starts=[0]](%bias_hh_l0_reverse), scope: GRU
  %54 : Tensor = onnx::Slice[axes=[0], ends=[60], starts=[40]](%bias_hh_l0_reverse), scope: GRU
  %55 : Tensor = onnx::Concat[axis=0](%52, %53, %54), scope: GRU
  %56 : Tensor = onnx::Concat[axis=0](%51, %55), scope: GRU
  %57 : Tensor = onnx::Unsqueeze[axes=[0]](%43), scope: GRU
  %58 : Tensor = onnx::Unsqueeze[axes=[0]](%47), scope: GRU
  %59 : Tensor = onnx::Unsqueeze[axes=[0]](%56), scope: GRU
  %60 : Tensor = onnx::Concat[axis=0](%37, %57), scope: GRU
  %61 : Tensor = onnx::Concat[axis=0](%38, %58), scope: GRU
  %62 : Tensor = onnx::Concat[axis=0](%39, %59), scope: GRU
  %63 : Tensor, %64 : Float(2, 3, 20) = onnx::GRU[direction="bidirectional", hidden_size=20, linear_before_reset=1](%input, %60, %61, %62, %19, %18), scope: GRU
  %65 : Tensor = onnx::Transpose[perm=[0, 2, 1, 3]](%63), scope: GRU
  %66 : Tensor = onnx::Constant[value= 0  0 -1 [ Variable[CPUType]{3} ]](), scope: GRU
  %67 : Float(5, 3, 40) = onnx::Reshape(%65, %66), scope: GRU
  return (%67, %64)

x2paddle --framework=onnx --model=test.onnx --save_dir=./转paddle模型，会找不到%19这个节点，报错如下：
Traceback (most recent call last):
  File "/home/zhangzexin/anaconda3/envs/paddle/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/home/zhangzexin/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle/convert.py", line 211, in main
    onnx2paddle(args.model, args.save_dir)
  File "/home/zhangzexin/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle/convert.py", line 154, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/zhangzexin/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle/decoder/onnx_decoder.py", line 334, in __init__
    self.standardize_variable_name(model.graph)
  File "/home/zhangzexin/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle/decoder/onnx_decoder.py", line 501, in standardize_variable_name
    node.input[i] = self.make_variable_name(node.input[i])
  File "/home/zhangzexin/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle/decoder/onnx_decoder.py", line 478, in make_variable_name
    raise ValueError('name should not be empty')
ValueError: name should not be empty

已看github上一个gru的issue，看到推荐是使用nn.GRUCell的方式，但由于使用了nn.GRU封装的bidirection等属性，想知道（1）现在nn.GRU是一定没有办法转成功嘛，（2）有没有办法在不重新训练模型的情况下转成paddle呢~非常期待回复，感谢！

**Comment by richlaji** [comment]
使用from onnx2fluid.torch_export_helper import export_onnx_with_validation转的onnx模型，pytorch代码如下：
rnn = nn.GRU(10,20, bidirectional=True)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input)
#torch.onnx.export(rnn, input, 'test.onnx', verbose=True)
export_onnx_with_validation(rnn, [input], 'test.onnx', ['x'], ['y'],verbose=True, training=False)
也是会遇到相同的问题~

**Comment by jiangjiajun** [comment]
> Hi, @richlaji 感谢你对GRU算子的关注，
> 
> 对于第二种GRU包装算子， 即：
> 
> https://github.com/MacroBull/X2Paddle/blob/046844babd100e2671c99485414d01da452a50f6/onnx2fluid/examples/gen_some_samples.py#L54
> 
> 我在 #34 增加了支持，可以在这个分支上做尝试，bidirectional=True也是支持的
> 但是torch默认是linear_before_reset的，这个实现跟Paddle是不一样的，所以很可能会遇到
> 
> > python -m onnx2fluid sample_2.onnx -t sample_2.npz
> > ...
> > AssertionError: only linear_before_reset = 0 supported
> 
> 无视这个选项强转出来应该结果会有差别，
> 算子实现的兼容性问题还需要 @jiangjiajun 来看下能否解决

目前我们基本已经把之前分支涉及到CV相关的算子都Merge到develop版本，NLP的算子目前已经在排期测试哈

**Comment by richlaji** [comment]
@jiangjiajun 好的感谢~想问一下GRU或者LSTM像MacroBull提到的linear_before_reset的实现不同的问题是不是比较难解决~

**Comment by MacroBull** [comment]
@richlaji 不好意思，我这边刚才确认了下，对LSTM和GRU的bidirectional=True的支持还是有问题的，目前双向算子还是没法正确转换的，耽误你的时间了，有后续进展我们会在这个issue下同步的，谢谢你的关注

**Comment by richlaji** [comment]
@MacroBull 好的感谢告知~期待后续的更新
