### ISSUE TITLE
不支持instance normalization吗

### ISSUE THREAD

**Issue by mathfinder** [PaddlePaddle/X2Paddle#133]
![image](https://user-images.githubusercontent.com/23050243/64674201-bcde8180-d4a2-11e9-9562-d5c214368cf4.png)

**Comment by jiangjiajun** [comment]
Hi，你好，你用的x2paddle是什么版本呢，目前onnx已经支持instance normalization，可以拉取最新代码重新安装使用

**Comment by mathfinder** [comment]
就刚刚拉取的版本，
![image](https://user-images.githubusercontent.com/23050243/64678367-fbc50500-d4ab-11e9-89a8-c55dcfa479f5.png)

这是版本号吗？

**Comment by jiangjiajun** [comment]
使用develop分支 https://github.com/PaddlePaddle/X2Paddle/tree/develop
