### ISSUE TITLE
 'TENSOR_TYPE_TO_NP_TYPE'

### ISSUE THREAD

**Issue by richlaji** [PaddlePaddle/X2Paddle#135]
x2paddle/op_mapper/onnx_op_mapper.py line511
NameError: name 'TENSOR_TYPE_TO_NP_TYPE' is not defined

**Comment by richlaji** [comment]
from onnx.mapping import TENSOR_TYPE_TO_NP_TYPE 可以解决

**Comment by jiangjiajun** [comment]
> from onnx.mapping import TENSOR_TYPE_TO_NP_TYPE 可以解决

多谢反馈，我们会尽快修复这个问题
