### ISSUE TITLE
Ops are not supported yet:Sqrt,MirrorPad,Square

### ISSUE THREAD

**Issue by didikee** [PaddlePaddle/X2Paddle#156]
(paddle) bash-3.2$ x2paddle --framework=tensorflow --model=/Users/dev01/下载目录/测试model.pb/Angel_a025_c256_s512_a0.25_b2_sn16-32000_frozen.pb --save_dir=/Users/dev01/下载目录/paddle
Now translating model from tensorflow to paddle.
Total nodes: 468
Converting node 468 ...    ==========3 Ops are not supported yet======
========== Sqrt ==========
========== MirrorPad ==========
========== Square ==========

**Comment by jiangjiajun** [comment]
> (paddle) bash-3.2$ x2paddle --framework=tensorflow --model=/Users/dev01/下载目录/测试model.pb/Angel_a025_c256_s512_a0.25_b2_sn16-32000_frozen.pb --save_dir=/Users/dev01/下载目录/paddle
> Now translating model from tensorflow to paddle.
> Total nodes: 468
> Converting node 468 ... ==========3 Ops are not supported yet======
> ========== Sqrt ==========
> ========== MirrorPad ==========
> ========== Square ==========

Hello， Could your provide your tensorflow model for us to analysis?

**Comment by jiangjiajun** [comment]
Hello, this issue will be closed since there is no update information for 15 days. 
If you need, you can reopen this issue anytime. :)
