### ISSUE TITLE
version must be larger than 3.6.0!

### ISSUE THREAD

**Issue by CerrieJ** [PaddlePaddle/X2Paddle#178]
这代码是谁写的???
![image](https://user-images.githubusercontent.com/15920960/67254674-f4344b00-f4b0-11e9-9e87-27c50d926b65.png)
![image](https://user-images.githubusercontent.com/15920960/67254685-feeee000-f4b0-11e9-96fe-d91bf8af1398.png)
![image](https://user-images.githubusercontent.com/15920960/67254690-04e4c100-f4b1-11e9-85d1-6429fb50fe87.png)

**Comment by SunAhong1993** [comment]
> 这代码是谁写的???
> ![image](https://user-images.githubusercontent.com/15920960/67254674-f4344b00-f4b0-11e9-9e87-27c50d926b65.png)
> ![image](https://user-images.githubusercontent.com/15920960/67254685-feeee000-f4b0-11e9-96fe-d91bf8af1398.png)
> ![image](https://user-images.githubusercontent.com/15920960/67254690-04e4c100-f4b1-11e9-85d1-6429fb50fe87.png)

您好~在最新版的代码中已修复此问题了，您可clone最新版的代码，来进行转换。
