### ISSUE TITLE
Can X2Paddle convert SSD_mobileNet_V1 model zoo pretrained in tensorflow?

### ISSUE THREAD

**Issue by dehuy69** [PaddlePaddle/X2Paddle#183]
I download SSD_Mobilenet Tensorflow detection model zoo from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md and use X2Paddle convert to Paddle-lite model and use it run on an Neural Network Inference Engine supported by huawei chip. BUT none of them success. Could you please do a try and give me some suggest?

**Comment by jiangjiajun** [comment]
Hi, SSD(tf version) is not supported and the mainly problem is the control flow in this model.   SSD in caffe version is supported. [SSD-MobileNet](https://github.com/chuanqi305/MobileNet-SSD)
