### ISSUE TITLE
x2paddle transfer model of tensorflow, report error.

### ISSUE THREAD

**Issue by liuhong-lh** [PaddlePaddle/X2Paddle#201]
(venv-python36) PS D:\tensorflow-learning\venv-python36\Scripts> x2paddle -m D:\work\AI\model\mobilenet_v1_1.0_224_frozen\mobilenet_v1_1.0_224_frozen.pb -s D:\work\AI\PaddlePaddleLite -f tensorflow -f tensorflow

### paddlepaddle not installed, use "pip install paddlepaddle"
1.0.0<=tensorflow<2.0.0 is required, and v1.14.0 is recommended

but paddlepaddle installed . And use "pip list" can see : "paddlepaddle 1.6.1"

**Comment by jiangjiajun** [comment]
> (venv-python36) PS D:\tensorflow-learning\venv-python36\Scripts> x2paddle -m D:\work\AI\model\mobilenet_v1_1.0_224_frozen\mobilenet_v1_1.0_224_frozen.pb -s D:\work\AI\PaddlePaddleLite -f tensorflow -f tensorflow
> 
> ### paddlepaddle not installed, use "pip install paddlepaddle"
> 1.0.0<=tensorflow<2.0.0 is required, and v1.14.0 is recommended
> 
> but paddlepaddle installed . And use "pip list" can see : "paddlepaddle 1.6.1"

『paddlepaddle not installed, use "pip install paddlepaddle"』 this will happen under the following codes,

https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/convert.py#L205 
```
    try:
        import paddle
        v0, v1, v2 = paddle.__version__.split('.')
        if int(v0) != 1 or int(v1) < 6:
            print("paddlepaddle>=1.6.0 is required")
            return
    except:
        print("paddlepaddle not installed, use \"pip install paddlepaddle\"")
```

you may need to check your python environment, try to  reinstall x2paddle and paddlepaddle to solve this problem.

```
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
git checkout develop
python setup.py install
```
