### ISSUE TITLE
GPT-2模型转换时出错。

### ISSUE THREAD

**Issue by 914295860** [PaddlePaddle/X2Paddle#202]
在我使用onnx转paddle时候，报错：
There are 1 ops not supported yet, list as below
NonZero

希望能尽快支持

模型位置：https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2/model

**Comment by Channingss** [comment]
感谢您的关注和反馈，NonZero已经在我们的开发计划中，开发好第一时间告知您。

**Comment by Channingss** [comment]
@914295860 #205 更新了对NonZero的支持

**Comment by Channingss** [comment]
@914295860 #206支持了NonZero

**Comment by Channingss** [comment]
@914295860 请问是不是用的这个[model](https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2/model)，这个model暂时还不支持。

**Comment by 914295860** [comment]
> 
> 
> @914295860 请问是不是用的这个[model](https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2/model)，这个model暂时还不支持。

没错，就是这个。希望能尽快提供支持吧。

**Comment by AnShengqiang** [comment]
请问现在支持了吗？

**Comment by empty-id** [comment]
求支持+1

**Comment by Channingss** [comment]
@AnShengqiang @null-id @914295860 可以试试https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle_model_zoo.md#onnx 列表来自于huggingface的GPT2
