### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by billmguo** [PaddlePaddle/X2Paddle#210]
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.6.0', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/convert.py", line 227, in main
    args.caffe_proto, params_merge)
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/convert.py", line 145, in caffe2paddle
    model = CaffeDecoder(proto, weight, caffe_proto)
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/decoder/caffe_decoder.py", line 228, in __init__
    self.load_using_pb()
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/decoder/caffe_decoder.py", line 237, in load_using_pb
    data.MergeFromString(open(self.model_path, 'rb').read())
google.protobuf.message.DecodeError: Error parsing message

This issue happen when convert a caffe model to paddle paddle model, any specified requirement on google protobuf? I am installing the python3 protobuf.

**Comment by jiangjiajun** [comment]
> Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 11, in
> load_entry_point('x2paddle==0.6.0', 'console_scripts', 'x2paddle')()
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/convert.py", line 227, in main
> args.caffe_proto, params_merge)
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/convert.py", line 145, in caffe2paddle
> model = CaffeDecoder(proto, weight, caffe_proto)
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/decoder/caffe_decoder.py", line 228, in **init**
> self.load_using_pb()
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-0.6.0-py3.5.egg/x2paddle/decoder/caffe_decoder.py", line 237, in load_using_pb
> data.MergeFromString(open(self.model_path, 'rb').read())
> google.protobuf.message.DecodeError: Error parsing message
> 
> This issue happen when convert a caffe model to paddle paddle model, any specified requirement on google protobuf? I am installing the python3 protobuf.

google.protobuf >= 3.6.0 is required, but it seems that there's problem exists in your model file, you may need to  check your "prototxt" file.

**Comment by jiangjiajun** [comment]
The issue is closed now, but you can reopen it if you need.
