### ISSUE TITLE
IndexError: list index out of range? 

### ISSUE THREAD

**Issue by ghimiredhikura** [PaddlePaddle/X2Paddle#213]
Hi, 

x2paddle conversion gives this error. I used Ubuntu18.04 in VitrualBox. 

Model: [ssd_mobilenet_custom.zip](https://github.com/PaddlePaddle/X2Paddle/files/3915001/ssd_mobilenet_custom.zip)

```
x2paddle --framework=caffe --prototxt=deploy.prototxt --weight=coco/ssd_mobilenet_custom.caffemodel --save_dir=pd_model
Now translating model from caffe to paddle.
Total nodes: 268
Traceback (most recent call last):
  File "/home/ghimire/.local/bin/x2paddle", line 11, in <module>
    sys.exit(main())
  File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 227, in main
    args.caffe_proto, params_merge)
  File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 146, in caffe2paddle
    mapper = CaffeOpMapper(model)
  File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 51, in __init__
    self.deal_custom_layer(node)
  File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 944, in deal_custom_layer
    input = self.graph.get_bottom_node(input, idx=0, copy=True)
  File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/decoder/caffe_decoder.py", line 204, in get_bottom_node
    input_node_name = node.inputs[idx]
IndexError: list index out of range
```
Please help. 

Best,
Deepak

**Comment by SunAhong1993** [comment]
> Hi,
> 
> x2paddle conversion gives this error. I used Ubuntu18.04 in VitrualBox.
> 
> Model: [ssd_mobilenet_custom.zip](https://github.com/PaddlePaddle/X2Paddle/files/3915001/ssd_mobilenet_custom.zip)
> 
> ```
> x2paddle --framework=caffe --prototxt=deploy.prototxt --weight=coco/ssd_mobilenet_custom.caffemodel --save_dir=pd_model
> Now translating model from caffe to paddle.
> Total nodes: 268
> Traceback (most recent call last):
>   File "/home/ghimire/.local/bin/x2paddle", line 11, in <module>
>     sys.exit(main())
>   File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 227, in main
>     args.caffe_proto, params_merge)
>   File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 146, in caffe2paddle
>     mapper = CaffeOpMapper(model)
>   File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 51, in __init__
>     self.deal_custom_layer(node)
>   File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 944, in deal_custom_layer
>     input = self.graph.get_bottom_node(input, idx=0, copy=True)
>   File "/home/ghimire/.local/lib/python2.7/site-packages/x2paddle/decoder/caffe_decoder.py", line 204, in get_bottom_node
>     input_node_name = node.inputs[idx]
> IndexError: list index out of range
> ```
> 
> Please help.
> 
> Best,
> Deepak

This problem is because that we forget to deal with "Sigmoid" op before DetectionOutput model.  We have fix this problem. Thanks!

**Comment by ghimiredhikura** [comment]
Thanks for your quick response
> 
> This problem is because that we forget to deal with "Sigmoid" op before DetectionOutput model. We have fix this problem. Thanks!

Is this also fixed in `pip install x2paddle --index https://pypi.Python.org/simple/` ?

Thanks.

**Comment by jiangjiajun** [comment]
> Thanks for your quick response
> 
> > This problem is because that we forget to deal with "Sigmoid" op before DetectionOutput model. We have fix this problem. Thanks!
> 
> Is this also fixed in `pip install x2paddle --index https://pypi.Python.org/simple/` ?
> 
> Thanks.

yes, pip source is updated, the newest version is x2paddle v0.7

**Comment by ghimiredhikura** [comment]
Thanks.
