### ISSUE TITLE
使用x2paddle转换之后的模型进行预测，是否必须要求预测库paddle>1.6.0

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/X2Paddle#217]
如题

使用x2paddle对caffe转模型后，利用paddle预测库进行预测，是否要求预测库paddle>1.6.0

**Comment by jiangjiajun** [comment]
> 如题
> 
> 使用x2paddle对caffe转模型后，利用paddle预测库进行预测，是否要求预测库paddle>1.6.0

X2Paddle中的代码随Paddle版本会进行一些功能的更新，所以最新版本的X2Paddle转换后的模型也是要求在最新版本的Paddle上使用。
如果有需求要使用低版本的Paddle，目前只能尝试使用更早版本的X2Paddle（目前最新为v0.7）。
由于新版本的x2paddle中会修复之前存在的代码bug，支持更多OP，所以仍然建议使用最新版本的x2paddle
```
# v0.5.2 对Paddle版本的要求是1.5.0或更新
pip install x2paddle==0.5.2 --index https://pypi.Python.org/simple/
```
