### ISSUE TITLE
使用paddle训练后的paddle模型可以转caffe模型吗？

### ISSUE THREAD

**Issue by fangwudi** [PaddlePaddle/X2Paddle#219]
使用paddle训练后的paddle模型可以转caffe模型吗？

**Comment by jiangjiajun** [comment]
> 使用paddle训练后的paddle模型可以转caffe模型吗？

目前没有提供此转换工具。但可以关注一下[Paddle2ONNX](https://github.com/PaddlePaddle/paddle2onnx)，支持部分模型从Paddle转至ONNX

**Comment by fangwudi** [comment]
好的，多谢

> > 使用paddle训练后的paddle模型可以转caffe模型吗？
> 
> 目前没有提供此转换工具。但可以关注一下[Paddle2ONNX](https://github.com/PaddlePaddle/paddle2onnx)，支持部分模型从Paddle转至ONNX
