### ISSUE TITLE
使用x2paddle转caffe模型后，paddle1.6.1的C++ inference速度慢了20%以上

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/X2Paddle#220]
caffe模型选用[x2paddle_model_zoo](https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle_model_zoo.md)
中的[shufflenetv2](https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe/releases/tag/v0.1.0)

转模型后，使用paddle1.6.1的 cpu-mkl版本进行预测，比caffe的模型（cpu端）慢20%以上。

**Comment by jiangjiajun** [comment]
X2Paddle并未具体测试过模型转换前后的性能对比。
预测性能上，不同框架OP并不是完全一致的，所以可能会在转换过程中，使用Paddle OP去组合实现Caffe的OP，OP数量的增加，可能会带来一定的性能损失。
预测时间的测试中，也可能会受到一些环境设置的影响，例如是否预测时使用多线程之类的。如果需要优化Paddle的预测速度，可以根据官方网站查阅下相关的文档。
