### ISSUE TITLE
在含有paddle的docker中安装tensor1.14.0后，使用x2paddle工具还是提示未安装tensorflow

### ISSUE THREAD

**Issue by zuoyekun** [PaddlePaddle/X2Paddle#221]
![image](https://user-images.githubusercontent.com/38059903/70456108-77087800-1ae8-11ea-9145-2b9ae2226f79.png)

**Comment by jiangjiajun** [comment]
可以尝试在命令行，直接输入 python， 然后执行以下代码，看是否会有问题
```
import x2paddle
import tensorflow
```

**Comment by jiangjiajun** [comment]
可以尝试在命令行，直接输入 python， 然后执行以下代码，看是否会有问题
```
import x2paddle
import tensorflow
```
