### ISSUE TITLE
为什么onnx转paddle需要是1.6版本的，有没有支持1.4版本的

### ISSUE THREAD

**Issue by DJinsis** [PaddlePaddle/X2Paddle#222]
版本太高，有些不支持

**Comment by jiangjiajun** [comment]
> 版本太高，有些不支持

如果有需求要支持以前版本的Paddle，建议你可以尝试使用更低版本的X2Paddle，可以参考这个Issue https://github.com/PaddlePaddle/X2Paddle/issues/217

**Comment by jiangjiajun** [comment]
由于较长时间没有回复，此issue将会被关闭，若后续有需要跟进的问题，可以随时重新打开，谢谢。
