### ISSUE TITLE
使用x2paddle转换mobilenet(tensorflow),报错

### ISSUE THREAD

**Issue by lantuxin** [PaddlePaddle/X2Paddle#224]
转换命令：x2paddle -f tensorflow -m frozen_inference_graph.pb -s pd_model/ --without_data_format_optimization --define_input_shape
报错情况：
Now translating model from tensorflow to paddle.
Define shape[now is [-1L, -1L, -1L, 3L]] for input tensor[tensor name: "image_tensor']
Use your keyboard type the shape of input tensor below :)
Shape of Input(e.g. None,224,224,3): None,224,224,3
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.6.0', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/convert.py", line 219, in main
    define_input_shape, params_merge)
  File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/convert.py", line 106, in tf2paddle
    model = TFDecoder(model_path, define_input_shape=define_input_shape)
  File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/decoder/tf_decoder.py", line 263, in __init__
    self.tf_graph.build()
  File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/decoder/tf_decoder.py", line 123, in build
    format(in_node, layer_name))
Exception: input[^Preprocessor_map_while_Identity] of node[Preprocessor_map_while_add_y] does not exist in node_map

测试模型及环境配置说明见百度网盘：
链接：https://pan.baidu.com/s/1LTRQdLbGk35KZGL7Mloy_g 
提取码：jm0u 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by jiangjiajun** [comment]
> 转换命令：x2paddle -f tensorflow -m frozen_inference_graph.pb -s pd_model/ --without_data_format_optimization --define_input_shape
> 报错情况：
> Now translating model from tensorflow to paddle.
> Define shape[now is [-1L, -1L, -1L, 3L]] for input tensor[tensor name: "image_tensor']
> Use your keyboard type the shape of input tensor below :)
> Shape of Input(e.g. None,224,224,3): None,224,224,3
> Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 11, in
> load_entry_point('x2paddle==0.6.0', 'console_scripts', 'x2paddle')()
> File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/convert.py", line 219, in main
> define_input_shape, params_merge)
> File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/convert.py", line 106, in tf2paddle
> model = TFDecoder(model_path, define_input_shape=define_input_shape)
> File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/decoder/tf_decoder.py", line 263, in **init**
> self.tf_graph.build()
> File "/usr/local/lib/python2.7/dist-packages/x2paddle-0.6.0-py2.7.egg/x2paddle/decoder/tf_decoder.py", line 123, in build
> format(in_node, layer_name))
> Exception: input[^Preprocessor_map_while_Identity] of node[Preprocessor_map_while_add_y] does not exist in node_map
> 
> 测试模型及环境配置说明见百度网盘：
> 链接：https://pan.baidu.com/s/1LTRQdLbGk35KZGL7Mloy_g
> 提取码：jm0u
> 复制这段内容后打开百度网盘手机App，操作更方便哦

你好，请问模型的来源是TensorFlow/models中的MobileNet实现吗，查看到这个模型的结构较为复杂，且分析到模型共涉及到62个TensorFlow的OP算子，并包括控制流算子，目前X2Paddle不支持该类模型的转换。 目前已经测试可以转换的MobileNet模型可以见X2Paddle 的[模型测试列表](https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle_model_zoo.md)
涉及到的OP算子列表如下
```
  1 Add
  2 All
  3 Assert
  4 BiasAdd
  5 Cast
  6 ConcatV2
  7 Const
  8 Conv2D
  9 DepthwiseConv2dNative
 10 Enter
 11 Equal
 12 Exit
 13 Exp
 14 ExpandDims
 15 Fill
 16 FusedBatchNorm
 17 GatherV2
 18 Greater
 19 GreaterEqual
 20 Identity
 21 Less
 22 LogicalAnd
 23 LoopCond
 24 Maximum
 25 Merge
 26 Minimum
 27 Mul
 28 NextIteration
 29 NonMaxSuppressionV3
 30 NoOp
 31 Pack
 32 Pad
 33 Placeholder
 34 Range
 35 RealDiv
 36 Relu6
 37 Reshape
 38 ResizeBilinear
 39 Select
 40 Shape
 41 Sigmoid
 42 Size
 43 Slice
 44 Split
 45 Sqrt
 46 Squeeze
 47 StridedSlice
 48 Sub
 49 Sum
 50 Switch
 51 TensorArrayGatherV3
 52 TensorArrayReadV3
 53 TensorArrayScatterV3
 54 TensorArraySizeV3
 55 TensorArrayV3
 56 TensorArrayWriteV3
 57 Tile
 58 TopKV2
 59 Transpose
 60 Unpack
 61 Where
 62 ZerosLike
```

**Comment by lantuxin** [comment]
模型是我们使用TensorFlow训练的Mobilenet_SSD。模型测试列表中的确没有支持，但caffe下的Mobilenet_SSD已支持，所以还是希望贵团队早日支持。

**Comment by jiangjiajun** [comment]
> 模型是我们使用TensorFlow训练的Mobilenet_SSD。模型测试列表中的确没有支持，但caffe下的Mobilenet_SSD已支持，所以还是希望贵团队早日支持。

TensorFlow中的检测模型多涉及到控制流，目前都无法支持。PaddlePaddle/models中已经有SSD的实现。另外现在有基于Paddle的统一检测模型库PaddleDetection（ https://github.com/PaddlePaddle/PaddleDetection )，里面已经包含了大量常用和最新的检测模型，包括SSD，建议可以尝试使用：）

**Comment by jiangjiajun** [comment]
此issue已被关闭，若仍有需求，可随时再打开。:)
