### ISSUE TITLE
HI,if I want to transfer tensorflow code into paddle ,how do I change the session part?

### ISSUE THREAD

**Issue by Xshelton** [PaddlePaddle/X2Paddle#225]
with tf.Session() as sess:
  sess.run(init)
  sess.run([train_op], feed_dict={
            x: batch_xs,
            y: batch_ys,
        })
something like that,? thanks

**Comment by jiangjiajun** [comment]
This document shows how to export tensorflow model with ".pb" format

https://github.com/PaddlePaddle/X2Paddle/blob/develop/export_tf_model.md

**Comment by Xshelton** [comment]
> This document shows how to export tensorflow model with ".pb" format
> 
> https://github.com/PaddlePaddle/X2Paddle/blob/develop/export_tf_model.md

 I mean I want to retrain my model in paddlepaddle as it does not support tensorflow-gpu. But, In my program, there are some sentence like "sess", Is there anything in pdpd that may be in correspondence to the sentence like "sess"? thanks.

**Comment by jiangjiajun** [comment]
Simple Code for Linear Regression

for your case, 'sess' seems like 'exe' in paddlepaddle
```
import paddle.fluid as fluid
import numpy as np

outputs = np.random.randint(5, size=(10, 4))
res = []
for i in range(10):
        # 假设方程式为 y=4a+6b+7c+2d
        y = 4*outputs[i][0]+6*outputs[i][1]+7*outputs[i][2]+2*outputs[i][3]
        res.append([y])
# 定义数据
train_data=np.array(outputs).astype('float32')
y_true = np.array(res).astype('float32')


# network
x = fluid.layers.data(name="x",shape=[4],dtype='float32')
y = fluid.layers.data(name="y",shape=[1],dtype='float32')
y_predict = fluid.layers.fc(input=x,size=1,act=None)
# loss function
cost = fluid.layers.square_error_cost(input=y_predict,label=y)
avg_cost = fluid.layers.mean(cost)
# optimizer
sgd_optimizer = fluid.optimizer.SGD(learning_rate=0.05)
sgd_optimizer.minimize(avg_cost)
# initialization
cpu = fluid.CPUPlace()
exe = fluid.Executor(cpu)
exe.run(fluid.default_startup_program())

# start training
for i in range(500):
        outs = exe.run(
                feed={'x':train_data,'y':y_true},
                fetch_list=[y_predict.name,avg_cost.name])
        if i%50==0:
                print ('iter={:.0f},cost={}'.format(i,outs[1][0]))
# save parameter
params_dirname = "result"
fluid.io.save_inference_model(params_dirname, ['x'], [y_predict], exe)
```

**Comment by Xshelton** [comment]
okay, that's it. thanks a lot. I will try to transfer my tf version into pd version . Thx
