### ISSUE TITLE
Convert paddle model to tensorflow

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/X2Paddle#229]
### I am not good at paddlehub. I am usually use tensorflow python. Therefore, I need convert __model__ __param__ in paddlehub to  model tensorflow. How can I do it, or load __moddel__ __param__ by tensorflow? Thank in advance.

```
__model__.nb    ----->   model.pb or model.h5
__param__.nb   ----->  param 
```

**Comment by jiangjiajun** [comment]
> ### I am not good at paddlehub. I am usually use tensorflow python. Therefore, I need convert **model** **param** in paddlehub to model tensorflow. How can I do it, or load **moddel** **param** by tensorflow? Thank in advance.
> ```
> __model__    ----->   model.pb or model.h5
> __param__   ----->  param
> ```

Hi， Which model in PaddleHub you want to convert? And is there any problem while you use PaddleHub?

**Comment by phamkhactu** [comment]
Thank for responding. I want convert face_detection model.nb to model.pb or model.h5. Can you tutorial me step by step to convert.

**Comment by phamkhactu** [comment]
if not converted to tensorflow. Can you give me some code to load model.nb and param.nb ?
I am a newbie, but i love it so much. I want to dig it more and more.

**Comment by jiangjiajun** [comment]
> Thank for responding. I want convert face_detection model.nb to model.pb or model.h5. Can you tutorial me step by step to convert.

"face_detection model.nb" I'm not sure which model in PaddleHub you are referencing. 
This document shows how to use pyramidbox_lite_server to detect human face
https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server&en_category=ObjectDetection

**Comment by phamkhactu** [comment]
I get it in a wget https://paddle-inference-dist.bj.bcebos.com/mask_detection.tar.gz. I think it i paddle model. It is saved binary weight. I try out read with https://blog.csdn.net/ymznice/article/details/88826328. but this show error: google.protobuf.message.DecodeError: Error parsing message. I think it caused by not model  tensorflow can be read.

**Comment by jiangjiajun** [comment]
> I get it in a wget https://paddle-inference-dist.bj.bcebos.com/mask_detection.tar.gz. I think it i paddle model. It is saved binary weight. I try out read with https://blog.csdn.net/ymznice/article/details/88826328. but this show error: google.protobuf.message.DecodeError: Error parsing message. I think it caused by not model tensorflow can be read.

Mask Detection in PaddleHub: https://www.paddlepaddle.org.cn/hub/scene/maskdetect

**Comment by phamkhactu** [comment]
but, in my purpose, i want to convert model.nb (binary model) to keras model.

**Comment by jiangjiajun** [comment]
> > I get it in a wget https://paddle-inference-dist.bj.bcebos.com/mask_detection.tar.gz. I think it i paddle model. It is saved binary weight. I try out read with https://blog.csdn.net/ymznice/article/details/88826328. but this show error: google.protobuf.message.DecodeError: Error parsing message. I think it caused by not model tensorflow can be read.
> 
> Mask Detection in PaddleHub: https://www.paddlepaddle.org.cn/hub/scene/maskdetect

 It's not supported yet, but you can load this model, and export weight by your self.

**Comment by AliSheheryar** [comment]
How can you import this pd model into tensorflow runtime? any guidlines?
Tried all sort of ways to convert it using packages but no success.
