### ISSUE TITLE
pb模型无法读取input tensor name

### ISSUE THREAD

**Issue by wc8287194** [PaddlePaddle/X2Paddle#23]
已训练好的pb模型可以在tensorflow的sess.run中正常调用，在feed_dict字典中的input为
self.graph.get_tensor_by_name('prefix/input_1:0')
在convert.py中设置in_nodes为"prefix/input_1:0"，报错如下
![wrong1](https://user-images.githubusercontent.com/46018261/57302425-bc596700-710d-11e9-8e50-87493e912c98.jpg)
修改in_nodes为‘input_1’，报错相同。

**Comment by jiangjiajun** [comment]
```
python tf2fluid/convert.py --pb_file models/frozen_darknet_yolov3_model.pb \
                                              --in_nodes inputs \
                                              --input_shape None,416,416,3  \
                                              --output_nodes output_boxes  \
                                              --save_dir paddle_model  \
                                              --input_format NHWC \
```
参考上面转换darknet_yolov3的示例，指定输入时，仅指定tensor的name即可，不需在后面加":0"

**Comment by wc8287194** [comment]
感谢回复。尝试过只键入tensor的name，报错完全一样。

**Comment by wc8287194** [comment]
注意到在60行读取input_node_names时把字符串全部拆分为单个字符了，这样在64行想要从从单个字符串set中删除图中读到的tensorname“input_1”，即会报错。
![wrong2](https://user-images.githubusercontent.com/46018261/57342998-07a66080-7174-11e9-922b-be526a7c408e.png)

**Comment by wc8287194** [comment]
非常感谢，已经解决。
