### ISSUE TITLE
请问支持NLP中的ALBERT的模型转换吗

### ISSUE THREAD

**Issue by hdulbj** [PaddlePaddle/X2Paddle#230]

**Comment by jiangjiajun** [comment]
目前未在NLP模型上测试过模型的转换，可以自行测试一下

**Comment by jiangjiajun** [comment]
> _No description provided._

Hi，你好，最近我们新更新了代码，对Bert模型进行了支持，可以尝试使用一下，可以参考这个ISSUE
https://github.com/PaddlePaddle/X2Paddle/issues/239
