### ISSUE TITLE
pytorch->onnx->paddle,  paddle中的_interpolate函数(paddle not support op:resize wiht mode: linear)

### ISSUE THREAD

**Issue by Eric-Zhang1990** [PaddlePaddle/X2Paddle#231]
pytorch->onnx->paddle:
pytorch中调用了F.interpolate(x, scale_factor=[0.5, 0.75], mode="bilinear", align_corners=False), 但是onnx转paddle报错:
![WXWorkCapture_15827237397369](https://user-images.githubusercontent.com/24602893/75349109-131f6f80-58df-11ea-8415-792ab7c74dcb.png)
和issue #142类似, 但是不知道具体怎么解决, 请各位帮忙看看, 谢了

**Comment by Channingss** [comment]
@Eric-Zhang1990 可以先尝试用github源码安装，如果还有问题的话，可以把模型用百度云或者其他方式分享给我。

**Comment by Eric-Zhang1990** [comment]
@Channingss  我用源码编译的, 运行出现下面的错误, 这个怎么解决呢? 谢谢
![WXWorkCapture_15827687087651](https://user-images.githubusercontent.com/24602893/75405148-ba37f180-5947-11ea-9bdf-50316969f3fe.png)

**Comment by Eric-Zhang1990** [comment]
@Channingss  onnx的opset_version不同错误也不一样, 下面是opset_version=11的错误:
![3](https://user-images.githubusercontent.com/24602893/75405793-a2fa0380-5949-11ea-9826-afe807f1626b.png)

**Comment by Eric-Zhang1990** [comment]
@Channingss  我把onnx模型发到你163邮箱了, 谢谢

**Comment by Eric-Zhang1990** [comment]
@Channingss   我刚试了另外一个方法，就是把后面用到interpolate的网络先不加载，只转换前面一部分，这样onnx转paddle没有报错. 
所以是不是还是interpolate的bug呢?谢谢

**Comment by Channingss** [comment]
@Eric-Zhang1990 收到，我看下模型。

**Comment by Eric-Zhang1990** [comment]
@Channingss  请问问题找到了吗？是interpolate的原因吗？tkx

**Comment by Channingss** [comment]
@Eric-Zhang1990 是interpolate的问题，需要花点时间定位下具体问题，尽快回复

**Comment by Channingss** [comment]
@Eric-Zhang1990 #232 ，亲测使用opset_version==10可以转换。

**Comment by Eric-Zhang1990** [comment]
@Channingss  请问你是把我给你的onnx模型（opset_version=10）转paddle转成功了是吗？ tkx

**Comment by Eric-Zhang1990** [comment]
@Channingss  你这边是转换成功了是吗?  能怎么验证转换后的模型是不是正确呢? 谢谢

**Comment by Channingss** [comment]
@Eric-Zhang1990 我这边是转换成功了，但代码还没有合入，可以先到我提交PR的repo下面去clone。你可以对比一张图片看原来的模型和转换模型的输出。

**Comment by Eric-Zhang1990** [comment]
@Channingss  我测试过, 转换后的模型用生成的model.py能输出结果, 输入矩阵ones(1,3,513,513), 不过原模型和转换后的模型结果不一致.

**Comment by Eric-Zhang1990** [comment]
@Channingss  我转换后的模型有200多M (原项目地址: https://github.com/kazuto1011/deeplab-pytorch), 我把转换后的模型移植到安卓端, 但是移动加载模型时就报了个错:
A/libc: /Volumes/Android/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
还没找到解决方法, 是不是模型太大的原因呢? 你有遇到过这个错误吗? 谢谢

(我用的是我发给你的onnx模型转换的, 安卓端运行的paddle-lite的分割例子, 我就只把模型替换了, 然后运行报了那个错, 你看你能不能也用转换后的模型在安卓端paddle-lite的分割例子运行试试呢? 谢谢)

**Comment by Channingss** [comment]
@Eric-Zhang1990 1.原模型和转换后的模型结果不一致的问题，我刚刚查了一下是因为paddle目前只支持bilinear：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#resize-bilinear
，你那边onnx的模型的resize使用的是linear模式

**Comment by Channingss** [comment]
@Eric-Zhang1990 2.如果你使用Lite的model_optimize_tool能转换过去没报错，说明Lite对这个模型的OP支持是没问题的。另外，Lite那边两百兆的模型部署到安卓端，看报错像是模型太大了的问题。这么大的模型到安卓端跑起来性能跟不上的，其实是不合理的哈。分割的demo配置的时候，HW是反的，你注意一下。

**Comment by Eric-Zhang1990** [comment]
> @Eric-Zhang1990 1.原模型和转换后的模型结果不一致的问题，我刚刚查了一下是因为paddle目前只支持bilinear：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#resize-bilinear
> ，你那边onnx的模型的resize使用的是linear模式

我在pytorch中用的是bilinear (F.interpolate(x, scale_factor=[0.5, 0.75], mode="bilinear", align_corners=False)), 转onnx后再转paddle后x2paddle显示的是linear, 和issue#142一样, 不过不知道他是怎么修改的.

**Comment by Eric-Zhang1990** [comment]
> @Eric-Zhang1990 2.如果你使用Lite的model_optimize_tool能转换过去没报错，说明Lite对这个模型的OP支持是没问题的。另外，Lite那边两百兆的模型部署到安卓端，看报错像是模型太大了的问题。这么大的模型到安卓端跑起来性能跟不上的，其实是不合理的哈。分割的demo配置的时候，HW是反的，你注意一下。

我也在找小一点的deeplab的模型, 不过还没找到, 不知道你有没有小一点的deeplab模型(onnx和tensorflow都可以) 呢? 谢谢

**Comment by Channingss** [comment]
@Eric-Zhang1990 如果pytorch中用的是bilinear，那理论上Paddle这边应该没有diff才对，我再确认下吧

**Comment by Channingss** [comment]
@Eric-Zhang1990 咱们自己的model库里面有deeplab:
https://github.com/PaddlePaddle/PaddleSeg

**Comment by jiangjiajun** [comment]
由于长久时间没更新，此issue目前被关闭，如若有需求，可随时再重新打开。

**Comment by Daniel-Kelvich** [comment]
I have the same problem. @Channingss have you manage to resolve this issue somehow?
