### ISSUE TITLE
X2Paddle支持任意大小的输入吗？

### ISSUE THREAD

**Issue by czczup** [PaddlePaddle/X2Paddle#233]
我想用Paddle-Lite在移动端部署快速风格迁移模型，模型的输入shape是(1, None, None, 3)，输出的shape和输入的shape相同。我从tensorflow的pb格式转换为paddle的格式会报错：
```
Shape[now is [1, -1, -1, 3]] for input tensor[tensor name: "input"] not support yet
Use your keyboard type the shape of input tensor below :)
```
我看[FAQ](https://github.com/PaddlePaddle/X2Paddle/blob/develop/FAQ.md)中说**需要用户手动在提示后输入详细的shape信息，如None,224,224,3**。

我希望我的模型支持任意大小的输入，请问该怎么操作才能实现？

**Comment by jiangjiajun** [comment]
> 我想用Paddle-Lite在移动端部署快速风格迁移模型，模型的输入shape是(1, None, None, 3)，输出的shape和输入的shape相同。我从tensorflow的pb格式转换为paddle的格式会报错：
> 
> ```
> Shape[now is [1, -1, -1, 3]] for input tensor[tensor name: "input"] not support yet
> Use your keyboard type the shape of input tensor below :)
> ```
> 
> 我看[FAQ](https://github.com/PaddlePaddle/X2Paddle/blob/develop/FAQ.md)中说**需要用户手动在提示后输入详细的shape信息，如None,224,224,3**。
> 
> 我希望我的模型支持任意大小的输入，请问该怎么操作才能实现？

你好，PaddleLite目前除batch维可以为None外，其余维度要求是固定的输入

**Comment by JINGTING92** [comment]
请问要在the shape of input tensor below: 后面输入怎样的形式呢？我尝试输入None, 513, 513, 3和1, 513, 513, 3都不对

**Comment by jiangjiajun** [comment]
> 请问要在the shape of input tensor below: 后面输入怎样的形式呢？我尝试输入None, 513, 513, 3和1, 513, 513, 3都不对

不需要空格，输入1,513,513,3
