### ISSUE TITLE
PaddlePaddle 2 Tensorflow/ONNX

### ISSUE THREAD

**Issue by loretoparisi** [PaddlePaddle/X2Paddle#238]
Is it possibile to do the opposite? I would like to convert a pretrained PaddlePaddle model to Tensorflow (or Pytorch) by example

Thanks

**Comment by jiangjiajun** [comment]
> Is it possibile to do the opposite? I would like to convert a pretrained PaddlePaddle model to Tensorflow (or Pytorch) by example
> 
> Thanks

We have provided Paddle2ONNX which supports parts of paddle model converting to ONNX。
https://github.com/PaddlePaddle/paddle2onnx

**Comment by loretoparisi** [comment]
@jiangjiajun awesome thank you!
