### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by matfeb** [PaddlePaddle/X2Paddle#242]
Hi,

Model = MobileNet_v2_1.0 224 from TensorFlow hub models

MobileNet_v1_1.0 and SqueezeNet 1.1 have been converted without any issue.

`x2paddle --framework=tensorflow --model=mobilenet_v2_1.0_224_frozen.pb --save_dir=pd_model` gave me 

```bash
paddle.__version__ = 1.7.1
Now translating model from tensorflow to paddle.
Traceback (most recent call last):
  File "/home/mfebvay/.local/bin/x2paddle", line 11, in <module>
    sys.exit(main())
  File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 237, in main
    define_input_shape, params_merge)
  File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 108, in tf2paddle
    model = TFDecoder(model_path, define_input_shape=define_input_shape)
  File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/decoder/tf_decoder.py", line 299, in __init__
    input_map = self._check_input_shape(graph_def)
  File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/decoder/tf_decoder.py", line 344, in _check_input_shape
    shape = graph_node.out_shapes[0]
IndexError: list index out of range
```

Related to #213 ?

Thanks.

**Comment by jiangjiajun** [comment]
> Hi,
> 
> Model = MobileNet_v2_1.0 224 from TensorFlow hub models
> 
> MobileNet_v1_1.0 and SqueezeNet 1.1 have been converted without any issue.
> 
> `x2paddle --framework=tensorflow --model=mobilenet_v2_1.0_224_frozen.pb --save_dir=pd_model` gave me
> 
> ```shell
> paddle.__version__ = 1.7.1
> Now translating model from tensorflow to paddle.
> Traceback (most recent call last):
>   File "/home/mfebvay/.local/bin/x2paddle", line 11, in <module>
>     sys.exit(main())
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 237, in main
>     define_input_shape, params_merge)
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 108, in tf2paddle
>     model = TFDecoder(model_path, define_input_shape=define_input_shape)
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/decoder/tf_decoder.py", line 299, in __init__
>     input_map = self._check_input_shape(graph_def)
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/decoder/tf_decoder.py", line 344, in _check_input_shape
>     shape = graph_node.out_shapes[0]
> IndexError: list index out of range
> ```
> 
> Related to #213 ?
> 
> Thanks.

Hi , Could you provide your model `mobilenet_v2_1.0_224_frozen.pb` for us to debug code?

**Comment by jiangjiajun** [comment]
> Hi,
> 
> Model = MobileNet_v2_1.0 224 from TensorFlow hub models
> 
> MobileNet_v1_1.0 and SqueezeNet 1.1 have been converted without any issue.
> 
> `x2paddle --framework=tensorflow --model=mobilenet_v2_1.0_224_frozen.pb --save_dir=pd_model` gave me
> 
> ```shell
> paddle.__version__ = 1.7.1
> Now translating model from tensorflow to paddle.
> Traceback (most recent call last):
>   File "/home/mfebvay/.local/bin/x2paddle", line 11, in <module>
>     sys.exit(main())
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 237, in main
>     define_input_shape, params_merge)
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/convert.py", line 108, in tf2paddle
>     model = TFDecoder(model_path, define_input_shape=define_input_shape)
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/decoder/tf_decoder.py", line 299, in __init__
>     input_map = self._check_input_shape(graph_def)
>   File "/home/mfebvay/.local/lib/python2.7/site-packages/x2paddle/decoder/tf_decoder.py", line 344, in _check_input_shape
>     shape = graph_node.out_shapes[0]
> IndexError: list index out of range
> ```
> 
> Related to #213 ?
> 
> Thanks.

Thanks for reporting this problem, I just found a bug in my code, which is caused by code upgrade recently. I have fix the bug, please try to pull the latest code of X2Paddle :)
```
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
git checkout develop
pip uninstall x2paddle
python setup.py install
```

**Comment by matfeb** [comment]
Hello,

thanks for your fix.
It's working now, not with pip install be with git clone it's allright.

The model is from TFLite hub [https://www.tensorflow.org/lite/guide/hosted_models](url)

Regards,
