### ISSUE TITLE
用x2paddle转pytorch模型报错

### ISSUE THREAD

**Issue by qhpeklh5959** [PaddlePaddle/X2Paddle#243]

**Comment by qhpeklh5959** [comment]
![image](https://user-images.githubusercontent.com/5755812/78239553-6a34e780-7510-11ea-9f93-5cfe2a516908.png)
报错显示有一个操作不支持

**Comment by Channingss** [comment]
@qhpeklh5959 hi，我们刚刚新增了OP:Erf的转换，可以clone最新的代码，然后手动安装x2paddle。

**Comment by qhpeklh5959** [comment]
> @qhpeklh5959 hi，我们刚刚新增了OP:Erf的转换，可以clone最新的代码，然后手动安装x2paddle。

赞效率，感谢~
pytorch模型参数的话是不是不能是None啊，我看中间还报了一个错
![image](https://user-images.githubusercontent.com/5755812/78335249-d91d4980-75bf-11ea-980a-520c9dffd031.png)

**Comment by Channingss** [comment]
麻烦提供一下ONNX的模型文件

**Comment by qhpeklh5959** [comment]
> 麻烦提供一下ONNX的模型文件

https://ecloud.baidu.com?t=b5f081b34b2497c1d4272a79d9bbd411

**Comment by Channingss** [comment]
@qhpeklh5959 分享的地址好像不对
![image](https://user-images.githubusercontent.com/12471701/79571109-356a8800-80ed-11ea-950e-5f42145ab105.png)

**Comment by qhpeklh5959** [comment]
> @qhpeklh5959 分享的地址好像不对
> ![image](https://user-images.githubusercontent.com/12471701/79571109-356a8800-80ed-11ea-950e-5f42145ab105.png)

不好意思，点错了，这个应该对了
https://ecloud.baidu.com?t=4d15161690fd04a15934d0e55b028441

**Comment by Channingss** [comment]
@qhpeklh5959  我们在转换的过程中，有些op需要用到输出的shape。目前对onnx做shape inference，有些情况下shape推理不出来，可以参看onnx官方给出的说明：https://github.com/onnx/onnx/blob/master/docs/ShapeInference.md#limitations
未来我们会考虑解决这个问题。

**Comment by jiangjiajun** [comment]
此issue长时间未更新，将被关闭，若有需求可随时再打开
