### ISSUE TITLE
Support Caffe FasteRCNN to paddle model?

### ISSUE THREAD

**Issue by guoqiang0148666** [PaddlePaddle/X2Paddle#246]
Thanks your excellent work!

Could X2Paddle convert Caffe FasteRCNN to paddle model?

Thanks

(l see that custom caffe layer of X2Paddle have't proposal layer)

**Comment by SunAhong1993** [comment]
> Thanks your excellent work!
> 
> Could X2Paddle convert Caffe FasteRCNN to paddle model?
> 
> Thanks
> 
> (l see that custom caffe layer of X2Paddle have't proposal layer)

Sorry, we don't support the FasterRCNN conversion from caffe to paddle. Because the Python layer and proposal layer can't align to paddle op.

**Comment by guoqiang0148666** [comment]
@SunAhong1993 
Thanks.
