### ISSUE TITLE
Paddle lite模型可以转成Tensorflow lite吗

### ISSUE THREAD

**Issue by taoja12** [PaddlePaddle/X2Paddle#248]
目前有一个Paddle Lite的VGG16模型，可以将这个模型转换成Tensorflow Lite模型，然后再去使用吗？

或者，Paddle Lite的模型，可以在TVM上面调用吗？

**Comment by jiangjiajun** [comment]
> 目前有一个Paddle Lite的VGG16模型，可以将这个模型转换成Tensorflow Lite模型，然后再去使用吗？
> 
> 或者，Paddle Lite的模型，可以在TVM上面调用吗？

目前有Paddle2ONNX，可以支持大部分Paddle的分类模型转成onnx格式，可以尝试使用一下。 https://github.com/PaddlePaddle/paddle2onnx
