### ISSUE TITLE
加载tf的meta文件，输出是个tensor的列表，转换失败

### ISSUE THREAD

**Issue by liushanshan07** [PaddlePaddle/X2Paddle#25]
> python tf2fluid/convert.py --meta_file=${meta_file} \
  5     --ckpt_dir=./textnet-part-vgg-synth-8gpu-tf-base/ \
  6     --in_nodes=input_images,input_proposals,input_decoders,input_target_weights \
  7     --input_shape=None,512,512,3 \
  8     --input_format=NHWC \
  9     --output_nodes=model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection/AttnOutputProjection/BiasAdd,model_wo_buckets/embedd    ing_attention_decoder/attention_decoder/AttnOutputProjection_1/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/    AttnOutputProjection_2/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_3/AttnOutputProject    ion/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_4/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_a    ttention_decoder/attention_decoder/AttnOutputProjection_5/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnO    utputProjection_6/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_7/AttnOutputProjection/B    iasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_8/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attent    ion_decoder/attention_decoder/AttnOutputProjection_9/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutput    Projection_10/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_11/AttnOutputProjection/Bias    Add,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_12/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attentio    n_decoder/attention_decoder/AttnOutputProjection_13/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputP    rojection_14/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_15/AttnOutputProjection/BiasA    dd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_16/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention    _decoder/attention_decoder/AttnOutputProjection_17/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputPr    ojection_18/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_19/AttnOutputProjection/BiasAd    d,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_20/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_    decoder/attention_decoder/AttnOutputProjection_21/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputPro    jection_22/AttnOutputProjection/BiasAdd,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_23/AttnOutputProjection/BiasAdd    ,model_wo_buckets/embedding_attention_decoder/attention_decoder/AttnOutputProjection_24/AttnOutputProjection/BiasAdd \
 10     --use_cuda=True \
 11     --save_dir=./save_fluid_model/ \

**Comment by jiangjiajun** [comment]
当指定多个输入或输出时，参数之间有空格分开；此外在指定多个输入的同时，也需要指定每个输入的input_shape,如下面的示例，指定的输入tensor包括`x`和`dropout_probability`，对应的input_shape分别为`[None, 572, 572, 3]`和`[1]`
```
python tf2fluid/convert.py --meta_file ckpt_dir/model.meta \
                                              --ckpt_dir ckpt_dir \
                                              --in_nodes x dropout_probability \
                                              --input_shape None,572,572,3 1 \
                                              --output_nodes results/pixel_wise_softmax/truediv \
                                              --save_dir paddle_model \
                                              --input_format NHWC
```

**Comment by jiangjiajun** [comment]
因长时间没有回复，issue将会被close，若有问题，之后可以重新打开，谢谢
