### ISSUE TITLE
x2paddle现在可以支持nn.GRU了吗

### ISSUE THREAD

**Issue by TreeDiagram-1** [PaddlePaddle/X2Paddle#250]

**Comment by TreeDiagram-1** [comment]
模型如下：
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.gru = nn.GRU(6, 5, 3)
        #self.lstm = nn.LSTM(5, 4, 2)
    def forward(self, x, h1, h2, c2):
        y, h1 = self.gru(x, h1)
        #y, (h2, c2) = self.lstm(y, (h2, c2))
        return y
model = Model()
model.eval()
xb = torch.rand((8, 1, 6))
h1 = torch.zeros((3, 1, 5))
h2 = torch.zeros((2, 1, 4))
c2 = torch.zeros((2, 1, 4))
yp = model(xb, h1, h2, c2)
#torch.onnx.export(model,[xb, h1, h2, c2], 'test_g.onnx',['x', 'h1', 'h2', 'c2'], verbose=True)
export_onnx_with_validation(
        model, [xb, h1, h2, c2], 'test_g',
        ['x', 'h1', 'h2', 'c2'], ['y'],
        verbose=True, training=False)
转成paddle模型的时候报了下面这个错：
Traceback (most recent call last):
  File "./convert.py", line 21, in <module>
    def arg_parser():
  File "./convert.py", line 252, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "./convert.py", line 174, in onnx2paddle
    mapper = ONNXOpMapper(model, save_dir)
  File "/usr/local/lib/python3.5/dist-packages/x2paddle/op_mapper/onnx_op_mapper.py", line 98, in __init__
    func(node)
  File "/usr/local/lib/python3.5/dist-packages/x2paddle/op_mapper/onnx_op_mapper.py", line 524, in Unsqueeze
    if len(val_x.out_shapes[0]) == 0:
TypeError: object of type 'NoneType' has no len()

**Comment by Channingss** [comment]
@TreeDiagram-1  @你好，目前x2paddle支持torch的GRU转换成：[paddle.fluid.layers.dynamic_gru](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/dynamic_gru_cn.html#dynamic-gru)，但两个OP的参数存在差别，目前只支持部分参数的转换，可以参考 #131。
这段代码，我在pytorch1.4.0上跑不起来，能提供转换后的onnx文件吗？

**Comment by jiangjiajun** [comment]
此issue长时间未更新，如有需求，可随时重新打开。
