### ISSUE TITLE
X2Paddle tensorflow报错

### ISSUE THREAD

**Issue by lwbmowgli** [PaddlePaddle/X2Paddle#251]
![%4(V9S)}IL RS97V0P1A )V](https://user-images.githubusercontent.com/32731935/80712654-d7926300-8b24-11ea-9485-2f2730d5d34d.png)
报错信息如上，代码以及我生成的pb文件都在分享链接里。对于这个错误没有任何解决头绪，希望您解答一下，非常感谢。
链接：https://pan.baidu.com/s/1qaAfsb0PbvOE8NJMrAmfhg 
提取码：kpkk

**Comment by jiangjiajun** [comment]
> ![%4(V9S)}IL RS97V0P1A )V](https://user-images.githubusercontent.com/32731935/80712654-d7926300-8b24-11ea-9485-2f2730d5d34d.png)
> 报错信息如上，代码以及我生成的pb文件都在分享链接里。对于这个错误没有任何解决头绪，希望您解答一下，非常感谢。
> 链接：https://pan.baidu.com/s/1qaAfsb0PbvOE8NJMrAmfhg
> 提取码：kpkk

Hi，请问你这里用的tensorflow版本是多少呢

**Comment by lwbmowgli** [comment]
十分抱歉，我有点记不太清了，电脑在老家那边了，看不到具体的信息了，可能是tf1.13或者tf2.0.。

**Comment by jiangjiajun** [comment]
> 十分抱歉，我有点记不太清了，电脑在老家那边了，看不到具体的信息了，可能是tf1.13或者tf2.0.。

我试着用tf 1.14跑会出错，不过目前tf2.0的模型暂不支持转到Paddle

**Comment by jiangjiajun** [comment]
> 十分抱歉，我有点记不太清了，电脑在老家那边了，看不到具体的信息了，可能是tf1.13或者tf2.0.。

Hello，我刚测试了你的代码，我是在tf 1.14.0版本下进行的训练，可以正常训练（先前由于数据路径被编码成Windows上绝对路径导致加载出错）

Tensorflow模型在导出时，注意只需要导出前向计算部分（即模型预测部分，不需要训练部分回传的网络结构），因此我在你在train.py中定义了如下函数
```
def freeze_model(sess, output_tensor_names, freeze_model_path):
    out_graph = graph_util.convert_variables_to_constants(
        sess, sess.graph.as_graph_def(), output_tensor_names)
    with tf.gfile.GFile(freeze_model_path, 'wb') as f:
        f.write(out_graph.SerializeToString())
    print("freeze model saved in {}".format(freeze_model_path))
```
同时将你原代码中如下导出代码
```
#        constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph_def, ['train'])
#        with tf.gfile.FastGFile('model.pb', mode='wb') as f:
#             f.write(constant_graph.SerializeToString())
```
替换为
```
        out_tensor_name = y.name.split(':')[0]
        freeze_model(sess, [out_tensor_name], './model.pb')
```

按如上操作后的代码即可导出tensorflow模型，并使用X2Paddle进行转换。

**Comment by jiangjiajun** [comment]
因issue长时间未更新，将被关闭，如有需求可随时重新打开。
