### ISSUE TITLE
onnx转paddle中遇到问题

### ISSUE THREAD

**Issue by CoderAnn** [PaddlePaddle/X2Paddle#252]
我在onnx转paddle时候遇到了一个问题想请教一下。最开始torch版本是1.1.0转onnx时会报错，之后torch修改为1.0.1后pytorch转onnx没问题了，但是在onnx转paddle时遇到了如下问题，请问该如何解决呢？麻烦了！感谢！（ps：我的网络结构中用到了上采样层）
`Now translating model from onnx to paddle.
model ir_version: 3, op version: 9
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 1585340438
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 1585340438
(op_type:Tanh, name:): Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)
Traceback (most recent call last):
  File "/home/vis/hongzhibin/env/anaconda3/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.7.1', 'console_scripts', 'x2paddle')()
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 248, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 172, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/decoder/onnx_decoder.py", line 325, in __init__
    self.check_model_running_state(onnx_model)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/decoder/onnx_decoder.py", line 481, in check_model_running_state
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)`
另外还尝试过torch版本为1.2.0时转onnx，在onnx转paddle时也遇到问题。无论哪种版本能从onnx转到padlle就可以了。
`Traceback (most recent call last):
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/decoder/onnx_decoder.py", line 494, in check_model_running_state
    sess = rt.InferenceSession(model_path)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 23, in __init__
    self._load_model()
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 35, in _load_model
    self._sess.load_model(self._path_or_bytes, providers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsample.h:209 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.
Stacktrace:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vis/hongzhibin/env/anaconda3/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.7.1', 'console_scripts', 'x2paddle')()
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 248, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 172, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/decoder/onnx_decoder.py", line 325, in __init__
    self.check_model_running_state(onnx_model)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/decoder/onnx_decoder.py", line 503, in check_model_running_state
    "onnxruntime inference onnx model failed, Please confirm the correctness of onnx model by onnxruntime, if onnx model is correct, please submit issue in github."
Exception: onnxruntime inference onnx model failed, Please confirm the correctness of onnx model by onnxruntime, if onnx model is correct, please submit issue in github.`

**Comment by Channingss** [comment]
@CoderAnn 您好，从报错信息来看，您导出的模型用onnxruntime跑不起来，我们需要onnxruntime来推理模型里面各个node的shape。如果torch版本可以run的话，很有可能是从torch转到onnx的时，保存的onnx存在问题。
onnxruntime如何运行模型，可参考下面的API：
https://microsoft.github.io/onnxruntime/python/tutorial.html#step-3-load-and-run-the-model-using-onnx-runtime

**Comment by CoderAnn** [comment]
那您的意思是版本没什么问题哈？那我可以在torch为1.0.1转的onnx模型上去做op的推理？关于使用onnxruntime去推理的问题也可以请教您吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: channings <notifications@github.com&gt;
发送时间: 2020年5月7日 16:05
收件人: PaddlePaddle/X2Paddle <X2Paddle@noreply.github.com&gt;
抄送: CodingAnn <272597709@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/X2Paddle] onnx转paddle中遇到问题 (#252)





 
@CoderAnn 您好，从报错信息来看，您导出的模型用onnxruntime跑不起来，我们需要onnxruntime来推理模型里面各个node的shape。

**Comment by Channingss** [comment]
@CoderAnn 我看您在1.0.1的版本在onnx对模型做shape_inference也出现了问题，onnxruntime使用的问题首先可以考虑到onnxruntime的github主页寻找解决方案，也可以在这个issues下面提问哈。

**Comment by CoderAnn** [comment]
好的，麻烦了！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: channings <notifications@github.com&gt;
发送时间: 2020年5月7日 16:39
收件人: PaddlePaddle/X2Paddle <X2Paddle@noreply.github.com&gt;
抄送: CodingAnn <272597709@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/X2Paddle] onnx转paddle中遇到问题 (#252)





 
@CoderAnn 我看您在1.0.1的版本在onnx对模型做shape_inference也出现了问题，onnxruntime使用的问题首先可以考虑到onnxruntime的github主页寻找解决方案，也可以在这个issues下面提问哈。

**Comment by CoderAnn** [comment]
您好，我在torch=1.0.1版本下的upsample模块修改为指定size的情况下，模型可以转到onnx但是在onnx转paddle时会遇到这种问题，我是将两个pytorch模型转到一起（因为其中一个会调用另一个），和这个有关系吗？还是说这个问题属于上采样模块的问题呢？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: channings <notifications@github.com&gt;
发送时间: 2020年5月7日 16:39
收件人: PaddlePaddle/X2Paddle <X2Paddle@noreply.github.com&gt;
抄送: CodingAnn <272597709@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/X2Paddle] onnx转paddle中遇到问题 (#252)





 
@CoderAnn 我看您在1.0.1的版本在onnx对模型做shape_inference也出现了问题，onnxruntime使用的问题首先可以考虑到onnxruntime的github主页寻找解决方案，也可以在这个issues下面提问哈。

**Comment by CoderAnn** [comment]
您好，我现在遇到了另一个问题不知道您之前遇到过吗？我的模型里使用了torch.nn.PRelU函数，这个函数在onnxruntime上推理会有问题，但是我不清楚该如何修改，如果您也遇到过类似问题，麻烦告知我该如何解决。感谢！
我的代码
`self.input_layer = Sequential(Conv2d(3, 64, (3, 3), 1, 1 ,bias=False),
                                       BatchNorm2d(64),
                                       PReLU(64))`
报错信息：
`2020-05-11 16:35:26.845232609 [E:onnxruntime:, sequential_executor.cc:165 Execute] Non-zero status code returned while running PRelu node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:339 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 64 by 112
Stacktrace:

Traceback (most recent call last):
  File "onnx_model_test.py", line 15, in <module>
    ort_outs = ort_session.run(None, ort_inputs)
  File "/home/vis/hongzhibin/env/anaconda3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 136, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running PRelu node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:339 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 64 by 112
Stacktrace:`

**Comment by CoderAnn** [comment]
您好，我现在转到paddle已经转成功了，但是在测试时会报错，测试代码如下，我的pytorch模型是需要加载另一个预训练好的模型，也就是说我是将两个模型转在一起的。
`     exe = fluid.Executor(fluid.CPUPlace())
     path = "wasserstein_gan_arch/inference_model"
     [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=exe)`
错误信息：
`------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/vis/hongzhibin/env/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/vis/hongzhibin/env/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 697, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/home/vis/hongzhibin/env/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 668, in load_vars
    filename=filename)
  File "/home/vis/hongzhibin/env/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 835, in load_persistables
    filename=filename)
  File "/home/vis/hongzhibin/env/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1314, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "test_paddle_faceshifter.py", line 41, in main2
    fluid.io.load_inference_model(dirname=path, executor=exe)
  File "test_paddle_faceshifter.py", line 95, in <module>
    main2()

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Cannot open file wasserstein_gan_arch/inference_model/x2paddle_id_network_body_16_res_layer_0_running_mean for load op at [/paddle/paddle/fluid/operators/load_op.h:37]
  [operator < load > error]`

**Comment by Channingss** [comment]
@CoderAnn 看上去是某个op的参数load出现了问题，问题解决了吗

**Comment by CoderAnn** [comment]
问题解决了！感谢，麻烦您了！顺便还有个小问题想问问您，我的网络里使用了bilinear做上采样，但是转换到onnx后效果有较大diff，但是用nearest做上采样就没问题，这个有没有好的解决方案呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: channings <notifications@github.com&gt;
发送时间: 2020年5月14日 14:43
收件人: PaddlePaddle/X2Paddle <X2Paddle@noreply.github.com&gt;
抄送: CodingAnn <272597709@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/X2Paddle] onnx转paddle中遇到问题 (#252)





 
@CoderAnn 看上去是某个op的参数load出现了问题，问题解决了吗

**Comment by Channingss** [comment]
@CoderAnn 是不是反了，paddle目前只有bilinear

**Comment by CoderAnn** [comment]
啊，我网络里用的是bilinear但是转到onnx上后效果就有diff，从onnx转到paddle的效果和onnx是一致的。感觉是onnx对bilinear的支持有点问题吧，就是想问问您从pytorch转到onnx时，针对bilinear后结果不一致的问题有没有好的解决方案呢～

**Comment by Channingss** [comment]
@CoderAnn 
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#attributes-131，

onnx这边用linear表征了好几个插值方式：linear (including bilinear, trilinear, etc)，不过感觉bilinear 不会呀，你是对比onnxruntime的输出吗？我这边现在强制是bilinear:https://github.com/PaddlePaddle/X2Paddle/blob/5480c7dc24344ff5eea17b8e764c9d2f5011ac2d/x2paddle/op_mapper/onnx_op_mapper.py#L410

**Comment by CoderAnn** [comment]
是的我对比的是onnx和pytorch的效果，确实很奇怪，如果将插值方式更换为nearest两个模型的输出就无diff了。我目前已经使用finetune了pytorch模型。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: channings <notifications@github.com&gt;
发送时间: 2020年5月14日 20:18
收件人: PaddlePaddle/X2Paddle <X2Paddle@noreply.github.com&gt;
抄送: CodingAnn <272597709@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/X2Paddle] onnx转paddle中遇到问题 (#252)





 
@CoderAnn https://github.com/onnx/onnx/blob/master/docs/Changelog.md#attributes-131，onnx这边用linear表征了好几个插值方式：linear (including bilinear, trilinear, etc)，不过感觉bilinear 不会呀，你是对比onnxruntime的输出吗？我这边现在强制是bilinear:https://github.com/PaddlePaddle/X2Paddle/blob/5480c7dc24344ff5eea17b8e764c9d2f5011ac2d/x2paddle/op_mapper/onnx_op_mapper.py#L410

**Comment by Channingss** [comment]
@CoderAnn 如果paddle这边对的齐pytorch就ok呀

**Comment by jiangjiajun** [comment]
此issue由于长期未更新，将被关闭，如有需求可随时再打开。
