### ISSUE TITLE
caffe转换paddle异常

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/X2Paddle#253]
![123](https://user-images.githubusercontent.com/12640462/81379613-ffdd1b80-913b-11ea-98bf-72dbd6c16f3b.png)
在执行caffee转换的时候出现这个错误，大家有明白的吗，求解释
我的操作命令为：
`x2paddle --framework=caffe --prototxt=XXX.prototxt  --weight=XXX.caffemodel --save_dir=XX`

**Comment by SunAhong1993** [comment]
> 在执行caffee转换的时候出现这个错误，大家有明白的吗，求解释

你好~这个错误是由于ContinuationIndicator是自定义的Caffe OP（在使用Caffe时也需要重新编译带有该OP的Caffe才可以使用），所以目前X2Paddle暂不支持该OP的转换。

**Comment by BeyondYourself** [comment]
OK,get it, thanks

**Comment by 60999** [comment]
我这边也是遇到这种非标的，不知道如何处理。

**Comment by jiangjiajun** [comment]
因issue长时间未更新，将被关闭，如有需要可随时再打开。
