### ISSUE TITLE
有没有办法转torch的state_dict模型

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/X2Paddle#254]
有没有办法转torch模型，而且代码中是encoder.state_dict()
倒是代码和数据集都有，是否有转换的方法？得改代码吗？

**Comment by jiangjiajun** [comment]
只是转换参数，就直接把里面的参数提取出来就行了，Paddle可以有方法加载numpy参数初始化

**Comment by jiangjiajun** [comment]
此issue由于长期未更新，将被关闭，如有需求可随时再打开。
