### ISSUE TITLE
x2paddle: onnx转paddle报错: 1 ops not supported yet:  ReduceL2

### ISSUE THREAD

**Issue by Eric-Zhang1990** [PaddlePaddle/X2Paddle#255]
@Channingss  用x2paddle将onnx模型转paddle模型时出现1个ops不支持的问题, 调试发现是torch.norm操作这一步 (torch.norm(o, p=2, dim=1, keepdim=True) + 0.000001).expand_as(o)), torch.norm转为onnx是onnx::ReduceL2[axes=[1], keepdims=1], x2paddle转onnx模型出现如下错误: 
![error](https://user-images.githubusercontent.com/24602893/81889796-0a356480-95d7-11ea-9f8e-a5124581a00d.png)

请问是不是x2paddle工具确实还不支持ReduceL2呢? 谢谢

**Comment by Channingss** [comment]
@Eric-Zhang1990 目前还不支持

**Comment by Eric-Zhang1990** [comment]
@Channingss  Ok.  我把这操作放在模型转换之外了, 其他都能正常转换, 最后再自己对输出实现这个操作吧, 谢谢

**Comment by Channingss** [comment]
@Eric-Zhang1990 可以的，感谢反馈，我们把这个op加入到开发需求列表。

**Comment by jiangjiajun** [comment]
此issue由于长期未更新，将被关闭，如有需求可随时再打开。
