### ISSUE TITLE
Converting node 894 ...    ==========6 Ops are not supported yet======

### ISSUE THREAD

**Issue by wuyanhong3019** [PaddlePaddle/X2Paddle#256]
您好，我在使用x2paddle转换pb文件至paddlepaddle的时候，遇到以下几个Op不支持的情况，请问能近期能开发支持吗？
Converting node 894 ...    ==========6 Ops are not supported yet======
========== Sqrt ==========
========== ExpandDims ==========
========== EncodeJpeg ==========
========== ClipByValue ==========
========== Ceil ==========
========== ResizeBicubic ==========
它们对应的tensorflow函数分别是
tf.sqrt
tf.expand_dims
tf.image.encode_jpeg
tf.clip_by_value
tf.ceil
tf.image.resize_images

**Comment by jiangjiajun** [comment]
这个模型目前转换的话，需要改一下你的网络模型, 删除或修改以下几个OP
1. EncodeJpeg（删除)
2. ResizeBicubic(改成ResizeNearest或ResizeBilinear)

**Comment by jiangjiajun** [comment]
此issue由于长期未更新，将被关闭，如有需求可随时再打开。
