### ISSUE TITLE
tf.initializers.variables()以及with tf.variable_scope()应当如何转换到paddle呢

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [PaddlePaddle/X2Paddle#257]
请问，如下部分代码中：
**accumulator = tf.Variable(tf.zeros_like(mask_tf))
   self.accumulators.append(accumulator)
   self.init_accumulators = tf.initializers.variables(self.accumulators)**

其中，tf.Variable可以替换，而 tf.initializers.variables则找不到相应的替换函数。

同理：如下代码中
**with tf.variable_scope("prepare_img"):
……
**
with tf.variable_scope()：应当如何替换呢。

十分感谢。

**Comment by jiangjiajun** [comment]
> 请问，如下部分代码中：
> **accumulator = tf.Variable(tf.zeros_like(mask_tf)) self.accumulators.append(accumulator) self.init_accumulators = tf.initializers.variables(self.accumulators)**
> 
> 其中，tf.Variable可以替换，而 tf.initializers.variables则找不到相应的替换函数。
> 
> 同理：如下代码中
> **with tf.variable_scope("prepare_img"):
> ……
> **
> with tf.variable_scope()：应当如何替换呢。
> 
> 十分感谢。

initialize在paddlepaddle中可以使用exe.run(fluid.default_startup_program())即可初始化所有的参数。

with tf.variable_scope('prepare_img') 在paddlepaddle则有相应的name_scope，参考此文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/name_scope_cn.html#name-scope
