### ISSUE TITLE
tf.contrib.image与tf.where(input, a,b)等相关API接口问题

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [PaddlePaddle/X2Paddle#259]
我在进行API转换的过程中仍有一些问题希望请问大佬：
1   tf.contrib.image的相关子模块，例如**tf.contrib.image.transform(patch_batched, Mb,interpolation="NEAREST",name="perspective")**应当如何转换。
2   tf.image的相关子模块，例如tf.image.total_variation（）以及tf.image.grayscale_to_rgb应当如何转换。
3   tf.math的相关子模块，例如tf.math.maximum（）应当如何转换。
4   我在查阅doc文档时，是否可以使用fluid.layers.where，因为似乎不再具备tf.where(input, a,b)的特性。我想知道fluid.layers.where是否还具有这一应用呢。
5   tf.summary.scalar（）以及tf.add_n（）应当如何转换。

十分感谢！

**Comment by jiangjiajun** [comment]
> 我在进行API转换的过程中仍有一些问题希望请问大佬：
> 1 tf.contrib.image的相关子模块，例如**tf.contrib.image.transform(patch_batched, Mb,interpolation="NEAREST",name="perspective")**应当如何转换。
> 2 tf.image的相关子模块，例如tf.image.total_variation（）以及tf.image.grayscale_to_rgb应当如何转换。
> 3 tf.math的相关子模块，例如tf.math.maximum（）应当如何转换。
> 4 我在查阅doc文档时，是否可以使用fluid.layers.where，因为似乎不再具备tf.where(input, a,b)的特性。我想知道fluid.layers.where是否还具有这一应用呢。
> 5 tf.summary.scalar（）以及tf.add_n（）应当如何转换。
> 
> 十分感谢！

> 1.image相关子模块：PaddlePaddle有resize的相关操作，[相关文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/resize_nearest_cn.html#resize-nearest)  
> 2.paddlepaddle中目前没有image的相关预处理算子，这些建议在python代码的数据预处理中去做  
> 3. [fluid.layers.elementwise_max](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/elementwise_max_cn.html#elementwise-max)  
> 4.这个暂时还没有  
> 5.fluid.summary.scalar暂无，tf.add_n参考[fluid.layers.sum](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sum_cn.html#paddle.fluid.layers.sum)

**Comment by jiangjiajun** [comment]
此issue长时间未更新，将被关闭，如有需求，可随时再重新打开。
