### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by yanhn** [PaddlePaddle/X2Paddle#26]
我是要做caffe2paddle，
使用convert.py转换那一步成功，想把npy参数和py网络转成paddle可读取的模型文件时出错，
我看问题是出在
`data_dict = np.load(data_path).item()`
因为这是生成的net.py里的，所以哪一行可能不确定，错误内容基本上是说np.load的时候设置了allow_pickle=False，这可能是默认参数。修改为
`data_dict = np.load(data_path, allow_pickle=True).item()`之后就可以成功导出模型了。
导出的只有两个文件，一个叫model，一个叫params。

**Comment by yanhn** [comment]
接着往下做，想跑一下`tools/diff.sh`
先是diff.sh的第52行少了`--def_path `，报convert.py的用法错了。
接着往下做，要执行`./infer.py dump XXXX`的时候，提示找不到我的paddle导出模型的路径，这里好像是通过fluid加载转换出的fulid的那个模型，而不是npy的权值，这里的sh我就不会改了。

**Comment by yanhn** [comment]
就直接跑infer.py脚本，用之前导出的model和params所在的路径，
跑的时候报错，应该是解析fluid模型然后找input shape的时候，名字不匹配。
我把infer.py的175行`if var.name == 'data':`改成了`if var.name == name:`，能跑出个结果了。

**Comment by SunAhong1993** [comment]
> 接着往下做，想跑一下`tools/diff.sh`
> 先是diff.sh的第52行少了`--def_path `，报convert.py的用法错了。
> 接着往下做，要执行`./infer.py dump XXXX`的时候，提示找不到我的paddle导出模型的路径，这里好像是通过fluid加载转换出的fulid的那个模型，而不是npy的权值，这里的sh我就不会改了。

1.这里是我们代码的一个bug，我们后期会修复。
2.执行../infer.py dump XXXX是使用.npy权值，同时只fetch网络的输出，不会fetch中间值；值得注意的是，在运行diff.sh的时候会使用到run.sh，run.sh会根据.prototxt的name来获取.py中的类名，所以要保证二者一致。我们后期会修改此部分代码，使易用性增强。

**Comment by SunAhong1993** [comment]
> 就直接跑infer.py脚本，用之前导出的model和params所在的路径，
> 跑的时候报错，应该是解析fluid模型然后找input shape的时候，名字不匹配。
> 我把infer.py的175行`if var.name == 'data':`改成了`if var.name == name:`，能跑出个结果了。

var.name必须等于.prototxt中type为Input的layer的name，所以此处需要用户的手动修改，我们后期也会对这一问题进行修复。

**Comment by yanhn** [comment]
> > 接着往下做，想跑一下`tools/diff.sh`
> > 先是diff.sh的第52行少了`--def_path `，报convert.py的用法错了。
> > 接着往下做，要执行`./infer.py dump XXXX`的时候，提示找不到我的paddle导出模型的路径，这里好像是通过fluid加载转换出的fulid的那个模型，而不是npy的权值，这里的sh我就不会改了。
> 
> 1.这里是我们代码的一个bug，我们后期会修复。
> 2.执行../infer.py dump XXXX是使用.npy权值，同时只fetch网络的输出，不会fetch中间值；值得注意的是，在运行diff.sh的时候会使用到run.sh，run.sh会根据.prototxt的name来获取.py中的类名，所以要保证二者一致。我们后期会修改此部分代码，使易用性增强。

infer.py的时候会调用到`load_inference_model`方法，这个方法根据`dirname`拼接出`model`和`params`的路径然后用`fluid.io.load_inference_model`加载，所以我才怀疑他没有用到weights.npy。
现在我已经跑通了，验证了caffe转paddle的数据基本一致，在小数点后5位左右，满足我的应用了。
