### ISSUE TITLE
使用X2Paddle工具将vgg16转换成paddle模型后inference_model文件读取

### ISSUE THREAD

**Issue by taoja12** [PaddlePaddle/X2Paddle#260]
使用X2Paddle工具将vgg16转换成paddle模型后，生成的两个文件夹inference_model和model_with_code，对于inference_model里面的文件，可以怎么样读取出来吗，得到生成paddle模型后网络每一层的特征值。

**Comment by jiangjiajun** [comment]
使用paddlepaddle加载模型即可，如要获取每一层的特征值，也可以运行model_with_code的代码来做更灵活的debug

**Comment by taoja12** [comment]
> 使用paddlepaddle加载模型即可，如要获取每一层的特征值，也可以运行model_with_code的代码来做更灵活的debug

那我该如何去调用inference_model 里面的内容检测一张图片？
并且提取每一层的输入输出特征值具体应该怎么做？

这是我的网络模型的链接
链接: https://pan.baidu.com/s/1LMsIETIcqlh6pedRFQG74Q 提取码: 9mf8

**Comment by jiangjiajun** [comment]
> > 使用paddlepaddle加载模型即可，如要获取每一层的特征值，也可以运行model_with_code的代码来做更灵活的debug
> 
> 那我该如何去调用inference_model 里面的内容检测一张图片？
> 并且提取每一层的输入输出特征值具体应该怎么做？
> 
> 这是我的网络模型的链接
> 链接: https://pan.baidu.com/s/1LMsIETIcqlh6pedRFQG74Q 提取码: 9mf8

检测图片涉及到图像的预处理，你需要自己将原来模型的图像预处理代码集成进来，然后处理好后再将数据输入给paddle模型。

至于如何获取每一层的输入输出特征值，可以直接修改model_with_code里面的model.py，将每一层的tensor返回即可, 你可以看到x2paddle_net函数中目前只返回了最后一层的结果

**Comment by taoja12** [comment]
> 使用paddlepaddle加载模型即可，如要获取每一层的特征值，也可以运行model_with_code的代码来做更灵活的debug
> 
> 那我该如何去调用inference_model 里面的内容检测一张图片？
> 并且提取每一层的输入输出特征值具体应该怎么做？
> 这是我的网络模型的链接
> 链接: https://pan.baidu.com/s/1LMsIETIcqlh6pedRFQG74Q 提取码: 9mf8
> 
> 检测图片涉及到图像的预处理，你需要自己将原来模型的图像预处理代码集成进来，然后处理好后再将数据输入给paddle模型。
> 至于如何获取每一层的输入输出特征值，可以直接修改model_with_code里面的model.py，将每一层的tensor返回即可, 你可以看到x2paddle_net函数中目前只返回了最后一层的结果

我是将tensorflow vgg16模型通过X2Paddle转换成paddle模型，产生了inference_model和model_with_code两个文件夹，之后使用无校准数据量化对inference_model里的参数进行量化，成功后生成的模型参数体积减小了，想问量化的原理可以从哪里看到？量化后的模型每一层tensor值如何返回？

**Comment by jiangjiajun** [comment]
> > 使用paddlepaddle加载模型即可，如要获取每一层的特征值，也可以运行model_with_code的代码来做更灵活的debug
> > 那我该如何去调用inference_model 里面的内容检测一张图片？
> > 并且提取每一层的输入输出特征值具体应该怎么做？
> > 这是我的网络模型的链接
> > 链接: https://pan.baidu.com/s/1LMsIETIcqlh6pedRFQG74Q 提取码: 9mf8
> > 检测图片涉及到图像的预处理，你需要自己将原来模型的图像预处理代码集成进来，然后处理好后再将数据输入给paddle模型。
> > 至于如何获取每一层的输入输出特征值，可以直接修改model_with_code里面的model.py，将每一层的tensor返回即可, 你可以看到x2paddle_net函数中目前只返回了最后一层的结果
> 
> 我是将tensorflow vgg16模型通过X2Paddle转换成paddle模型，产生了inference_model和model_with_code两个文件夹，之后使用无校准数据量化对inference_model里的参数进行量化，成功后生成的模型参数体积减小了，想问量化的原理可以从哪里看到？量化后的模型每一层tensor值如何返回？

PaddleLite的原理可以参考 https://github.com/PaddlePaddle/Paddle-Lite 中的文档，量化后暂不支持取每一层的特征值

**Comment by jiangjiajun** [comment]
此issue长时间未更新，将被关闭，如有需求，可随时再重新打开。
