### ISSUE TITLE
finetune后的albert转换失败

### ISSUE THREAD

**Issue by daiwk** [PaddlePaddle/X2Paddle#261]
参考https://github.com/PaddlePaddle/X2Paddle/issues/239的方法，

![image](https://user-images.githubusercontent.com/4243530/83036283-fd9c1c00-a06c-11ea-9139-930d9ec7aecf.png)

使用原始albert的checkpoint是正常的（如上图），但使用finetune的checkpoint就会报错
![image](https://user-images.githubusercontent.com/4243530/83036048-c7f73300-a06c-11ea-9dcb-cc27ca3f8158.png)

**Comment by jiangjiajun** [comment]
> https://github.com/PaddlePaddle/X2Paddle/issues/239的方法，

已更新代码，继续参考此Issue中方法即可完成bert模型的转换  https://github.com/PaddlePaddle/X2Paddle/issues/239
