### ISSUE TITLE
AssertionError: directly_map error with multi inputs

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/X2Paddle#262]
When I try to convert a ssd-like net, got this error:
```
  File "/usr/local/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 246, in directly_map
    assert len(val_inps) == 1, 'directly_map error with multi inputs'
AssertionError: directly_map error with multi inputs
```

**Comment by Channingss** [comment]
请问onnx模型的op版本是多少？x2paddle现在支持的op版本是9

**Comment by imistyrain** [comment]
op版本是11导出的.
用版本9导出时提示
```
ONNX export failed: Couldn't export operator aten::upsample_bilinear2d
```

**Comment by Channingss** [comment]
@imistyrain 看能不能想办法用其他的op换掉upsample_bilinear2d，然后导出来为版本9

**Comment by imistyrain** [comment]
上采样在分割中是很常见的操作，多个concat起来按理说应该支持才对

**Comment by Channingss** [comment]
@imistyrain 现在有Upsample和Resize，只是op_set是9。报错信息来看我不明确是哪个OP的版本不一致导致的，如果方便的话，可以把模型发给我们

**Comment by Channingss** [comment]
> When I try to convert a ssd-like net, got this error:
> 
> ```
>   File "/usr/local/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 246, in directly_map
>     assert len(val_inps) == 1, 'directly_map error with multi inputs'
> AssertionError: directly_map error with multi inputs
> ```
we found when ONNX:Clip's op_set>=9，which attribute `min` and `max` support Tensor, https://github.com/onnx/onnx/blob/master/docs/Operators.md#clip，
but onnx2paddle decode attribute as Scalar, we will fix this bug when upgrade onnx2paddle support paddle1.8.

**Comment by jiangjiajun** [comment]
此issue常期未更新，将被关闭，如有需求，可随时再打开。
