### ISSUE TITLE
Exception: Model are not supported yet.

### ISSUE THREAD

**Issue by won-bae** [PaddlePaddle/X2Paddle#275]
Hi,

I got 

There are 2 ops not supported yet, list as below
Greater
ReduceMax

Does it mean onnx model with those two operations cannot be convert to Paddlepaddle model?

Thanks

**Comment by Channingss** [comment]
@won-bae onnx2paddle didn't add that Ops into convert List:
https://github.com/PaddlePaddle/X2Paddle/blob/develop/op_list.md
i will add Greater, ReduceMax,  and reply you as soon as possible

**Comment by Channingss** [comment]
#278

**Comment by Channingss** [comment]
Hi, this pull add Greater, ReduceMax, #301

**Comment by jiangjiajun** [comment]
此issue常期未更新，将被关闭，如有需求，可随时再打开。
