### ISSUE TITLE
模型转换后再次训练的问题

### ISSUE THREAD

**Issue by EwardJohn** [PaddlePaddle/X2Paddle#277]
请问模型从onnx格式转换成paddle格式的模型，能够进行迁移学习吗？能够使用paddledetection上面的文件再次进行训练吗？
onnx格式转换过来后生成inference_model ， model_with_code这两个文件，这里边的模型能够进行再次训练吗？

除此之外，还有一个错误，在使用inference_model时出现错误：
InvalidArgumentError: tensor version 1120706826 is not supported, Only version 0 is supported
请问这个问题如何解决？

**Comment by Channingss** [comment]
@EwardJohn 可以把转换后生成的inference model发给我们验证一下吗？

**Comment by EwardJohn** [comment]
可以的，以什么方式发给你们？ @Channingss

**Comment by Channingss** [comment]
@EwardJohn 我的个人主页上有邮箱

**Comment by EwardJohn** [comment]
好的，模型已经发送到您邮箱了，谢谢!

**Comment by Channingss** [comment]
@EwardJohn 您好，您是想在PaddleDetetion里面再训练转出来的模型吗

**Comment by jiangjiajun** [comment]
此issue常期未更新，将被关闭，如有需求，可随时再打开。

**Comment by EwardJohn** [comment]
你好，我想在这个PaddleDetection中再训练转出来的模型，谢谢！

channings <notifications@github.com> 于2020年7月7日周二 下午5:57写道：
