### ISSUE TITLE
Some ops are not supported yet in tensorflow

### ISSUE THREAD

**Issue by Paradox-GG** [PaddlePaddle/X2Paddle#279]
I try to convert a tf_model.pb,  but the terminal shows these below at last:
Converting node 858 ...    ==========12 Ops are not supported yet======
========== BatchMatMulV2 ==========
========== Unpack ==========
========== Square ==========
========== Fill ==========
========== GatherV2 ==========
========== MatrixDiagPart ==========
========== ResizeArea ==========
========== ExpandDims ==========
========== MatrixSolve ==========
========== Log ==========
========== Minimum ==========
========== Floor ==========

could you please add these ops?I'd appreciate your help on this.

**Comment by jiangjiajun** [comment]
> I try to convert a tf_model.pb, but the terminal shows these below at last:
> Converting node 858 ... ==========12 Ops are not supported yet======
> ========== BatchMatMulV2 ==========
> ========== Unpack ==========
> ========== Square ==========
> ========== Fill ==========
> ========== GatherV2 ==========
> ========== MatrixDiagPart ==========
> ========== ResizeArea ==========
> ========== ExpandDims ==========
> ========== MatrixSolve ==========
> ========== Log ==========
> ========== Minimum ==========
> ========== Floor ==========
> 
> could you please add these ops?I'd appreciate your help on this.

Hi， Could you provide your tensorflow pb model for us to analysis?

**Comment by Paradox-GG** [comment]
> > I try to convert a tf_model.pb, but the terminal shows these below at last:
> > Converting node 858 ... ==========12 Ops are not supported yet======
> > ========== BatchMatMulV2 ==========
> > ========== Unpack ==========
> > ========== Square ==========
> > ========== Fill ==========
> > ========== GatherV2 ==========
> > ========== MatrixDiagPart ==========
> > ========== ResizeArea ==========
> > ========== ExpandDims ==========
> > ========== MatrixSolve ==========
> > ========== Log ==========
> > ========== Minimum ==========
> > ========== Floor ==========
> > could you please add these ops?I'd appreciate your help on this.
> 
> Hi， Could you provide your tensorflow pb model for us to analysis?

Thanks for your reply!
I am sorry that i don’t have the permission to share the pb file, but I make a rudimentary scan on the pb file and codes, found that the ops below may cause the issue: 

from tensorflow.python.ops import array_ops
1,array_ops.zeros([b, num_b_cols, num_b_cols], train_points.dtype)
2, array_ops.ones([b, n, 1], train_points.dtype)
3,array_ops.unstack(query_points, axis=2)
4,array_ops.meshgrid()

from tensorflow.python.ops import linalg_ops
5,linalg_ops.matrix_solve(lhs, rhs)

from tensorflow.python.ops import math_ops
6,array_ops.expand_dims(x_norm_squared, 2) 
7,math_ops.matmul(x, x, adjoint_b=True)
8,math_ops.maximum(r, EPSILON)
9,math_ops.square(r) 
10,math_ops.log()
11,math_ops.minimum()

12,np.expand_dims(np.eye(n), 0)
13,tf.image.resize_images(r,[CROP_SIZE,CROP_SIZE],method=tf.image.ResizeMethod.AREA)
14,tf.expand_dims(transform(inputs), 0)

Any suggestion or help is welcome!

**Comment by jiangjiajun** [comment]
> > > I try to convert a tf_model.pb, but the terminal shows these below at last:
> > > Converting node 858 ... ==========12 Ops are not supported yet======
> > > ========== BatchMatMulV2 ==========
> > > ========== Unpack ==========
> > > ========== Square ==========
> > > ========== Fill ==========
> > > ========== GatherV2 ==========
> > > ========== MatrixDiagPart ==========
> > > ========== ResizeArea ==========
> > > ========== ExpandDims ==========
> > > ========== MatrixSolve ==========
> > > ========== Log ==========
> > > ========== Minimum ==========
> > > ========== Floor ==========
> > > could you please add these ops?I'd appreciate your help on this.
> > 
> > 
> > Hi， Could you provide your tensorflow pb model for us to analysis?
> 
> Thanks for your reply!
> I am sorry that i don’t have the permission to share the pb file, but I make a rudimentary scan on the pb file and codes, found that the ops below may cause the issue:
> 
> from tensorflow.python.ops import array_ops
> 1,array_ops.zeros([b, num_b_cols, num_b_cols], train_points.dtype)
> 2, array_ops.ones([b, n, 1], train_points.dtype)
> 3,array_ops.unstack(query_points, axis=2)
> 4,array_ops.meshgrid()
> 
> from tensorflow.python.ops import linalg_ops
> 5,linalg_ops.matrix_solve(lhs, rhs)
> 
> from tensorflow.python.ops import math_ops
> 6,array_ops.expand_dims(x_norm_squared, 2)
> 7,math_ops.matmul(x, x, adjoint_b=True)
> 8,math_ops.maximum(r, EPSILON)
> 9,math_ops.square(r)
> 10,math_ops.log()
> 11,math_ops.minimum()
> 
> 12,np.expand_dims(np.eye(n), 0)
> 13,tf.image.resize_images(r,[CROP_SIZE,CROP_SIZE],method=tf.image.ResizeMethod.AREA)
> 14,tf.expand_dims(transform(inputs), 0)
> 
> Any suggestion or help is welcome!

Thanks for sharing these details, these will related to a lots of work, we are going to update X2Paddle in next month, more operators would be supported.

**Comment by mjj1094** [comment]
@jiangjiajun 您好，我在转换指代消解模型（ckpt格式转成的pd格式，又转化的paddle）的时候，有22个算子不被支持，如果需要pd文件，能否提供一下邮箱呢？
Converting node 2879 ...    ==========22 Ops are not supported yet======
========== Minimum ==========
========== OneHot ==========
========== Prod ==========
========== BatchMatMulV2 ==========
========== PaddingFIFOQueueV2 ==========
========== Erf ==========
========== GatherV2 ==========
========== All ==========
========== Where ==========
========== ExtractSpans ==========
========== Sqrt ==========
========== ExpandDims ==========
========== Fill ==========
========== Log ==========
========== Floor ==========
========== QueueDequeueV2 ==========
========== LessEqual ==========
========== Assert ==========
========== Less ==========
========== LogicalAnd ==========
========== Equal ==========
========== TopKV2 ==========

**Comment by jiangjiajun** [comment]
> @jiangjiajun 您好，我在转换指代消解模型（ckpt格式转成的pd格式，又转化的paddle）的时候，有22个算子不被支持，如果需要pd文件，能否提供一下邮箱呢？
> Converting node 2879 ... ==========22 Ops are not supported yet======
> ========== Minimum ==========
> ========== OneHot ==========
> ========== Prod ==========
> ========== BatchMatMulV2 ==========
> ========== PaddingFIFOQueueV2 ==========
> ========== Erf ==========
> ========== GatherV2 ==========
> ========== All ==========
> ========== Where ==========
> ========== ExtractSpans ==========
> ========== Sqrt ==========
> ========== ExpandDims ==========
> ========== Fill ==========
> ========== Log ==========
> ========== Floor ==========
> ========== QueueDequeueV2 ==========
> ========== LessEqual ==========
> ========== Assert ==========
> ========== Less ==========
> ========== LogicalAnd ==========
> ========== Equal ==========
> ========== TopKV2 ==========

jiangjiajun@baidu.com
