### ISSUE TITLE
Paddle模型转Onnx模型时显示 no support

### ISSUE THREAD

**Issue by libingbingdev** [PaddlePaddle/X2Paddle#281]
环境：paddlepaddle==1.8.0
           onnx == 1.6.0 
           onnxruntime == 1.0.0
应用场景：paddlehub的shufflenet_v2_imagenet，finetune后，使用命令：
python tools/merge_params.py paddle_model/inference_model  new_model_dir
将best_model目录下的参数文件转化为__model__和__params__两个文件，然后使用命令：
x2paddle --framework=paddle2onnx --model=paddle_infer_model_dir --save_dir=onnx_model
时出现：
paddle.__version__ = 1.8.0
Translating PaddlePaddle to ONNX...

Total:235, Current:235 : fetch
There's 1 ops are not supported yet
=========== swish ===========

目的：将paddle模型转化为onnx模型，然后再将onnx模型转化为Intel IR，以便使用Intel神经计算棒进行边缘计算，请问有其他方式达到模型转化的目的么？

**Comment by Channingss** [comment]
@libingbingdev swish这个激活函数目前我们还没有实现转换的支持，我们评估和测试一下，没问题的话近期加上去

**Comment by Channingss** [comment]
@libingbingdev 您好，这是新增swish op的PR：#300

**Comment by jiangjiajun** [comment]
此issue常期未更新，将被关闭，如有需求，可随时再打开。
