### ISSUE TITLE
PaddleOCR文字检测模型转onnx后输入图像参数问题

### ISSUE THREAD

**Issue by amandazw** [PaddlePaddle/X2Paddle#283]
请问各位有没有遇到这样的问题，原来的paddleOCR的模型支持不定长输入，为32的倍数即可。转为onnx后输入固化了：如下onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: image for the following indices
 index: 2 Got: 960 Expected: 640
 index: 3 Got: 480 Expected: 640
 Please fix either the inputs or the model.
必须要640*640
请教一下如何修改能让模型预测接受可变长度序列呢

**Comment by jiangjiajun** [comment]
> 请问各位有没有遇到这样的问题，原来的paddleOCR的模型支持不定长输入，为32的倍数即可。转为onnx后输入固化了：如下onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: image for the following indices
> index: 2 Got: 960 Expected: 640
> index: 3 Got: 480 Expected: 640
> Please fix either the inputs or the model.
> 必须要640*640
> 请教一下如何修改能让模型预测接受可变长度序列呢

原因在于PaddleOCR在训练模型时，将输入图片大小参数设定为[640, 640]， 因此X2Paddle在解析模型时即会将输入固定为[640, 640]， 详见PaddleOCR的训练配置文件 https://github.com/PaddlePaddle/PaddleOCR/blob/bb1a54ef97100db185cfea0b893b89597c9848f5/configs/det/det_r50_vd_db.yml#L12  如若需要其它大小，可修改配置文件重新训练导出。如若需要支持不定长输入，则需将输入大小设定为[-1, -1]

**Comment by amandazw** [comment]
> > 请问各位有没有遇到这样的问题，原来的paddleOCR的模型支持不定长输入，为32的倍数即可。转为onnx后输入固化了：如下onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: image for the following indices
> > index: 2 Got: 960 Expected: 640
> > index: 3 Got: 480 Expected: 640
> > Please fix either the inputs or the model.
> > 必须要640*640
> > 请教一下如何修改能让模型预测接受可变长度序列呢
> 
> 原因在于PaddleOCR在训练模型时，将输入图片大小参数设定为[640, 640]， 因此X2Paddle在解析模型时即会将输入固定为[640, 640]， 详见PaddleOCR的训练配置文件 https://github.com/PaddlePaddle/PaddleOCR/blob/bb1a54ef97100db185cfea0b893b89597c9848f5/configs/det/det_r50_vd_db.yml#L12 如若需要其它大小，可修改配置文件重新训练导出。如若需要支持不定长输入，则需将输入大小设定为[-1, -1]

了解了，感谢~

**Comment by YuzaChongyi** [comment]
> > > 请问各位有没有遇到这样的问题，原来的paddleOCR的模型支持不定长输入，为32的倍数即可。转为onnx后输入固化了：如下onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: image for the following indices
> > > index: 2 Got: 960 Expected: 640
> > > index: 3 Got: 480 Expected: 640
> > > Please fix either the inputs or the model.
> > > 必须要640*640
> > > 请教一下如何修改能让模型预测接受可变长度序列呢
> > 
> > 
> > 原因在于PaddleOCR在训练模型时，将输入图片大小参数设定为[640, 640]， 因此X2Paddle在解析模型时即会将输入固定为[640, 640]， 详见PaddleOCR的训练配置文件 https://github.com/PaddlePaddle/PaddleOCR/blob/bb1a54ef97100db185cfea0b893b89597c9848f5/configs/det/det_r50_vd_db.yml#L12 如若需要其它大小，可修改配置文件重新训练导出。如若需要支持不定长输入，则需将输入大小设定为[-1, -1]
> 
> 了解了，感谢~

测试ocr文字识别模型转onnx时发现好像还不支持lstm层。

**Comment by amandazw** [comment]
> > > > 请问各位有没有遇到这样的问题，原来的paddleOCR的模型支持不定长输入，为32的倍数即可。转为onnx后输入固化了：如下onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: image for the following indices
> > > > index: 2 Got: 960 Expected: 640
> > > > index: 3 Got: 480 Expected: 640
> > > > Please fix either the inputs or the model.
> > > > 必须要640*640
> > > > 请教一下如何修改能让模型预测接受可变长度序列呢
> > > 
> > > 
> > > 原因在于PaddleOCR在训练模型时，将输入图片大小参数设定为[640, 640]， 因此X2Paddle在解析模型时即会将输入固定为[640, 640]， 详见PaddleOCR的训练配置文件 https://github.com/PaddlePaddle/PaddleOCR/blob/bb1a54ef97100db185cfea0b893b89597c9848f5/configs/det/det_r50_vd_db.yml#L12 如若需要其它大小，可修改配置文件重新训练导出。如若需要支持不定长输入，则需将输入大小设定为[-1, -1]
> > 
> > 
> > 了解了，感谢~
> 
> 测试ocr文字识别模型转onnx时发现好像还不支持lstm层。

是的，文字检测模型可以转成功推理也没有问题。你有尝试过这个paddle模型的onnx转别的模型（h5、pb）或者opencv加载onnx成功吗？
