### ISSUE TITLE
警告paddle not support op:resize wiht mode: linear, we use bilinear replace linear，请问怎么解决

### ISSUE THREAD

**Issue by x423xu** [PaddlePaddle/X2Paddle#284]
paddle not support op:resize wiht mode: linear, we use bilinear replace linear

**Comment by Channingss** [comment]
这个是因为paddle的resize目前没有linear插值方式。

**Comment by jiangjiajun** [comment]
此issue常期未更新，将被关闭，如有需求，可随时再打开。
