### ISSUE TITLE
ops are not supported

### ISSUE THREAD

**Issue by bywang** [PaddlePaddle/X2Paddle#286]
paddle.__version__ = 1.8.1
Translating PaddlePaddle to ONNX...

Total:167, Current:167 : fetch                              
There's 2 ops are not supported yet
=========== prior_box ===========
=========== box_coder ===========

prior_box和box_coder这两个op有支持的计划吗？

**Comment by jiangjiajun** [comment]
> paddle.**version** = 1.8.1
> Translating PaddlePaddle to ONNX...
> 
> Total:167, Current:167 : fetch
> There's 2 ops are not supported yet
> =========== prior_box ===========
> =========== box_coder ===========
> 
> prior_box和box_coder这两个op有支持的计划吗？

目前正在开发中，预计会在7月份完成

**Comment by Channingss** [comment]
@bywang Pr: #331 增加了prior_box和box_coder

**Comment by jiangjiajun** [comment]
此issue长期未更新，将被关闭，如有需求，可随时再打开。
