### ISSUE TITLE
PaddlePaddle to ONNX  yolov3转换失败

### ISSUE THREAD

**Issue by Septend-fun** [PaddlePaddle/X2Paddle#293]
x2paddle --framework=paddle2onnx --model=export --save_dir=onnx_model
paddle.__version__ = 1.8.1
Translating PaddlePaddle to ONNX...

Total:262, Current:260 : multiclass_nms                 lib/python3.6/site-packages/x2paddle/op_mapper/paddle_custom_layer/multiclass_nms.py:47: UserWarning: The parameter normalized of multiclass_nms OP of Paddle is False, which has diff with ONNX.                          Please set normalized=True in multiclass_nms of Paddle
  Please set normalized=True in multiclass_nms of Paddle'
Total:262, Current:262 : fetch                   Traceback (most recent call last):
  File "/home/bin/x2paddle", line 11, in <module>
    sys.exit(main())
  File "/home/lib/python3.6/site-packages/x2paddle/convert.py", line 272, in main
    paddle2onnx(args.model, args.save_dir)
  File "/home/lib/python3.6/site-packages/x2paddle/convert.py", line 194, in paddle2onnx
    mapper.convert(model.program, save_dir)
  File "/home/lib/python3.6/site-packages/x2paddle/op_mapper/paddle_op_mapper.py", line 815, in convert
    onnx.checker.check_model(model)
  File "/home/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: max for operator Clip

==> Context: Bad node spec: input: "yolo_box0.tmp_0@pred_box_x1_decode" output: "yolo_box0.tmp_0@pred_box_x1_clip" op_type: "Clip" attribute { name: "max" f: inf type: FLOAT } attribute { name: "min" f: 0 type: FLOAT }

**Comment by jiangjiajun** [comment]
> x2paddle --framework=paddle2onnx --model=export --save_dir=onnx_model
> paddle.**version** = 1.8.1
> Translating PaddlePaddle to ONNX...
> 
> Total:262, Current:260 : multiclass_nms lib/python3.6/site-packages/x2paddle/op_mapper/paddle_custom_layer/multiclass_nms.py:47: UserWarning: The parameter normalized of multiclass_nms OP of Paddle is False, which has diff with ONNX. Please set normalized=True in multiclass_nms of Paddle
> Please set normalized=True in multiclass_nms of Paddle'
> Total:262, Current:262 : fetch Traceback (most recent call last):
> File "/home/bin/x2paddle", line 11, in
> sys.exit(main())
> File "/home/lib/python3.6/site-packages/x2paddle/convert.py", line 272, in main
> paddle2onnx(args.model, args.save_dir)
> File "/home/lib/python3.6/site-packages/x2paddle/convert.py", line 194, in paddle2onnx
> mapper.convert(model.program, save_dir)
> File "/home/lib/python3.6/site-packages/x2paddle/op_mapper/paddle_op_mapper.py", line 815, in convert
> onnx.checker.check_model(model)
> File "/home/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
> C.check_model(model.SerializeToString())
> onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: max for operator Clip
> 
> ==> Context: Bad node spec: input: "yolo_box0.tmp_0@pred_box_x1_decode" output: "yolo_box0.tmp_0@pred_box_x1_clip" op_type: "Clip" attribute { name: "max" f: inf type: FLOAT } attribute { name: "min" f: 0 type: FLOAT }

YOLOv3目前支持仍存在问题，涉及的相关OP还在开发中，预计在本月内完成

**Comment by Septend-fun** [comment]
> > x2paddle --framework=paddle2onnx --model=export --save_dir=onnx_model
> > paddle.**version** = 1.8.1
> > Translating PaddlePaddle to ONNX...
> > Total:262, Current:260 : multiclass_nms lib/python3.6/site-packages/x2paddle/op_mapper/paddle_custom_layer/multiclass_nms.py:47: UserWarning: The parameter normalized of multiclass_nms OP of Paddle is False, which has diff with ONNX. Please set normalized=True in multiclass_nms of Paddle
> > Please set normalized=True in multiclass_nms of Paddle'
> > Total:262, Current:262 : fetch Traceback (most recent call last):
> > File "/home/bin/x2paddle", line 11, in
> > sys.exit(main())
> > File "/home/lib/python3.6/site-packages/x2paddle/convert.py", line 272, in main
> > paddle2onnx(args.model, args.save_dir)
> > File "/home/lib/python3.6/site-packages/x2paddle/convert.py", line 194, in paddle2onnx
> > mapper.convert(model.program, save_dir)
> > File "/home/lib/python3.6/site-packages/x2paddle/op_mapper/paddle_op_mapper.py", line 815, in convert
> > onnx.checker.check_model(model)
> > File "/home/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
> > C.check_model(model.SerializeToString())
> > onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: max for operator Clip
> > ==> Context: Bad node spec: input: "yolo_box0.tmp_0@pred_box_x1_decode" output: "yolo_box0.tmp_0@pred_box_x1_clip" op_type: "Clip" attribute { name: "max" f: inf type: FLOAT } attribute { name: "min" f: 0 type: FLOAT }
> 
> YOLOv3目前支持仍存在问题，涉及的相关OP还在开发中，预计在本月内完成

好的，多谢！
