### ISSUE TITLE
paddle转onnx efficientnet结果有误差

### ISSUE THREAD

**Issue by ArtyZe** [PaddlePaddle/X2Paddle#297]
efficientnet转换过程中，可能是因为conv的output_w不能整除的原因，所以后面跟了一个slice将第一列数据去掉。但是在转onnx时，转换没有报错，转换之后测试时候误差较大。如下：
![image](https://user-images.githubusercontent.com/32027268/86437339-f4226580-bd36-11ea-87b6-795ee4a78438.png)
之前已经测试过其他的模型，都是可以对得上的，除了efficientnet系列。
```
测试模型： 下载的paddlecv的预训练模型并通过save_inference_model保存得到
```

请问是否有啥建议呀？

**Comment by Channingss** [comment]
@ArtyZe 我们这边尝试复现一下，请问paddle的版本是？

**Comment by ArtyZe** [comment]
> @ArtyZe 我们这边尝试复现一下，请问paddle的版本是？
```
paddlepaddle:        1.7.2
onnx                 1.6.0
onnxruntime          1.3.0
```
同时因为onnx不支持swish，我使用mul及sigmoid替代了，如下图
![image](https://user-images.githubusercontent.com/32027268/86457427-3b6c1e80-bd56-11ea-91fe-1121698bc1b4.png)
同时，我觉得padding后不能整除可能是造成现在这样的原因
![image](https://user-images.githubusercontent.com/32027268/86457519-60609180-bd56-11ea-91b4-224d7c3ee372.png)

**Comment by Channingss** [comment]
@ArtyZe 请问使用的是哪一个模型呢，我这边刚刚测试了EfficientNetB0，有部分op转换还没实现。
![image](https://user-images.githubusercontent.com/12471701/86744624-53041980-c06c-11ea-8b21-11be2afc88f1.png)

**Comment by ArtyZe** [comment]
> @ArtyZe 请问使用的是哪一个模型呢，我这边刚刚测试了EfficientNetB0，有部分op转换还没实现。
> ![image](https://user-images.githubusercontent.com/12471701/86744624-53041980-c06c-11ea-8b21-11be2afc88f1.png)

B0到B7我都可以的，你那边是哪个算子不支持？swish可以用simoid和mul替换，其他的应该都支持吧

swish算子如下：
```
def make_name(name):
    """Make op name for inserted ops."""
    global INTERNAL_NAME
    INTERNAL_NAME += 1
    return "{}__{}".format(name, INTERNAL_NAME)

def swish_op(operator, block):
    """
    The activation swish,  y = x / (1 + exp(-beta * x))
    """
    inputs, attrs, outputs = op_io_info(operator)
    paddle_var = block.var(inputs["X"][0])
    shape = paddle_onnx_shape(paddle_var.shape)

    if 'beta' in attrs:
        beta = attrs['beta']
    if 'slope' in attrs:
        beta = attrs['slope']

    name_beta = [outputs['Out'][0] + "@swish_beta"]
    node_beta = onnx.helper.make_node(
        'Constant',
        name = make_name("Constant"),
        inputs=[],
        outputs=name_beta,
        value=onnx.helper.make_tensor(
            name=name_beta[0] + "@const",
            data_type=onnx.TensorProto.FLOAT,
            dims=(),
            vals=[beta]))

    # var and node for beta * x 
    name_beta_x = [outputs['Out'][0] + "@beta_x"]
    var_beta_x = onnx.helper.make_tensor_value_info(
        name_beta_x[0], PADDLE_TO_ONNX_DTYPE[paddle_var.dtype], shape)
    node_beta_x = onnx.helper.make_node(
        'Mul', name = make_name("Constant"), inputs=[name_beta[0], inputs['X'][0]], outputs=name_beta_x)

    # var and node sigmoid(beta*x)
    name_sigmoid_x = [outputs['Out'][0] + "@sigmoid_x"]
    var_sigmoid_x = onnx.helper.make_tensor_value_info(
        name_sigmoid_x[0], PADDLE_TO_ONNX_DTYPE[paddle_var.dtype], shape)
    node_sigmoid_x = onnx.helper.make_node(
        'Sigmoid', name = make_name("Constant"), inputs=name_beta_x, outputs=name_sigmoid_x)

    node_swish = onnx.helper.make_node(
        'Mul', name = make_name("Constant"), inputs=inputs['X'] + name_sigmoid_x, outputs=outputs['Out'])
    return (node_beta, node_beta_x, node_sigmoid_x, node_swish)
```

**Comment by Channingss** [comment]
@ArtyZe 你那边是自己写了这三个算子的转换吗？
There's 3 ops are not supported yet
=========== swish ===========
=========== uniform_random ===========
=========== floor ===========

**Comment by ArtyZe** [comment]
> @ArtyZe 你那边是自己写了这三个算子的转换吗？
> There's 3 ops are not supported yet
> =========== swish ===========
> =========== uniform_random ===========
> =========== floor ===========


咦，我使用save_model_infer保存的__model__文件没有你后面这两个算子，只有不支持的swish，那难道我精度下降就是我在save时候丢了这俩算子吗？
我只是自己实现了swish，因为本身也比较简单，就加上去了

**Comment by Channingss** [comment]
丢了算子不太可能，应该是我这边使用的X2paddle现在整合进来的paddle2onnx。https://github.com/PaddlePaddle/X2Paddle/#paddle2onnx

**Comment by ArtyZe** [comment]
> 丢了算子不太可能，应该是我这边使用的X2paddle现在整合进来的paddle2onnx。https://github.com/PaddlePaddle/X2Paddle/#paddle2onnx

我使用x2paddle测试了下efficientnetb0
```
x2paddle                           0.7.4
paddle                             1.0.2        
paddle2onnx                        0.2          
paddlehub                          1.0.0        
paddlelite                         2.6.1        
paddlepaddle                       1.8.2 
onnx                               1.6.0 
```
结果如下：
![image](https://user-images.githubusercontent.com/32027268/86750869-d9baf580-c070-11ea-954f-ba7f7b2e0808.png)
为了您那边debug方便，我将model和param上传到百度网盘，您看一下
https://pan.baidu.com/s/14LPwtuWyXCt9v6S9PfmQ2Q
passwd：q9ok

**Comment by Channingss** [comment]
我在X2Paddle新增了Swish op，这里是PR:  #300, 我这边测试随机数据，onnx和paddle误差在10的-7次方

**Comment by ArtyZe** [comment]
@Channingss hello，问题找到了，不是swish也不是pad的问题，是这里
![image](https://user-images.githubusercontent.com/32027268/86769041-11ca3480-c081-11ea-96de-2545504eaea2.png)
这里在dropout后面加了一个mul
![image](https://user-images.githubusercontent.com/32027268/86769081-28708b80-c081-11ea-91b2-1134ece79d50.png)
 node，
改正之后就全部正确了
![image](https://user-images.githubusercontent.com/32027268/86769118-39210180-c081-11ea-9e63-d84d89acaeaf.png)
多谢多谢！
那我就直接close了
