### ISSUE TITLE
paddle模型转onnx

### ISSUE THREAD

**Issue by Amore-HDU** [PaddlePaddle/X2Paddle#302]
paddle模型转onnx模型的时候全连接层被转成MatMul Reshape 等层，请问可以直接转成FC层吗

**Comment by Channingss** [comment]
@Amore-HDU 请问是有什么特别的需求吗

**Comment by jiangjiajun** [comment]
> paddle模型转onnx模型的时候全连接层被转成MatMul Reshape 等层，请问可以直接转成FC层吗

ONNX的Operators中目前没有FC层，可参考ONNX的OP集合，https://github.com/onnx/onnx/blob/master/docs/Operators.md

**Comment by Amore-HDU** [comment]
> @Amore-HDU 请问是有什么特别的需求吗

paddle分类模型转caffe完全不掉精度，但是caffe转到海思3559A的wk模型，精度掉的一塌糊涂  @Channingss

**Comment by Channingss** [comment]
@Amore-HDU 关于Caffe模型转到海思上精度问题，应该是由于海思提供的转换工具问题，建议联系一下海思的开发工程人员，定位一下转换的问题原因。

**Comment by Amore-HDU** [comment]
> @Amore-HDU 关于Caffe模型转到海思上精度问题，应该是由于海思提供的转换工具问题，建议联系一下海思的开发工程人员，定位一下转换的问题原因。

我用caffe训练的模型转到海思平台，不掉精度，pytorch训练的模型也不掉精度；唯独用飞桨训出来的模型转到3559A上掉精度掉的厉害

**Comment by Channingss** [comment]
@Amore-HDU 如果paddle分类模型转caffe完全不掉精度，说明X2Paddle这边导出的模型是没有问题的。应该是ONNX转成cafe后的模型里边有Operator海思那边支持不完善，建议找海思的开发人员定位下问题先。

**Comment by jiangjiajun** [comment]
此issue长期未更新，将被关闭，如有需求，可随时再打开。
