### ISSUE TITLE
paddle模型转onnx模型报错

### ISSUE THREAD

**Issue by DYJNG** [PaddlePaddle/X2Paddle#303]
您好，我在将paddle yolov3模型转onnx模型时报错如下：
$x2paddle --framework=paddle2onnx --model=paddle_model/yolov3_tf2paddle/ --save_dir=paddle_onnx_model
paddle.__version__ = 1.8.2
Translating PaddlePaddle to ONNX...

Total:333, Current:333 : fetch
There's 2 ops are not supported yet
=========== elementwise_max ===========
=========== pad2d ===========

在转换paddleslim quant_post量化后的模型时报错如下：
$x2paddle --framework=paddle2onnx --model=paddle_model/yolov3_quant_post_model/ --save_dir=paddle_quant_onnx_model
paddle.__version__ = 1.8.2
Translating PaddlePaddle to ONNX...

Total:481, Current:481 : fetch                             bs
There's 4 ops are not supported yet
=========== fake_quantize_range_abs_max ===========
=========== pad2d ===========
=========== fake_channel_wise_dequantize_max_abs ===========
=========== elementwise_max ===========

我的最终目的是为了将量化后的paddle yolov3模型转化为独立的trt模型，请问有什么好的解决方法吗？

**Comment by Channingss** [comment]
Paddle2onnx 目前还不完全支持Yolov3的转换，我们还在开发中，
另外Paddle预测库支持直接TRT部署运行：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html#gpu

**Comment by DYJNG** [comment]
@Channingss 感谢回复！
