### ISSUE TITLE
onnx模型opencv4.3.0加载报错

### ISSUE THREAD

**Issue by amandazw** [PaddlePaddle/X2Paddle#305]
paddleOCR模型转onnx后用opencv4.3.0加载报错，
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:149: error: (-215:Assertion failed) dstTotal != 0 in function 'cv::dnn::computeShapeByReshapeMask'

请问模型要怎么修改呢？

**Comment by jiangjiajun** [comment]
> paddleOCR模型转onnx后用opencv4.3.0加载报错，
> cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:149: error: (-215:Assertion failed) dstTotal != 0 in function 'cv::dnn::computeShapeByReshapeMask'
> 
> 请问模型要怎么修改呢？

目前转换采用的是ONNX的最新OP标准11， 建议使用onnxruntime进行加载预测

**Comment by amandazw** [comment]
> > paddleOCR模型转onnx后用opencv4.3.0加载报错，
> > cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:149: error: (-215:Assertion failed) dstTotal != 0 in function 'cv::dnn::computeShapeByReshapeMask'
> > 请问模型要怎么修改呢？
> 
> 目前转换采用的是ONNX的最新OP标准11， 建议使用onnxruntime进行加载预测

好的~

**Comment by amandazw** [comment]
C++配置onnxruntime加载成功，但是不知道怎么处理输出值，有人可以指点一下吗？

**Comment by amandazw** [comment]
onnxruntime加载成功
