### ISSUE TITLE
支持训练模型的转换吗

### ISSUE THREAD

**Issue by CYang0515** [PaddlePaddle/X2Paddle#307]
比如将ONNX模型转为paddle模型，可以在paddle slim里面进行量化训练吗？

**Comment by jiangjiajun** [comment]
> 比如将ONNX模型转为paddle模型，可以在paddle slim里面进行量化训练吗？

ONNX模型仅支持前向推理，不包含训练部分网络，如果作为训练，需要继续自行组网。PaddleSlim支持离线量化，前向推理的模型直接用PaddleSlim进行离线量化即可
