### ISSUE TITLE
ConstantFill op的转换失败

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/X2Paddle#31]
使用X2Paddle/onnx2fluid转一个gru的时候，报错onnx2fluid/writer.py", line 247, in Op
ValueError: conversion for ::ConstantFill not supported。希望能够支持对ConstantFill op的转换。

**Comment by jiangjiajun** [comment]
该问题，在类似的issue下已作回复，https://github.com/PaddlePaddle/X2Paddle/issues/30

目前X2Paddle主要支持的是CV模型，NLP模型暂未支持。

**Comment by MacroBull** [comment]
> 使用X2Paddle/onnx2fluid转一个gru的时候，报错onnx2fluid/writer.py", line 247, in Op
> ValueError: conversion for ::ConstantFill not supported。希望能够支持对ConstantFill op的转换。

你好，可以告诉我转换所使用的参数和模型算子集版本吗？
X2Paddle目前支持ONNX算子集第9版，ConstantFill不是该稳定版本下的算子，如果没有显式版本转换，程序应当会抛出一个错误。
另外，PyTorch目前对RNN类模型的导出不完备，如果不是手工搭建的干净的ONNX模型是无法进行有效的转换的，可以参考[PyTorch symbolic.py](https://github.com/pytorch/pytorch/blob/45c6fa0007cc3eda6fa187c1c2a587eba5b0008d/torch/onnx/symbolic_opset9.py#L1282)。

**Comment by MacroBull** [comment]
> 使用X2Paddle/onnx2fluid转一个gru的时候，报错onnx2fluid/writer.py", line 247, in Op
> ValueError: conversion for ::ConstantFill not supported。希望能够支持对ConstantFill op的转换。

@wzzju 

推荐的可转换的模型构建方式：

https://github.com/MacroBull/X2Paddle/blob/986457338460dfb5d917eb67298734cf00a3d98d/onnx2fluid/examples/gen_some_samples.py#L25


不推荐的方式：

https://github.com/MacroBull/X2Paddle/blob/986457338460dfb5d917eb67298734cf00a3d98d/onnx2fluid/examples/gen_some_samples.py#L54
