### ISSUE TITLE
AttributeError: 'str' object has no attribute 'outputs' and dont support deconv

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [PaddlePaddle/X2Paddle#310]
python：3.5
tensorflow: 1.14.0
paddlepaddle: 1.18.5
x2paddle: 0.7.4

请问一下 我正常存了个只有四层卷积的tensorflow pb 转化的过程中报错
AttributeError: 'str' object has no attribute  [#'outputs']
 下面是我的测试pb 只有四层卷积 
 [test.pb](https://drive.google.com/file/d/1dwJE14SiwdqkArie-C-ETkgq7e83mJM3/view?usp=sharing)

转化pb代码与x2paddle官方示例完全一样

**Comment by mamingjie-China** [comment]
> python：3.5
> tensorflow: 1.14.0
> paddlepaddle: 1.18.5
> x2paddle: 0.7.4
> 
> 请问一下 我正常存了个只有四层卷积的tensorflow pb 转化的过程中报错
> AttributeError: 'str' object has no attribute [#'outputs']
> 下面是我的测试pb 只有四层卷积
> [test.pb](https://drive.google.com/file/d/1dwJE14SiwdqkArie-C-ETkgq7e83mJM3/view?usp=sharing)
> 
> 转化pb代码与x2paddle官方示例完全一样

您好，非常感谢您的使用！我们目前正在进行版本迭代工作，目前，您可以使用x2paddle --framework=tensorflow --model=test.pb --save_dir=pd_model --without_data_format_optimization进行转换，迭代后，计划将--without_data_format_optimization设置为默认形式，欢迎您继续关注

**Comment by jiuzhuanzhuan** [comment]
> > python：3.5
> > tensorflow: 1.14.0
> > paddlepaddle: 1.18.5
> > x2paddle: 0.7.4
> > 请问一下 我正常存了个只有四层卷积的tensorflow pb 转化的过程中报错
> > AttributeError: 'str' object has no attribute [#'outputs']
> > 下面是我的测试pb 只有四层卷积
> > [test.pb](https://drive.google.com/file/d/1dwJE14SiwdqkArie-C-ETkgq7e83mJM3/view?usp=sharing)
> > 转化pb代码与x2paddle官方示例完全一样
> 
> 您好，非常感谢您的使用！我们目前正在进行版本迭代工作，目前，您可以使用x2paddle --framework=tensorflow --model=test.pb --save_dir=pd_model --without_data_format_optimization进行转换，迭代后，计划将--without_data_format_optimization设置为默认形式，欢迎您继续关注

非常感谢 解决了

**Comment by jiuzhuanzhuan** [comment]
同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
[deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
Converting node 24 ...     ========= 1 OPs are not supported yet ===========
========== Conv2DBackpropInput ============

**Comment by mamingjie-China** [comment]
> 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> Converting node 24 ... ========= 1 OPs are not supported yet ===========
> ========== Conv2DBackpropInput ============

提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因

**Comment by jiuzhuanzhuan** [comment]
> > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > ========== Conv2DBackpropInput ============
> 
> 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
您看一下 这个
[newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)

**Comment by jiuzhuanzhuan** [comment]
> > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > ========== Conv2DBackpropInput ============
> > 
> > 
> > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > 您看一下 这个
> > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by mamingjie-China** [comment]
> > > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > > ========== Conv2DBackpropInput ============
> > > 
> > > 
> > > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > > 您看一下 这个
> > > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
> > > 链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦

代码已经合入，欢迎使用，有什么问题可以后续沟通。

**Comment by jiuzhuanzhuan** [comment]
> > > > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > > > ========== Conv2DBackpropInput ============
> > > > 
> > > > 
> > > > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > > > 您看一下 这个
> > > > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
> > > > 链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 代码已经合入，欢迎使用，有什么问题可以后续沟通。

请问我重新下载了最新的X2paddle源码安装了 为何还是显示不支持Conv2DBackpropInput

**Comment by mamingjie-China** [comment]
> > > > > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > > > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > > > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > > > > ========== Conv2DBackpropInput ============
> > > > > 
> > > > > 
> > > > > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > > > > 您看一下 这个
> > > > > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
> > > > > 链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦
> > 
> > 
> > 代码已经合入，欢迎使用，有什么问题可以后续沟通。
> 
> 请问我重新下载了最新的X2paddle源码安装了 为何还是显示不支持Conv2DBackpropInput

是通过git clone下载的代码，还是直接pip安装的啊，pip的话可能暂时还没有同步，建议通过develop分支的代码安装

**Comment by jiuzhuanzhuan** [comment]
> > > > > > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > > > > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > > > > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > > > > > ========== Conv2DBackpropInput ============
> > > > > > 
> > > > > > 
> > > > > > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > > > > > 您看一下 这个
> > > > > > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
> > > > > > 链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦
> > > 
> > > 
> > > 代码已经合入，欢迎使用，有什么问题可以后续沟通。
> > 
> > 
> > 请问我重新下载了最新的X2paddle源码安装了 为何还是显示不支持Conv2DBackpropInput
> 
> 是通过git clone下载的代码，还是直接pip安装的啊，pip的话可能暂时还没有同步，建议通过develop分支的代码安装

是git clone 下的最新的 。然后也是在develop分支下 重新装了一下。 paddlepaddle是pip装的

**Comment by mamingjie-China** [comment]
> > > > > > > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > > > > > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > > > > > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > > > > > > ========== Conv2DBackpropInput ============
> > > > > > > 
> > > > > > > 
> > > > > > > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > > > > > > 您看一下 这个
> > > > > > > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
> > > > > > > 链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦
> > > > 
> > > > 
> > > > 代码已经合入，欢迎使用，有什么问题可以后续沟通。
> > > 
> > > 
> > > 请问我重新下载了最新的X2paddle源码安装了 为何还是显示不支持Conv2DBackpropInput
> > 
> > 
> > 是通过git clone下载的代码，还是直接pip安装的啊，pip的话可能暂时还没有同步，建议通过develop分支的代码安装
> 
> 是git clone 下的最新的 。然后也是在develop分支下 重新装了一下。 paddlepaddle是pip装的

我这边重新试了一下，develop分支是可以进行转换的，可以再检查一下安装的环境，或者重新卸载安装，跟Paddle应该没关系的，详细的情况，可添加QQ363377396进行沟通。

**Comment by jiuzhuanzhuan** [comment]
> > > > > > > > > 同样的环境搭了一层反卷积 为什么会显示不支持Conv2DBackpropInput 。 官方支持op是有这个算子的。找不出来什么原因。
> > > > > > > > > [deconv.pb](https://drive.google.com/file/d/1nwc4yI7-YSR9H4roOYj2M_03N1WeNHa1/view?usp=sharing)
> > > > > > > > > Converting node 24 ... ========= 1 OPs are not supported yet ===========
> > > > > > > > > ========== Conv2DBackpropInput ============
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 提供的模型我这边暂时没法下载，提示没有权限，待您那边申请通过后，我们这边复现一下看是什么原因
> > > > > > > > 您看一下 这个
> > > > > > > > [newpb](https://drive.google.com/file/d/1NAytWkIDNsOZHrIa3okM08Lz1DlS2Q_z/view?usp=sharing)
> > > > > > > > 链接: [baiduwangpan](https://pan.baidu.com/s/1tkWx42q36OaTLUcewtL7pA) 提取码: gftc 复制这段内容后打开百度网盘手机App，操作更方便哦
> > > > > 
> > > > > 
> > > > > 代码已经合入，欢迎使用，有什么问题可以后续沟通。
> > > > 
> > > > 
> > > > 请问我重新下载了最新的X2paddle源码安装了 为何还是显示不支持Conv2DBackpropInput
> > > 
> > > 
> > > 是通过git clone下载的代码，还是直接pip安装的啊，pip的话可能暂时还没有同步，建议通过develop分支的代码安装
> > 
> > 
> > 是git clone 下的最新的 。然后也是在develop分支下 重新装了一下。 paddlepaddle是pip装的
> 
> 我这边重新试了一下，develop分支是可以进行转换的，可以再检查一下安装的环境，或者重新卸载安装，跟Paddle应该没关系的，详细的情况，可添加QQ363377396进行沟通。

感谢大佬。 确实可以了。
