### ISSUE TITLE
Caffe 模型转换

### ISSUE THREAD

**Issue by MichaelZhero** [PaddlePaddle/X2Paddle#314]
Looking in indexes: https://pypi.Python.org/simple/
Collecting x2paddle
  Downloading https://files.pythonhosted.org/packages/8a/44/d76e2ac34efcc849389c70b2136e871ec2f78da04dbf8eb12e9620cfb6e3/x2paddle-0.7.4-py3-none-any.whl (132kB)
     |████████████████████████████████| 133kB 36kB/s eta 0:00:01
Installing collected packages: x2paddle
Successfully installed x2paddle-0.7.4

x2paddle --framework=caffe --prototxt=work/landmark_deploy.prototxt --weight=work/VanFace.caffemodel  --save_dir=work/pd_model
 File "<ipython-input-12-06349dba0f8a>", line 1
    x2paddle --framework=caffe --prototxt=work/landmark_deploy.prototxt --weight=work/VanFace.caffemodel  --save_dir=work/pd_model
                                                                                                                                  ^
SyntaxError: can't assign to operator

**Comment by SunAhong1993** [comment]
你好~你可以先确认下文件中是否存在不符合命名规则的名字。同时请问下是在什么系统上运行的？

**Comment by MichaelZhero** [comment]
你好，是在aistudio上面直接运行。然后命令是直接从x2paddle的readme.md的使用方法下面caffe这一条命令直接拷贝过来的，改了下模型文件路径

**Comment by SunAhong1993** [comment]
> 你好，是在aistudio上面直接运行。然后命令是直接从x2paddle的readme.md的使用方法下面caffe这一条命令直接拷贝过来的，改了下模型文件路径

aisudio上运行该命令行需在改行最前面加一个！，确认是否添加

**Comment by MichaelZhero** [comment]
!mkdir /home/aistudio/external-libraries
!mkdir /home/aistudio/pd_model
!pip install x2paddle --index https://pypi.Python.org/simple/ -t /home/aistudio/external-libraries
![image](https://user-images.githubusercontent.com/16940225/87921356-05949d00-caad-11ea-8e96-e6d2a4d2b369.png)
1、!x2paddle --framework=caffe --prototxt=work/landmark_deploy.prototxt --weight=work/VanFace.caffemodel  --saved_ir=pd_model
/bin/sh: 1: x2paddle: not found
2、!external-libraries/x2paddle --framework=caffe --prototxt=work/landmark_deploy.prototxt --weight=work/VanFace.caffemodel  --saved_ir=aa
/bin/sh: 1: external-libraries/x2paddle: Permission denied

**Comment by SunAhong1993** [comment]
![image](https://user-images.githubusercontent.com/48579383/87922658-ded76600-caae-11ea-878a-64c1ceb48ad6.png)
使用正常方式安装（不需要-t），即可使用

**Comment by MichaelZhero** [comment]
成功了。谢谢你。
