### ISSUE TITLE
tf_to_paddle

### ISSUE THREAD

**Issue by Zhaoyilunnn** [PaddlePaddle/X2Paddle#316]
![image](https://user-images.githubusercontent.com/40353317/88037220-317c5500-cb77-11ea-8177-e3fb3f98bc80.png)
请问一下tf1.8的这两个Ops近期有支持的计划吗

**Comment by mamingjie-China** [comment]
> ![image](https://user-images.githubusercontent.com/40353317/88037220-317c5500-cb77-11ea-8177-e3fb3f98bc80.png)
> 请问一下tf1.8的这两个Ops近期有支持的计划吗

请在转换时使用--without_data_format_optimization参数，即x2paddle --framework=tensorflow --model=tf_model.pb --save_dir=pd_model --without_data_format_optimization

**Comment by Zhaoyilunnn** [comment]
> > ![image](https://user-images.githubusercontent.com/40353317/88037220-317c5500-cb77-11ea-8177-e3fb3f98bc80.png)
> > 请问一下tf1.8的这两个Ops近期有支持的计划吗
> 
> 请在转换时使用--without_data_format_optimization参数，即x2paddle --framework=tensorflow --model=tf_model.pb --save_dir=pd_model --without_data_format_optimization

感谢及时回复

**Comment by jiangjiajun** [comment]
由于此issue长时间未更新，将被关闭，如有需求，可随时再打开。
