### ISSUE TITLE
paddle to onnx：There's 3 ops are not supported yet

### ISSUE THREAD

**Issue by Lbo18** [PaddlePaddle/X2Paddle#319]
There's 3 ops are not supported yet
=========== clip ===========
=========== tanh ===========
=========== log ===========
麻烦问一下，这些ops有支持的计划嘛

**Comment by Channingss** [comment]
@Lbo18 这边评估一下后，尽快给您回复

**Comment by Lbo18** [comment]
> @Lbo18 这边评估一下后，尽快给您回复

这个是yolov4权重转onnx出现的问题，感谢~

**Comment by Channingss** [comment]
@Lbo18  把模型发给我们方便吗？我们这边还没有尝试转换过yolov4

**Comment by Lbo18** [comment]
> @Lbo18 把模型发给我们方便吗？我们这边还没有尝试转换过yolov4

只需要__model__和__params__是嘛，邮箱可以发一下嘛

**Comment by Channingss** [comment]
@Lbo18 chen_lingchi@163.com

**Comment by Lbo18** [comment]
> @Lbo18 [chen_lingchi@163.com](mailto:chen_lingchi@163.com)

请问这个有进一步解决嘛

**Comment by Channingss** [comment]
@Lbo18 尽可能在这周完成

**Comment by Channingss** [comment]
@Lbo18 新增三个op的pr: #330 ，这边测试可以转换成功，并使用onnxruntime跑通转换后的onnx模型。

**Comment by Lbo18** [comment]
> @Lbo18 新增三个op的pr: #330 ，这边测试可以转换成功，并使用onnxruntime跑通转换后的onnx模型。

感谢，已更新相关代码，但运行后还是出现
Total:738, Current:1 : feed im_size
Total:738, Current:2 : feed image
Total:738, Current:738 : fetch lass_nms  
There's 3 ops are not supported yet
=========== tanh ===========
=========== clip ===========
=========== log ===========

**Comment by Lbo18** [comment]
> @Lbo18 新增三个op的pr: #330 ，这边测试可以转换成功，并使用onnxruntime跑通转换后的onnx模型。

是否需要重新用最新的PaddleDetection训练模型呢？

**Comment by Channingss** [comment]
@Lbo18 代码刚刚已经合入了，你可以重新拉取最新的develop分支

**Comment by Lbo18** [comment]
> @Lbo18 代码刚刚已经合入了，你可以重新拉取最新的develop分支

感谢~已解决

**Comment by zhengkai15** [comment]
> > @Lbo18 代码刚刚已经合入了，你可以重新拉取最新的develop分支
> 
> 感谢~已解决

您好可以微信交流一下嘛 zhengkai156252108 我也遇到了同样的问题
