### ISSUE TITLE
安装x2paddle后，运行命令报错

### ISSUE THREAD

**Issue by ccoocode** [PaddlePaddle/X2Paddle#320]
通过下面命令安装x2paddle出错：

git clone https://github.com/PaddlePaddle/X2Paddle.git 
git checkout bert

cd X2Paddle
python setup.py install

**运行 x2paddle 命令提示：
importlib_metadata.api.PackageNotFoundError: x2paddle**

如果直接通过 pip install x2paddle 安装则不会有问题

x2paddle==1.8.0
python==3.6.8

**Comment by mamingjie-China** [comment]
> 通过下面命令安装x2paddle出错：
> 
> git clone https://github.com/PaddlePaddle/X2Paddle.git
> git checkout bert
> 
> cd X2Paddle
> python setup.py install
> 
> **运行 x2paddle 命令提示： importlib_metadata.api.PackageNotFoundError: x2paddle**
> 
> 如果直接通过 pip install x2paddle 安装则不会有问题
> 
> x2paddle==1.8.0
> python==3.6.8

这边暂时无法复现出这个问题，建议使用develop版本，目前也是支持bert模型的转换的，转换时，请添加--without_data_format_optimization参数，有什么问题可以进一步沟通

**Comment by ccoocode** [comment]
importlib_metadata 版本问题，更新到最新版本后解决

**Comment by ccoocode** [comment]
importlib_metadata 版本问题，更新到最新版本后解决
