### ISSUE TITLE
cascade mask rcnn模型由paddle转onnx时有些op不支持

### ISSUE THREAD

**Issue by Tinagao222** [PaddlePaddle/X2Paddle#321]
使用paddleDetection中的cascade_mask_rcnn_r50_fpn_1x模型训练的，转成onnx时出现如下提示

Total:350, Current:1 : feed im_shape
Total:350, Current:2 : feed im_info
Total:350, Current:3 : feed image
Total:32, Current:32 : assign et e_add  posals ls
There's 18 ops are not supported yet
=========== logical_not ===========
=========== roi_align ===========
=========== assign ===========
=========== sequence_expand ===========
=========== box_clip ===========
=========== gather ===========
=========== less_than ===========
=========== conditional_block ===========
=========== box_coder ===========
=========== generate_proposals ===========
=========== elementwise_div ===========
=========== expand ===========
=========== anchor_generator ===========
=========== distribute_fpn_proposals ===========
=========== reduce_prod ===========
=========== collect_fpn_proposals ===========
=========== affine_channel ===========
=========== lod_reset ===========

如需要模型参数信息，请留个邮箱，谢谢~

**Comment by Channingss** [comment]
@Tinagao222 有计划支持更多PaddleOP抓换，但是短期内还无法满足RCNN的转换需求

**Comment by jiangjiajun** [comment]
由于长时间未更新，此issue将被关闭，如有需求，可随时再打开
