### ISSUE TITLE
目的：caffe模型转成paddle模型，再导出模型供其他sdk调用。

### ISSUE THREAD

**Issue by MichaelZhero** [PaddlePaddle/X2Paddle#322]
模型链接：https://github.com/lsy17096535/face-landmark/tree/master/model  

!x2paddle --framework=caffe --prototxt=work/landmark_deploy.prototxt --weight=work/VanFace.caffemodel  --save_dir=work/pd_model
可以生成两个文件：inference_model和model_with_code
![image](https://user-images.githubusercontent.com/16940225/88244584-d194c400-ccc6-11ea-8a31-5aed42359e4e.png)

#命令行#
!paddlex --export_inference --model_dir=work/pd_model/inference_model --save_dir=inference_model

报错
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 122, in main
    model = pdx.load_model(args.model_dir, fixed_input_shape)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 32, in load_model
    raise Exception("There's not model.yml in {}".format(model_dir))
Exception: There's not model.yml in work/pd_model/inference_model

**Comment by jiangjiajun** [comment]
> 模型链接：https://github.com/lsy17096535/face-landmark/tree/master/model
> 
> !x2paddle --framework=caffe --prototxt=work/landmark_deploy.prototxt --weight=work/VanFace.caffemodel --save_dir=work/pd_model
> 可以生成两个文件：inference_model和model_with_code
> ![image](https://user-images.githubusercontent.com/16940225/88244584-d194c400-ccc6-11ea-8a31-5aed42359e4e.png)
> 
> #命令行#
> !paddlex --export_inference --model_dir=work/pd_model/inference_model --save_dir=inference_model
> 
> 报错
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> import imp
> Traceback (most recent call last):
> File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 10, in
> sys.exit(main())
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 122, in main
> model = pdx.load_model(args.model_dir, fixed_input_shape)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 32, in load_model
> raise Exception("There's not model.yml in {}".format(model_dir))
> Exception: There's not model.yml in work/pd_model/inference_model

使用X2Paddle转换完后的模型中的inference_model即部署用的模型，PaddleX是另外一个视觉模型工具库，这个转换与它无关。

**Comment by jiangjiajun** [comment]
此issue长期未更新，将被关闭，如有需求，可随时再打开。
