### ISSUE TITLE
从paddlex训练得到骨干网络为Resnet18的FasterRCNN，想转成onnx模型报错

### ISSUE THREAD

**Issue by MichaelZhero** [PaddlePaddle/X2Paddle#323]
!x2paddle --framework=paddle2onnx --model=work/ --save_dir=work/onnx_model

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
paddle.__version__ = 1.8.0
Translating PaddlePaddle to ONNX...

Total:173, Current:173 : fetch                                      
There's 11 ops are not supported yet
=========== roi_align ===========
=========== sequence_expand ===========
=========== gather ===========
=========== generate_proposals ===========
=========== elementwise_div ===========
=========== box_coder ===========
=========== box_clip ===========
=========== lod_reset ===========
=========== distribute_fpn_proposals ===========
=========== anchor_generator ===========
=========== collect_fpn_proposals ===========
[1]

**Comment by Channingss** [comment]
@MichaelZhero 有计划支持更多PaddleOP抓换，但是短期内还无法满足RCNN的转换需求

**Comment by jiangjiajun** [comment]
此issue长期未更新，将被关闭，如有需求，可随时再打开。
