### ISSUE TITLE
paddle中手写的mobilenetV2模型转onnx : There's 13 ops are not supported yet

### ISSUE THREAD

**Issue by ZhaoFour** [PaddlePaddle/X2Paddle#333]
There's 13 ops are not supported yet
=========== mul_grad ===========
=========== cross_entropy_grad2 ===========
=========== sum ===========
=========== cross_entropy2 ===========
=========== relu6_grad ===========
=========== adam ===========
=========== mean_grad ===========
=========== elementwise_add_grad ===========
=========== conv2d_grad ===========
=========== depthwise_conv2d_grad ===========
=========== pool2d_grad ===========
=========== batch_norm_grad ===========
=========== softmax_grad ===========

**Comment by jiangjiajun** [comment]
> There's 13 ops are not supported yet
> =========== mul_grad ===========
> =========== cross_entropy_grad2 ===========
> =========== sum ===========
> =========== cross_entropy2 ===========
> =========== relu6_grad ===========
> =========== adam ===========
> =========== mean_grad ===========
> =========== elementwise_add_grad ===========
> =========== conv2d_grad ===========
> =========== depthwise_conv2d_grad ===========
> =========== pool2d_grad ===========
> =========== batch_norm_grad ===========
> =========== softmax_grad ===========

目前转ONNX只支持前向推理计算部分的网络进行转换，上面列出来的OP都是优化器及梯度相关OP，请使用fluid.io.save_inference_model将训练好的模型保存下来后再进行转换。

**Comment by ZhaoFour** [comment]
谢谢
