### ISSUE TITLE
onnx转paddle tensor类型转换错误

### ISSUE THREAD

**Issue by xilinniao123** [PaddlePaddle/X2Paddle#350]
x2paddle版本是  0.8.1
paddle 版本是 1.7.2
在文本关系抽取中，将pytorch转化的onnx转为paddle的时候报错，如图所示：
![image](https://user-images.githubusercontent.com/11830865/89491770-91633480-d7e2-11ea-864e-703494fa115c.png)
跟进代码查看发现是dict tensor_type_to_np_type的问题，这个dict的key中没有0出现，但是数据类型转化的时候是0

**Comment by jiangjiajun** [comment]
> 在文本关系抽取中，将pytorch转化的onnx转为paddle的时候报错，如图所示：
> ![image](https://user-images.githubusercontent.com/11830865/89491770-91633480-d7e2-11ea-864e-703494fa115c.png)
> 跟进代码查看发现是dict tensor_type_to_np_type的问题，这个dict的key中没有0出现，但是数据类型转化的时候是0

您好，已经在QQ上跟您沟通哈

**Comment by xilinniao123** [comment]
在另一个模型中发现有一个操作符号不支持
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
There are 1 ops not supported yet, list as below
Not

**Comment by jiangjiajun** [comment]
> 在另一个模型中发现有一个操作符号不支持
> Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
> There are 1 ops not supported yet, list as below
> Not

方便的话发一下模型给我们

**Comment by xilinniao123** [comment]
X2paddle 已经更新
