### ISSUE TITLE
paddleocr模型转onnx出错

### ISSUE THREAD

**Issue by yangfei963158659** [PaddlePaddle/X2Paddle#360]
paddleocr转onnx出错，报错信息如下:
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor version 1904018048 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] at (/paddle/paddle/fluid/framework/lod_tensor.cc:287)
  [operator < load_combine > error]

**Comment by Channingss** [comment]
@yangfei963158659 需要在模型保存的时候，指定参数：params_filename='\_\_params\_\_'
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model

**Comment by iamxinxin** [comment]
遇到同样的问题
