### ISSUE TITLE
Total nodes: 0 ;ValueError: 'target_vars' should be a list of Variable.

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/X2Paddle#361]
自己训练的模型，图像分割，deeplabv3；
以下是转换信息：
paddle.__version__ = 1.8.3
Now translating model from tensorflow to paddle.
Total nodes: 0

Done!
d:\anaconda\envs\py35-pp\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Traceback (most recent call last):
  File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\core\op_mapper.py", line 193, in save_inference_model
    params_filename=None)
  File "d:\anaconda\envs\py35-pp\lib\site-packages\paddle\fluid\io.py", line 1177, in save_inference_model
    raise ValueError("'target_vars' should be a list of Variable.")
ValueError: 'target_vars' should be a list of Variable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\envs\py35-pp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\py35-pp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\py35-pp\Scripts\x2paddle.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\convert.py", line 253, in main
    define_input_shape, params_merge)
  File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\convert.py", line 145, in tf2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\core\op_mapper.py", line 197, in save_inference_model
    .format(py_code_dir))
Exception: Paddle code was saved in ./pd_model\model_with_code/model.py, but seems there's wrong exist, please check model.py manually.

**Comment by mamingjie-China** [comment]
> 自己训练的模型，图像分割，deeplabv3；
> 以下是转换信息：
> paddle.**version** = 1.8.3
> Now translating model from tensorflow to paddle.
> Total nodes: 0
> 
> Done!
> d:\anaconda\envs\py35-pp\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
> warnings.warn(error_info)
> Traceback (most recent call last):
> File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\core\op_mapper.py", line 193, in save_inference_model
> params_filename=None)
> File "d:\anaconda\envs\py35-pp\lib\site-packages\paddle\fluid\io.py", line 1177, in save_inference_model
> raise ValueError("'target_vars' should be a list of Variable.")
> ValueError: 'target_vars' should be a list of Variable.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "d:\anaconda\envs\py35-pp\lib\runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "d:\anaconda\envs\py35-pp\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\Anaconda\envs\py35-pp\Scripts\x2paddle.exe__main__.py", line 9, in
> File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\convert.py", line 253, in main
> define_input_shape, params_merge)
> File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\convert.py", line 145, in tf2paddle
> mapper.save_inference_model(save_dir, params_merge)
> File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\core\op_mapper.py", line 197, in save_inference_model
> .format(py_code_dir))
> Exception: Paddle code was saved in ./pd_model\model_with_code/model.py, but seems there's wrong exist, please check model.py manually.

感谢你的使用，是否可以提供一下你的模型我们这边复现一下问题？

**Comment by iceriver97** [comment]
> > 自己训练的模型，图像分割，deeplabv3；
> > 以下是转换信息：
> > paddle.**version** = 1.8.3
> > Now translating model from tensorflow to paddle.
> > Total nodes: 0
> > Done!
> > d:\anaconda\envs\py35-pp\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
> > warnings.warn(error_info)
> > Traceback (most recent call last):
> > File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\core\op_mapper.py", line 193, in save_inference_model
> > params_filename=None)
> > File "d:\anaconda\envs\py35-pp\lib\site-packages\paddle\fluid\io.py", line 1177, in save_inference_model
> > raise ValueError("'target_vars' should be a list of Variable.")
> > ValueError: 'target_vars' should be a list of Variable.
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "d:\anaconda\envs\py35-pp\lib\runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "d:\anaconda\envs\py35-pp\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\Anaconda\envs\py35-pp\Scripts\x2paddle.exe__main__.py", line 9, in
> > File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\convert.py", line 253, in main
> > define_input_shape, params_merge)
> > File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\convert.py", line 145, in tf2paddle
> > mapper.save_inference_model(save_dir, params_merge)
> > File "d:\anaconda\envs\py35-pp\lib\site-packages\x2paddle\core\op_mapper.py", line 197, in save_inference_model
> > .format(py_code_dir))
> > Exception: Paddle code was saved in ./pd_model\model_with_code/model.py, but seems there's wrong exist, please check model.py manually.
> 
> 感谢你的使用，是否可以提供一下你的模型我们这边复现一下问题？

怎样给你文件呢？这个模型有149M

**Comment by iceriver97** [comment]
@mamingjie-China 我放在百度云了，谢谢你能帮我
链接：https://pan.baidu.com/s/11GGAYdGg8ofIKHOSuxvDpA 
提取码：j3j8

**Comment by mamingjie-China** [comment]
> @mamingjie-China 我放在百度云了，谢谢你能帮我
> 链接：https://pan.baidu.com/s/11GGAYdGg8ofIKHOSuxvDpA
> 提取码：j3j8

模型我看了一下，感觉是在pb保存的时候有问题，我用netron打开后，结构如图，请检查一下保存的过程，确定是在参数固化后，生成的pb文件。
![image](https://user-images.githubusercontent.com/52770436/89897614-e1daf780-dc11-11ea-84fb-b44bf1cb83da.png)

**Comment by iceriver97** [comment]
@mamingjie-China 
非常感谢！
以下是固化模型的操作：

```
def freeze_model(sess, output_tensor_names, freeze_model_path):
    out_graph = graph_util.convert_variables_to_constants(
        sess, sess.graph.as_graph_def(), output_tensor_names)
    with tf.gfile.GFile(freeze_model_path, 'wb') as f:
        f.write(out_graph.SerializeToString())

    print("freeze model saved in {}".format(freeze_model_path))
```
[deeplab_saved_model.zip](https://github.com/PaddlePaddle/X2Paddle/files/5056995/deeplab_saved_model.zip


```
with tf.Session(graph=tf.Graph()) as sess:

        # define placeholders for receiving the input image height and width
        image_height_tensor = tf.placeholder(tf.int32)
        image_width_tensor = tf.placeholder(tf.int32)

        # placeholder for receiving the serialized input image
        serialized_tf_example = tf.placeholder(tf.string, name='tf_example')
        feature_configs = {'x': tf.FixedLenFeature(shape=[], dtype=tf.float32), }
        tf_example = tf.parse_example(serialized_tf_example, feature_configs)

        # reshape the input image to its original dimension
        tf_example['x'] = tf.reshape(tf_example['x'], (1, image_height_tensor, image_width_tensor, 3))
        input_tensor = tf.identity(tf_example['x'], name='x')  # use tf.identity() to assign name

        # perform inference on the input image
        logits_tf = network.deeplab_v3(input_tensor, args, is_training=False, reuse=False)

        # extract the segmentation mask
        predictions_tf = tf.argmax(logits_tf, axis=3)

        # specify the directory where the pre-trained model weights are stored
        pre_trained_model_dir = os.path.join(log_folder, model_name, "train")

        saver = tf.train.Saver()

        # Restore variables from disk.
        saver.restore(sess, os.path.join(pre_trained_model_dir, "model.ckpt"))
        print("Model", model_name, "restored.")

        # Create SavedModelBuilder class
        # defines where the model will be exported
        export_path_base = FLAGS.export_model_dir
        export_path = os.path.join(
            tf.compat.as_bytes(export_path_base),
            tf.compat.as_bytes(str(FLAGS.model_version)))
        print('Exporting trained model to', export_path)
        builder = tf.saved_model.builder.SavedModelBuilder(export_path)

        # Creates the TensorInfo protobuf objects that encapsulates the input/output tensors
        tensor_info_input = tf.saved_model.utils.build_tensor_info(input_tensor)
        tensor_info_height = tf.saved_model.utils.build_tensor_info(image_height_tensor)
        tensor_info_width = tf.saved_model.utils.build_tensor_info(image_width_tensor)

        # output tensor info
        tensor_info_output = tf.saved_model.utils.build_tensor_info(predictions_tf)

        # Defines the DeepLab signatures, uses the TF Predict API
        # It receives an image and its dimensions and output the segmentation mask
        prediction_signature = (
            tf.saved_model.signature_def_utils.build_signature_def(
                inputs={'images': tensor_info_input, 'height': tensor_info_height, 'width': tensor_info_width},
                outputs={'segmentation_map': tensor_info_output},
                method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))

        builder.add_meta_graph_and_variables(
            sess, [tf.saved_model.tag_constants.SERVING],
            signature_def_map={
                'predict_images':
                    prediction_signature,
            })

        # export the model
        builder.save(as_text=True)
        # builder.save(as_text=False)
        # 打印所有需要训练的变量
        variable_names = [v.name[:-2] for v in tf.trainable_variables()]
        print(variable_names)
        freeze_model(sess, variable_names, "deeplabv3.pb")
        print('Done exporting!')
```

**Comment by iceriver97** [comment]
@mamingjie-China 这里生成pb文件的操作有错误吗？谢谢

**Comment by mamingjie-China** [comment]
> @mamingjie-China
> 非常感谢！
> 以下是固化模型的操作：
> 
> ```
> def freeze_model(sess, output_tensor_names, freeze_model_path):
>     out_graph = graph_util.convert_variables_to_constants(
>         sess, sess.graph.as_graph_def(), output_tensor_names)
>     with tf.gfile.GFile(freeze_model_path, 'wb') as f:
>         f.write(out_graph.SerializeToString())
> 
>     print("freeze model saved in {}".format(freeze_model_path))
> ```
> 
> [deeplab_saved_model.zip](https://github.com/PaddlePaddle/X2Paddle/files/5056995/deeplab_saved_model.zip
> 
> ```
> with tf.Session(graph=tf.Graph()) as sess:
> 
>         # define placeholders for receiving the input image height and width
>         image_height_tensor = tf.placeholder(tf.int32)
>         image_width_tensor = tf.placeholder(tf.int32)
> 
>         # placeholder for receiving the serialized input image
>         serialized_tf_example = tf.placeholder(tf.string, name='tf_example')
>         feature_configs = {'x': tf.FixedLenFeature(shape=[], dtype=tf.float32), }
>         tf_example = tf.parse_example(serialized_tf_example, feature_configs)
> 
>         # reshape the input image to its original dimension
>         tf_example['x'] = tf.reshape(tf_example['x'], (1, image_height_tensor, image_width_tensor, 3))
>         input_tensor = tf.identity(tf_example['x'], name='x')  # use tf.identity() to assign name
> 
>         # perform inference on the input image
>         logits_tf = network.deeplab_v3(input_tensor, args, is_training=False, reuse=False)
> 
>         # extract the segmentation mask
>         predictions_tf = tf.argmax(logits_tf, axis=3)
> 
>         # specify the directory where the pre-trained model weights are stored
>         pre_trained_model_dir = os.path.join(log_folder, model_name, "train")
> 
>         saver = tf.train.Saver()
> 
>         # Restore variables from disk.
>         saver.restore(sess, os.path.join(pre_trained_model_dir, "model.ckpt"))
>         print("Model", model_name, "restored.")
> 
>         # Create SavedModelBuilder class
>         # defines where the model will be exported
>         export_path_base = FLAGS.export_model_dir
>         export_path = os.path.join(
>             tf.compat.as_bytes(export_path_base),
>             tf.compat.as_bytes(str(FLAGS.model_version)))
>         print('Exporting trained model to', export_path)
>         builder = tf.saved_model.builder.SavedModelBuilder(export_path)
> 
>         # Creates the TensorInfo protobuf objects that encapsulates the input/output tensors
>         tensor_info_input = tf.saved_model.utils.build_tensor_info(input_tensor)
>         tensor_info_height = tf.saved_model.utils.build_tensor_info(image_height_tensor)
>         tensor_info_width = tf.saved_model.utils.build_tensor_info(image_width_tensor)
> 
>         # output tensor info
>         tensor_info_output = tf.saved_model.utils.build_tensor_info(predictions_tf)
> 
>         # Defines the DeepLab signatures, uses the TF Predict API
>         # It receives an image and its dimensions and output the segmentation mask
>         prediction_signature = (
>             tf.saved_model.signature_def_utils.build_signature_def(
>                 inputs={'images': tensor_info_input, 'height': tensor_info_height, 'width': tensor_info_width},
>                 outputs={'segmentation_map': tensor_info_output},
>                 method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))
> 
>         builder.add_meta_graph_and_variables(
>             sess, [tf.saved_model.tag_constants.SERVING],
>             signature_def_map={
>                 'predict_images':
>                     prediction_signature,
>             })
> 
>         # export the model
>         builder.save(as_text=True)
>         # builder.save(as_text=False)
>         # 打印所有需要训练的变量
>         variable_names = [v.name[:-2] for v in tf.trainable_variables()]
>         print(variable_names)
>         freeze_model(sess, variable_names, "deeplabv3.pb")
>         print('Done exporting!')
> ```

pb模型的保存，可以参考网上的示例，如果遇到问题，可以向Tensorflow的repo提出issue解决

**Comment by iceriver97** [comment]
@mamingjie-China  好的谢谢

**Comment by iceriver97** [comment]
@mamingjie-China  我在保存模型时只用指定与原来模型输入相同形状的张量还是说必须是原模型的输入

`logits, endpoint = vgg.vgg_16(inputs, num_classes=1000, is_training=False)` 就是说官方示例代码的 inputs 是不是只需要与原模型输入张量维度保持一致就可以? 谢谢

**Comment by jiangjiajun** [comment]
> @mamingjie-China 我在保存模型时只用指定与原来模型输入相同形状的张量还是说必须是原模型的输入
> 
> `logits, endpoint = vgg.vgg_16(inputs, num_classes=1000, is_training=False)` 就是说官方示例代码的 inputs 是不是只需要与原模型输入张量维度保持一致就可以? 谢谢

需要与原模型shape维度一致

**Comment by iceriver97** [comment]
@jiangjiajun  谢谢，比如我原来模型的输入是 从TFRecord读入的，维度为 (?, 512, 512, 3)，是不是这样指定inputs:
`inputs = tf.placeholder(dtype=tf.float32,shape=[None, 512, 512, 3],name="inputs")`

**Comment by jiangjiajun** [comment]
> @jiangjiajun 谢谢，比如我原来模型的输入是 从TFRecord读入的，维度为 (?, 512, 512, 3)，是不是这样指定inputs:
> `inputs = tf.placeholder(dtype=tf.float32,shape=[None, 512, 512, 3],name="inputs")`

这里得看模型经过预处理后，输给模型的数据大小是多大

**Comment by iceriver97** [comment]
@jiangjiajun  谢谢，这是调用模型的语句：（network.deeplab_v3是网络名称）
`logits_tf =  network.deeplab_v3(batch_images_tf, args, is_training=False, reuse=False)`
我是不是应该 使inputs = batch_images_tf,并且在导出模型时保存logits_tf?
