### ISSUE TITLE
Caffe proto Upsample层没有更新，导致Upsample不能直接转

### ISSUE THREAD

**Issue by AlphaLFC** [PaddlePaddle/X2Paddle#372]
Caffe proto Upsample层没有更新，导致Upsample不能直接转
能不能把调试upsample的层的caffe.proto文件里加上upsample这一层，方便大家使用，省得重新生成caffe_pb2.py文件了

**Comment by SunAhong1993** [comment]
> Caffe proto Upsample层没有更新，导致Upsample不能直接转
> 能不能把调试upsample的层的caffe.proto文件里加上upsample这一层，方便大家使用，省得重新生成caffe_pb2.py文件了

这边针对该问题已经提了PR  https://github.com/PaddlePaddle/X2Paddle/pull/377 ，您可
```
git clone https://github.com/PaddlePaddle/X2Paddle.git
python setup.py install 
```
安装新的X2Paddle包，即有Upsample层。

**Comment by AlphaLFC** [comment]
感谢！提供了caffe.proto也可以更方便地加其他层
