### ISSUE TITLE
onnx模型转paddle，batch normalization为啥没了

### ISSUE THREAD

**Issue by liutinglt** [PaddlePaddle/X2Paddle#38]
转出来的模型，BN没了。。。。 而且使用X2Paddle的时候，报segment fault，卸载掉paddle就好了~~

**Comment by MacroBull** [comment]
* onnx2paddle目前支持 **预测模型转换** ，一些训练用的算子会被优化掉，其中包括BN嵌入Conv
* 用于训练的模型转换，目前还不支持精度验证
* 出现segment fault清贴出完整输出信息以反馈

**Comment by MacroBull** [comment]
有需求的话，可以试试 #40

**Comment by jiangjiajun** [comment]
因为问题长时间未回复，此issue将被close，如此issue后续仍有问题，可重新再打开。
