### ISSUE TITLE
黄埔学院 x2paddle

### ISSUE THREAD

**Issue by yajiezhu** [PaddlePaddle/X2Paddle#383]
x2paddle 支持textCNN、bi-lstm-crf模型tf2pd吗

**Comment by yajiezhu** [comment]
x2paddle 支持textCNN、bi-lstm-crf模型tf2pd吗

**Comment by jiangjiajun** [comment]
> x2paddle 支持textCNN、bi-lstm-crf模型tf2pd吗

textCNN支持，序列类暂不支持
Duplicate of https://github.com/PaddlePaddle/X2Paddle/issues/382
