### ISSUE TITLE
vgg19 to paddle, 1 OPs are not supported yet

### ISSUE THREAD

**Issue by shikeno** [PaddlePaddle/X2Paddle#400]
TensorFlow模型转换至PaddlePaddle，请说明TensorFlow模型的来源，模型类型（例如图像分类、目标检测等）  

如有原模型文件或github链接，可以一并附上，方便开发人员分析。

paddle.__version__ = 1.8.2
Now translating model from tensorflow to paddle.
Total nodes: 101
Converting node 1 ...     Unknown shape of input nodes[InputImage].
Converting node 101 ...     ========= 1 OPs are not supported yet ===========
========== Placeholder ============

**Comment by jiangjiajun** [comment]
> TensorFlow模型转换至PaddlePaddle，请说明TensorFlow模型的来源，模型类型（例如图像分类、目标检测等）
> 
> 如有原模型文件或github链接，可以一并附上，方便开发人员分析。
> 
> paddle.**version** = 1.8.2
> Now translating model from tensorflow to paddle.
> Total nodes: 101
> Converting node 1 ... Unknown shape of input nodes[InputImage].
> Converting node 101 ... ========= 1 OPs are not supported yet ===========
> ========== Placeholder ============

在模型转换时，添加参数--define_input_shape试下
