### ISSUE TITLE
There's 1 ops are not supported yet

### ISSUE THREAD

**Issue by FitzShen666** [PaddlePaddle/X2Paddle#407]
paddleslim中提供的预训练模型SlimFaceNet_A_x0_60

There's 1 ops are not supported yet
=========== prelu ===========

请问近期会支持这个op吗？

**Comment by Channingss** [comment]
@FitzShen666 
已经新增了prelu的转换，请手动安装develop分支，最新的代码：[安装方式](https://github.com/PaddlePaddle/X2Paddle#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F%E4%B8%80%E6%8E%A8%E8%8D%90)
