### ISSUE TITLE
Paddle to Tensorflow

### ISSUE THREAD

**Issue by duongvvuet** [PaddlePaddle/X2Paddle#415]
Does PaddleOCR support model conversion to tensorflow and how do I do it?

**Comment by jiangjiajun** [comment]
> Does PaddleOCR support model conversion to tensorflow and how do I do it?

PaddlePaddle to TensorFlow is not supported by X2Paddle. But you can use X2Paddle to convert PaddleOCR(only detect model ,not recgnition model) to ONNX.
