### ISSUE TITLE
PP-YOLO to onnx

### ISSUE THREAD

**Issue by leozicai** [PaddlePaddle/X2Paddle#416]
我使用了paddle的PP-YOLO训练了一个模型，但是发现paddle2onnx不支持PP-YOLO转成onnx，原因是暂不支持可变卷积层和一些矩阵的变换。想问下什么时候能支持PP-YOLO转onnx？

**Comment by leozicai** [comment]
实际运行PP-YOLO转换到onnx发现除了上面提到的还缺了几个支持。
![捕获](https://user-images.githubusercontent.com/53112849/94539784-46ace880-0278-11eb-9637-d4b662bfc15b.PNG)

我使用PP-YOLO与yolov5对同一个数据集进行训练比较，PP-YOLO的mAP略高于yolov5，性能很好，Paddleslim的剪枝等压缩模型的工具很好用，希望大佬们加油开发出缺少的支持，帮助PP-YOLO落地到不同的平台~

**Comment by jiangjiajun** [comment]
> 实际运行PP-YOLO转换到onnx发现除了上面提到的还缺了几个支持。
> ![捕获](https://user-images.githubusercontent.com/53112849/94539784-46ace880-0278-11eb-9637-d4b662bfc15b.PNG)
> 
> 我使用PP-YOLO与yolov5对同一个数据集进行训练比较，PP-YOLO的mAP略高于yolov5，性能很好，Paddleslim的剪枝等压缩模型的工具很好用，希望大佬们加油开发出缺少的支持，帮助PP-YOLO落地到不同的平台~

目前还没有支持PP-YOLO，涉及到较多OP的开发，目前检测支持的模型包括YOLOv3和SSD

**Comment by leozicai** [comment]
好的，谢谢大佬，你们辛苦了~
