### ISSUE TITLE
detectron2模型转化成paddle模型问题

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/X2Paddle#417]
使用detectron2自带转化脚本转化模型成caffe2模型，然后尝试caffe2模型转成onnx，再由onnx转成paddle模型，但caffe2模型转成onnx模型需要shape和type，请问这个从哪获取

请问detectron2模型转化成paddle模型有脚本吗？

**Comment by Channingss** [comment]
@mcl-stone 这个可以使用名为Netron的可视化软件查看到。

**Comment by mcl-stone** [comment]
> @mcl-stone 这个可以使用名为Netron的可视化软件查看到。

好的，感谢！
