### ISSUE TITLE
请问caffe2paddle转后的模型，如何预测，有没有预测脚本

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/X2Paddle#419]
模型是关键点检测，转换成功了，转换后如何预测，文档内的地址不知如何使用

**Comment by mcl-stone** [comment]
![image](https://user-images.githubusercontent.com/62418900/96070432-cc64a100-0ed2-11eb-956c-b597b9168644.png)
根据咱提供的文档写了这个脚本，但报错了
root@mcl-virtual-machine:/home/mcl/Desktop/body_25/123# python3 test.py 
/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
  warnings.warn(
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    results = exe.run(inference_program,feed={feed_target_names[0]: tensorimg},fetch_list=fetch_targets)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1056, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1146, in _run_impl
    return self._run_program(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1228, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2604, in append_op
    op = Operator(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/nn.py", line 2922, in conv2d
    helper.append_op(
  File "123/model_with_code/model.py", line 7, in x2paddle_net
    relu1_1 = fluid.layers.conv2d(image, filter_size=[3, 3], num_filters=64, stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
  File "/usr/local/lib/python3.8/dist-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 157, in caffe2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 297, in main
    caffe2paddle(args.prototxt, args.weight, args.save_dir,
  File "/usr/local/bin/x2paddle", line 8, in <module>
    sys.exit(main())

----------------------
Error Message Summary:
----------------------
Error: op conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
  [operator < conv2d > error]
root@mcl-virtual-machine:/home/mcl/Desktop/body_25/123# python3 test.py 
/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
  warnings.warn(
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    results = exe.run(inference_program,feed={feed_target_names[0]: tensorimg},fetch_list=fetch_targets)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1056, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1146, in _run_impl
    return self._run_program(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1228, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2604, in append_op
    op = Operator(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/nn.py", line 2922, in conv2d
    helper.append_op(
  File "123/model_with_code/model.py", line 7, in x2paddle_net
    relu1_1 = fluid.layers.conv2d(image, filter_size=[3, 3], num_filters=64, stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
  File "/usr/local/lib/python3.8/dist-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 157, in caffe2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 297, in main
    caffe2paddle(args.prototxt, args.weight, args.save_dir,
  File "/usr/local/bin/x2paddle", line 8, in <module>
    sys.exit(main())

----------------------
Error Message Summary:
----------------------
Error: op conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
  [operator < conv2d > error]

**Comment by jiangjiajun** [comment]
> ![image](https://user-images.githubusercontent.com/62418900/96070432-cc64a100-0ed2-11eb-956c-b597b9168644.png)
> 根据咱提供的文档写了这个脚本，但报错了
> root@mcl-virtual-machine:/home/mcl/Desktop/body_25/123# python3 test.py
> /usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
> warnings.warn(
> Traceback (most recent call last):
> File "test.py", line 7, in
> results = exe.run(inference_program,feed={feed_target_names[0]: tensorimg},fetch_list=fetch_targets)
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1071, in run
> six.reraise(*sys.exc_info())
> File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
> raise value
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1056, in run
> return self._run_impl(
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1146, in _run_impl
> return self._run_program(
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1228, in _run_program
> self._default_executor.run(program.desc, scope, 0, True, True,
> paddle.fluid.core_avx.EnforceNotMet:
> 
> ## C++ Call Stacks (More useful to developers):
> 0 std::string paddle::platform::GetTraceBackStringstd::string(std::string&&, char const*, int)
> 1 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> 2 paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
> 3 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> 4 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> 5 paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> 6 paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
> 7 paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
> 8 paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocatorstd::string > const&, bool, bool)
> 
> ## Python Call Stacks (More useful to users):
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2604, in append_op
> op = Operator(
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/nn.py", line 2922, in conv2d
> helper.append_op(
> File "123/model_with_code/model.py", line 7, in x2paddle_net
> relu1_1 = fluid.layers.conv2d(image, filter_size=[3, 3], num_filters=64, stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
> File "/usr/local/lib/python3.8/dist-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
> inputs, outputs = model.x2paddle_net()
> File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 157, in caffe2paddle
> mapper.save_inference_model(save_dir, params_merge)
> File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 297, in main
> caffe2paddle(args.prototxt, args.weight, args.save_dir,
> File "/usr/local/bin/x2paddle", line 8, in
> sys.exit(main())
> 
> ## Error Message Summary:
> Error: op conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
> [operator < conv2d > error]
> root@mcl-virtual-machine:/home/mcl/Desktop/body_25/123# python3 test.py
> /usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
> warnings.warn(
> Traceback (most recent call last):
> File "test.py", line 7, in
> results = exe.run(inference_program,feed={feed_target_names[0]: tensorimg},fetch_list=fetch_targets)
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1071, in run
> six.reraise(*sys.exc_info())
> File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
> raise value
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1056, in run
> return self._run_impl(
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1146, in _run_impl
> return self._run_program(
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1228, in _run_program
> self._default_executor.run(program.desc, scope, 0, True, True,
> paddle.fluid.core_avx.EnforceNotMet:
> 
> ## C++ Call Stacks (More useful to developers):
> 0 std::string paddle::platform::GetTraceBackStringstd::string(std::string&&, char const*, int)
> 1 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> 2 paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
> 3 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> 4 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> 5 paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> 6 paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
> 7 paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
> 8 paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocatorstd::string > const&, bool, bool)
> 
> ## Python Call Stacks (More useful to users):
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2604, in append_op
> op = Operator(
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/nn.py", line 2922, in conv2d
> helper.append_op(
> File "123/model_with_code/model.py", line 7, in x2paddle_net
> relu1_1 = fluid.layers.conv2d(image, filter_size=[3, 3], num_filters=64, stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
> File "/usr/local/lib/python3.8/dist-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
> inputs, outputs = model.x2paddle_net()
> File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 157, in caffe2paddle
> mapper.save_inference_model(save_dir, params_merge)
> File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 297, in main
> caffe2paddle(args.prototxt, args.weight, args.save_dir,
> File "/usr/local/bin/x2paddle", line 8, in
> sys.exit(main())
> 
> ## Error Message Summary:
> Error: op conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
> [operator < conv2d > error]



> 模型是关键点检测，转换成功了，转换后如何预测，文档内的地址不知如何使用

X2Paddle只负责转换模型，而一个任务的运行是包括了数据的预处理、模型预测、模型预测结果后处理等步骤的，建议参阅一下原caffe模型的预测代码，然后对应到转换后的模型进行相应处理并预测

**Comment by mcl-stone** [comment]
> > ![image](https://user-images.githubusercontent.com/62418900/96070432-cc64a100-0ed2-11eb-956c-b597b9168644.png)
> > 根据咱提供的文档写了这个脚本，但报错了
> > root@mcl-virtual-machine:/home/mcl/Desktop/body_25/123# python3 test.py
> > /usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
> > warnings.warn(
> > Traceback (most recent call last):
> > File "test.py", line 7, in
> > results = exe.run(inference_program,feed={feed_target_names[0]: tensorimg},fetch_list=fetch_targets)
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1071, in run
> > six.reraise(*sys.exc_info())
> > File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
> > raise value
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1056, in run
> > return self._run_impl(
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1146, in _run_impl
> > return self._run_program(
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1228, in _run_program
> > self._default_executor.run(program.desc, scope, 0, True, True,
> > paddle.fluid.core_avx.EnforceNotMet:
> > ## C++ Call Stacks (More useful to developers):
> > 0 std::string paddle::platform::GetTraceBackStringstd::string(std::string&&, char const*, int)
> > 1 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> > 2 paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
> > 3 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> > 4 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> > 5 paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> > 6 paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
> > 7 paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
> > 8 paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocatorstd::string > const&, bool, bool)
> > ## Python Call Stacks (More useful to users):
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2604, in append_op
> > op = Operator(
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> > return self.main_program.current_block().append_op(*args, **kwargs)
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/nn.py", line 2922, in conv2d
> > helper.append_op(
> > File "123/model_with_code/model.py", line 7, in x2paddle_net
> > relu1_1 = fluid.layers.conv2d(image, filter_size=[3, 3], num_filters=64, stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
> > File "/usr/local/lib/python3.8/dist-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
> > inputs, outputs = model.x2paddle_net()
> > File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 157, in caffe2paddle
> > mapper.save_inference_model(save_dir, params_merge)
> > File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 297, in main
> > caffe2paddle(args.prototxt, args.weight, args.save_dir,
> > File "/usr/local/bin/x2paddle", line 8, in
> > sys.exit(main())
> > ## Error Message Summary:
> > Error: op conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
> > [operator < conv2d > error]
> > root@mcl-virtual-machine:/home/mcl/Desktop/body_25/123# python3 test.py
> > /usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py:1069: UserWarning: The following exception is not an EOF exception.
> > warnings.warn(
> > Traceback (most recent call last):
> > File "test.py", line 7, in
> > results = exe.run(inference_program,feed={feed_target_names[0]: tensorimg},fetch_list=fetch_targets)
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1071, in run
> > six.reraise(*sys.exc_info())
> > File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
> > raise value
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1056, in run
> > return self._run_impl(
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1146, in _run_impl
> > return self._run_program(
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1228, in _run_program
> > self._default_executor.run(program.desc, scope, 0, True, True,
> > paddle.fluid.core_avx.EnforceNotMet:
> > ## C++ Call Stacks (More useful to developers):
> > 0 std::string paddle::platform::GetTraceBackStringstd::string(std::string&&, char const*, int)
> > 1 paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
> > 2 paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
> > 3 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
> > 4 paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
> > 5 paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
> > 6 paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
> > 7 paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
> > 8 paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocatorstd::string > const&, bool, bool)
> > ## Python Call Stacks (More useful to users):
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2604, in append_op
> > op = Operator(
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> > return self.main_program.current_block().append_op(*args, **kwargs)
> > File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/nn.py", line 2922, in conv2d
> > helper.append_op(
> > File "123/model_with_code/model.py", line 7, in x2paddle_net
> > relu1_1 = fluid.layers.conv2d(image, filter_size=[3, 3], num_filters=64, stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
> > File "/usr/local/lib/python3.8/dist-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
> > inputs, outputs = model.x2paddle_net()
> > File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 157, in caffe2paddle
> > mapper.save_inference_model(save_dir, params_merge)
> > File "/usr/local/lib/python3.8/dist-packages/x2paddle/convert.py", line 297, in main
> > caffe2paddle(args.prototxt, args.weight, args.save_dir,
> > File "/usr/local/bin/x2paddle", line 8, in
> > sys.exit(main())
> > ## Error Message Summary:
> > Error: op conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
> > [operator < conv2d > error]
> 
> > 模型是关键点检测，转换成功了，转换后如何预测，文档内的地址不知如何使用
> 
> X2Paddle只负责转换模型，而一个任务的运行是包括了数据的预处理、模型预测、模型预测结果后处理等步骤的，建议参阅一下原caffe模型的预测代码，然后对应到转换后的模型进行相应处理并预测

明白！感谢！
