### ISSUE TITLE
mobilenet_v1_0.25_128_quant_frozen.pb tflite官网 量化模型 1ops are not supported

### ISSUE THREAD

**Issue by tx1103mark** [PaddlePaddle/X2Paddle#422]
TensorFlow模型转换至PaddlePaddle，请说明TensorFlow模型的来源，模型类型（例如图像分类、目标检测等）  

如有原模型文件或github链接，可以一并附上，方便开发人员分析。

**Comment by jiangjiajun** [comment]
请问具体提示信息是什么呢
