### ISSUE TITLE
加载转换好的模型时报错Enforce failed. Expected version == 0U, but received version:5 != 0U:0.

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/X2Paddle#43]
已有issue，https://github.com/PaddlePaddle/X2Paddle/issues/24 ，但未给出Windows下的解决方案，请教下。

**Comment by A1exy** [comment]
在Window下进行Tensorflow转Paddle，使用官方提供的Demo VGG16转换例子报错。
![image](https://user-images.githubusercontent.com/7035538/61605156-c99ae200-ac76-11e9-953a-26ba143e7356.png)


请问Windows下的问题修复了没有，或者怎么规避掉它，谢谢

**Comment by A1exy** [comment]
@jiangjiajun ,@SunAhong1993,@MacroBull

**Comment by jiangjiajun** [comment]
> 在Window下进行Tensorflow转Paddle，使用官方提供的Demo VGG16转换例子报错。
> ![image](https://user-images.githubusercontent.com/7035538/61605156-c99ae200-ac76-11e9-953a-26ba143e7356.png)
> 
> 请问Windows下的问题修复了没有，或者怎么规避掉它，谢谢

Hi，你好，可以尝试下这个PR https://github.com/PaddlePaddle/X2Paddle/pull/44

**Comment by A1exy** [comment]
@jiangjiajun  好的  我马上试一下

**Comment by A1exy** [comment]
@jiangjiajun   解决了 多谢  🐮🍺
![image](https://user-images.githubusercontent.com/7035538/61674470-91eb7300-ad26-11e9-8f75-5a2221b882a1.png)
