### ISSUE TITLE
caffe2fluid模型加载与预测代码问题

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/X2Paddle#45]
将Caffe模型转成Paddle模型，参考https://github.com/PaddlePaddle/X2Paddle/tree/master/caffe2fluid，执行完第一步和第二步后，生成的文件如下：
![image](https://user-images.githubusercontent.com/7035538/61676092-4ee0ce00-ad2d-11e9-956b-4fddae1d1bc8.png)
文档上写模型的加载及预测可参考PaddlePaddle官方文档： https://www.paddlepaddle.org.cn/documentation/docs/zh/1.3/api_guides/low_level/inference.html#id4
但你们参考的文档上模型目录下需要包含 ./infer_model/ __ model __  文件，Caffe模型转Paddle模型的文件夹中并没有该文件。请问怎么解决，或者有这个Inference的代码参考一下吗？
@SunAhong1993 @jiangjiajun

**Comment by A1exy** [comment]
Windows下Inference代码可能存在问题，https://github.com/PaddlePaddle/book/tree/develop/03.image_classification下进行分类训练后的模型如下：
![image](https://user-images.githubusercontent.com/7035538/61676611-3bcefd80-ad2f-11e9-80b8-f01952d287f1.png)

Inference代码如下：
![image](https://user-images.githubusercontent.com/7035538/61676654-64ef8e00-ad2f-11e9-86d8-82e6f72c601e.png)

报错信息如下：
![image](https://user-images.githubusercontent.com/7035538/61676676-733daa00-ad2f-11e9-9d8d-c9772c9d4a2c.png)

**Comment by A1exy** [comment]
参考以下链接，按照ImageNet数据集的AlexNet操作，都不行。。
https://github.com/PaddlePaddle/X2Paddle/tree/master/caffe2fluid/examples/imagenet  
![image](https://user-images.githubusercontent.com/7035538/61679329-77ba9080-ad38-11e9-89d5-0ca136eb2167.png)

**Comment by A1exy** [comment]
自带的例子都跑不通。。。

**Comment by SunAhong1993** [comment]
Hi，你好。针对你在issue中提到的问题，我这边归纳存在如下三个问题，
1. Caffe模型转Paddle模型的文件夹中没有"__model__"文件
> 在save_inference_model时对’__model__‘（此为默认名）进行了重命名成了’model‘，其实现可以参见caffe2fluid/kaffe/net_template.py中下述的这段代码
![image](https://user-images.githubusercontent.com/48579383/61680916-f108b200-ad3d-11e9-8399-7d130b5bcfd1.png)
具体可以参考[API](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/io_cn.html#load-inference-model)。至于如何inference，你可以使用caffe2fluid/examples/imagenet/infer.py，或者使用下述代码进行inference：
```python
import paddle.fluid as fluid
import numpy as np
exe = fluid.Executor(fluid.CPUPlace())
img = np.random.rand(10,3,227,227).astype('float32')
[inference_program, feed_target_names, fetch_targets] = \
            fluid.io.load_inference_model(dirname='./fluid_model', 
                                          executor=exe, model_filename='model', 
                                          params_filename='params')
with fluid.program_guard(inference_program):
    results = exe.run(inference_program, feed={feed_target_names[0]: img}, fetch_list=fetch_targets)
    print(np.array(results[0]).flatten()[:100])
```
2. https://github.com/PaddlePaddle/book/tree/develop/03.image_classification 中训练的模型如何infer
> 根据你的截图中的infer代码，在传入图片数据时没有使用正确，应该传入XX，而在截图中的代码传入的是字符串
3. https://github.com/PaddlePaddle/X2Paddle/tree/master/caffe2fluid/examples/imagenet 中例子无法跑通
> 本问题确实存在，我这边已经提交了新的代码，麻烦pull一下最新的代码；同时应该使用命令行`python infer.py infer ../../fluid_model/ ./data/65.jpeg`，其中倒数第二个参数为转换后的paddle模型所在文件夹。

**Comment by A1exy** [comment]
@SunAhong1993 好的，多谢，我去试一下

**Comment by jiangjiajun** [comment]
@A1exy 非常欢迎对X2Paddle提出建议，我们现在正在继续开发X2Paddle，解决之前遗留的问题，同时提升整体的易用性和OP及模型的覆盖率。有需求可以关注我们的repo，以收到最新的进展：)

**Comment by A1exy** [comment]
@SunAhong1993   问题已解决，多谢
@jiangjiajun   已经Watch项目最新进展：)
