### ISSUE TITLE
Caffe模型转换至PaddlePaddle失败

### ISSUE THREAD

**Issue by Xsx93** [PaddlePaddle/X2Paddle#450]
Caffe模型转换至PaddlePaddle，Caffe模型是于仕琪的SSD模型，模型人脸检测  

![IMG2020129-102549](https://user-images.githubusercontent.com/32325982/101566262-a9a1c500-3a09-11eb-8638-fcd81fa1fa0c.jpg)

**Comment by SunAhong1993** [comment]
> Caffe模型转换至PaddlePaddle，Caffe模型是于仕琪的SSD模型，模型人脸检测
> 
> ![IMG2020129-102549](https://user-images.githubusercontent.com/32325982/101566262-a9a1c500-3a09-11eb-8638-fcd81fa1fa0c.jpg)

你好，方便提供下模型（.prototxt和.caffemodel）发邮件到sunyanfang01@baidu.com吗

**Comment by SunAhong1993** [comment]
刚又仔细看了下报错信息，发现你的X2Paddle版本比较老，这个bug目前已经解决，您可以重装下X2Paddle，重装方式：
```shell
pip  uninstall x2paddle
git  clone https://github.com/PaddlePaddle/X2Paddle.git -b release-0.9
cd X2Paddle
python setup.py install
```
