### ISSUE TITLE
Missing ONNX ArgMax support

### ISSUE THREAD

**Issue by arogowie-intel** [PaddlePaddle/X2Paddle#464]
Hi, 

Thank you for this great tool! 

I tried to convert [MLPerf ResNet50 model](https://zenodo.org/record/2592612/files/resnet50_v1.onnx) (listed [here](https://github.com/mlcommons/inference/tree/master/vision/classification_and_detection#supported-models)) and get an error saying that there is missing `ArgMax` op support. 

Commandline I used:
```shell
x2paddle --framework=onnx --model=/path/to/resnet50_v1.onnx --save_dir=pdpd_fp32_converted --paddle_type static
```

Could you please add support for this op?

**Comment by SunAhong1993** [comment]
> Hi,
> 
> Thank you for this great tool!
> 
> I tried to convert [MLPerf ResNet50 model](https://zenodo.org/record/2592612/files/resnet50_v1.onnx) (listed [here](https://github.com/mlcommons/inference/tree/master/vision/classification_and_detection#supported-models)) and get an error saying that there is missing `ArgMax` op support.
> 
> Commandline I used:
> 
> ```shell
> x2paddle --framework=onnx --model=/path/to/resnet50_v1.onnx --save_dir=pdpd_fp32_converted --paddle_type static
> ```
> 
> Could you please add support for this op?

We will support this op in this week. We will contact you after supporting.

**Comment by SunAhong1993** [comment]
We have supported the op ArgMax. You can reinstall the X2Paddle by follow:
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b onnx
cd X2Paddle
python setup.py  install
```

**Comment by arogowie-intel** [comment]
Hi @SunAhong1993 thank you very much for your quick response! I've already added support for this op by myself here: #467
