### ISSUE TITLE
Argmax op not support

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/X2Paddle#469]
onnx来源：pytorch 导出
模型类型：目标检测
![image](https://user-images.githubusercontent.com/26452514/103126943-e12b9500-46ca-11eb-8626-2338f27ed217.png)

**Comment by SunAhong1993** [comment]
> onnx来源：pytorch 导出
> 模型类型：目标检测
> ![image](https://user-images.githubusercontent.com/26452514/103126943-e12b9500-46ca-11eb-8626-2338f27ed217.png)

目前，ArgMax已经支持，您可以重装下X2Paddle，具体如下：
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by youngstu** [comment]
> > onnx来源：pytorch 导出
> > 模型类型：目标检测
> > ![image](https://user-images.githubusercontent.com/26452514/103126943-e12b9500-46ca-11eb-8626-2338f27ed217.png)
> 
> 目前，ArgMax已经支持，您可以重装下X2Paddle，具体如下：
> 
> ```
> pip uninstall x2paddle
> git clone https://github.com/PaddlePaddle/X2Paddle.git
> cd X2Paddle
> python setup.py install
> ```

已解决
