### ISSUE TITLE
利用最新的develop版本安装x2paddle，转化tf模型有误

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/X2Paddle#477]
root@NUC8i5BEH:/home/Desktop# x2paddle --framework=tensorflow --model=tangyan.pb --save_dir=model
paddle.__version__ = 2.0.0-alpha0
Now translating model from tensorflow to paddle.
Total nodes: 316
Nodes converting ...
Converting node 132 ...     Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in __init__
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 679, in MirrorPad
NameError: name 'np' is not defined

**Comment by SunAhong1993** [comment]
该问题已在PR：https://github.com/PaddlePaddle/X2Paddle/pull/478/files 中修复，您可重新安装下X2Paddle进项转换，重装方式如下：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b tf
cd X2Paddle
python setup.py install
```

**Comment by Huihuihh** [comment]
paddle.__version__ = 2.0.0-alpha0
Now translating model from tensorflow to paddle.
Total nodes: 316
Nodes converting ...
Converting node 132 ...     Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in __init__
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 691, in MirrorPad
NameError: name 'new_padding' is not defined

又有了新的问题

**Comment by SunAhong1993** [comment]
> paddle.**version** = 2.0.0-alpha0
> Now translating model from tensorflow to paddle.
> Total nodes: 316
> Nodes converting ...
> Converting node 132 ... Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 11, in
> load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in **init**
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 691, in MirrorPad
> NameError: name 'new_padding' is not defined
> 
> 又有了新的问题

已经修复，按照上述方式重装下，有问题随时联系

**Comment by Huihuihh** [comment]
> > paddle.**version** = 2.0.0-alpha0
> > Now translating model from tensorflow to paddle.
> > Total nodes: 316
> > Nodes converting ...
> > Converting node 132 ... Traceback (most recent call last):
> > File "/usr/local/bin/x2paddle", line 11, in
> > load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in **init**
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 691, in MirrorPad
> > NameError: name 'new_padding' is not defined
> > 又有了新的问题
> 
> 已经修复，按照上述方式重装下，有问题随时联系

paddle.__version__ = 2.0.0-alpha0
Now translating model from tensorflow to paddle.
Total nodes: 316
Nodes converting ...
Converting node 316 ...
Nodes converted.
dygraph_conv2d_add_fuse_pass done!
dygraph_tf_batchnorm_fuse_pass done!
dygraph_prelu_fuse_pass done!
Optimize Transpose Layers...99.66%
Transpose layers optimized, before: transpose_num=34, after: transpose_num=32
transpose_eliminate_pass done!
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 138, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 291, in gen_dygraph_model
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 551, in gen_dygraph_code
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
AttributeError: module 'paddle' has no attribute 'to_tensor'

**Comment by SunAhong1993** [comment]
> > > paddle.**version** = 2.0.0-alpha0
> > > Now translating model from tensorflow to paddle.
> > > Total nodes: 316
> > > Nodes converting ...
> > > Converting node 132 ... Traceback (most recent call last):
> > > File "/usr/local/bin/x2paddle", line 11, in
> > > load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
> > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in **init**
> > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 691, in MirrorPad
> > > NameError: name 'new_padding' is not defined
> > > 又有了新的问题
> > 
> > 
> > 已经修复，按照上述方式重装下，有问题随时联系
> 
> paddle.**version** = 2.0.0-alpha0
> Now translating model from tensorflow to paddle.
> Total nodes: 316
> Nodes converting ...
> Converting node 316 ...
> Nodes converted.
> dygraph_conv2d_add_fuse_pass done!
> dygraph_tf_batchnorm_fuse_pass done!
> dygraph_prelu_fuse_pass done!
> Optimize Transpose Layers...99.66%
> Transpose layers optimized, before: transpose_num=34, after: transpose_num=32
> transpose_eliminate_pass done!
> Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 11, in
> load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 138, in tf2paddle
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 291, in gen_dygraph_model
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 551, in gen_dygraph_code
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
> AttributeError: module 'paddle' has no attribute 'to_tensor'

请将PaddlePaddle更新至2.0.0-rc1，即可完成转换。

**Comment by Huihuihh** [comment]
> > > > paddle.**version** = 2.0.0-alpha0
> > > > Now translating model from tensorflow to paddle.
> > > > Total nodes: 316
> > > > Nodes converting ...
> > > > Converting node 132 ... Traceback (most recent call last):
> > > > File "/usr/local/bin/x2paddle", line 11, in
> > > > load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> > > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> > > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
> > > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in **init**
> > > > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 691, in MirrorPad
> > > > NameError: name 'new_padding' is not defined
> > > > 又有了新的问题
> > > 
> > > 
> > > 已经修复，按照上述方式重装下，有问题随时联系
> > 
> > 
> > paddle.**version** = 2.0.0-alpha0
> > Now translating model from tensorflow to paddle.
> > Total nodes: 316
> > Nodes converting ...
> > Converting node 316 ...
> > Nodes converted.
> > dygraph_conv2d_add_fuse_pass done!
> > dygraph_tf_batchnorm_fuse_pass done!
> > dygraph_prelu_fuse_pass done!
> > Optimize Transpose Layers...99.66%
> > Transpose layers optimized, before: transpose_num=34, after: transpose_num=32
> > transpose_eliminate_pass done!
> > Traceback (most recent call last):
> > File "/usr/local/bin/x2paddle", line 11, in
> > load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 138, in tf2paddle
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 291, in gen_dygraph_model
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 551, in gen_dygraph_code
> > File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
> > AttributeError: module 'paddle' has no attribute 'to_tensor'
> 
> 请将PaddlePaddle更新至2.0.0-rc1，即可完成转换。

paddle.__version__ = 2.0.0-rc1
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.
Total nodes: 316
Nodes converting ...
Converting node 316 ...
Nodes converted.
dygraph_conv2d_add_fuse_pass done!
dygraph_tf_batchnorm_fuse_pass done!
dygraph_prelu_fuse_pass done!
Optimize Transpose Layers...99.66%
Transpose layers optimized, before: transpose_num=34, after: transpose_num=32
transpose_eliminate_pass done!
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 138, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 291, in gen_dygraph_model
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 551, in gen_dygraph_code
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
AttributeError: module 'paddle.nn' has no attribute 'Pad4D'
