### ISSUE TITLE
tensorflow模型转化为paddle模型op不支持

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/X2Paddle#491]
paddle.__version__ = 2.0.0-rc1
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Now translating model from tensorflow to paddle.

========= 1 OPs are not supported yet ===========
========== SplitV ============
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 94, in __init__
Exception: Model is not supported yet.

模型链接：https://pan.baidu.com/s/1vIzdO7l0bDfCZ6qTz5NGDQ 
提取码：4d4b

**Comment by SunAhong1993** [comment]
这边近期添加后回复您。

**Comment by SunAhong1993** [comment]
目前，已支持该模型的转换（详见PR：https://github.com/PaddlePaddle/X2Paddle/pull/490/commits/4ed14de239427f190a0a812c0a3ff2fe601471dc ），您可重新安装X2Paddle，并进行转换，安装装方式：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b tf
cd X2Paddle
python setup.py install
```

**Comment by Huihuihh** [comment]
> 目前，已支持该模型的转换（详见PR：[4ed14de](https://github.com/PaddlePaddle/X2Paddle/commit/4ed14de239427f190a0a812c0a3ff2fe601471dc) ），您可重新安装X2Paddle，并进行转换，安装装方式：
> 
> ```
> pip uninstall x2paddle
> git clone https://github.com/SunAhong1993/X2Paddle.git -b tf
> cd X2Paddle
> python setup.py install
> ```

是的，可以成功转换了。不过转换成paddlelite的模型还不行。
```
Error: This model is not supported, because 3 ops are not supported on 'arm'. These unsupported ops are: 'nearest_interp_v2, pad, tile'.
```

**Comment by SunAhong1993** [comment]
> > 目前，已支持该模型的转换（详见PR：[4ed14de](https://github.com/PaddlePaddle/X2Paddle/commit/4ed14de239427f190a0a812c0a3ff2fe601471dc) ），您可重新安装X2Paddle，并进行转换，安装装方式：
> > ```
> > pip uninstall x2paddle
> > git clone https://github.com/SunAhong1993/X2Paddle.git -b tf
> > cd X2Paddle
> > python setup.py install
> > ```
> 
> 是的，可以成功转换了。不过转换成paddlelite的模型还不行。
> 
> ```
> Error: This model is not supported, because 3 ops are not supported on 'arm'. These unsupported ops are: 'nearest_interp_v2, pad, tile'.
> ```
这个问题你可以到PaddleLite的repo提一个issue，那边同学会给您解答。

**Comment by Huihuihh** [comment]
> > > 目前，已支持该模型的转换（详见PR：[4ed14de](https://github.com/PaddlePaddle/X2Paddle/commit/4ed14de239427f190a0a812c0a3ff2fe601471dc) ），您可重新安装X2Paddle，并进行转换，安装装方式：
> > > ```
> > > pip uninstall x2paddle
> > > git clone https://github.com/SunAhong1993/X2Paddle.git -b tf
> > > cd X2Paddle
> > > python setup.py install
> > > ```
> > 
> > 
> > 是的，可以成功转换了。不过转换成paddlelite的模型还不行。
> > ```
> > Error: This model is not supported, because 3 ops are not supported on 'arm'. These unsupported ops are: 'nearest_interp_v2, pad, tile'.
> > ```
> 
> 这个问题你可以到PaddleLite的repo提一个isuue，那边同学会给您解答。

好的，麻烦了。这个问题我先关闭了
