### ISSUE TITLE
Tensorflow inceptionv3转Paddle，报错KeyError

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/X2Paddle#508]
hi，我使用**master**分支的教程
[https://github.com/PaddlePaddle/X2Paddle/blob/master/tensorflow2fluid/vgg_translate_tutorial.ipynb](url)

将tensorflow checkpoint模型转为paddle，但是报错
`Traceback (most recent call last):
  File "./convert_to_paddle_inceptionv3.py", line 22, in <module>
    convert.run(parser)
  File "../tf2fluid/convert.py", line 129, in run
    args.in_nodes, input_format)
  File "../tf2fluid/tensorflow_parser.py", line 72, in __init__
    self.tf_graph.build(input_format)
  File "../tf2fluid/tensorflow_graph.py", line 114, in build
    super(TensorflowGraph, self).build(input_format)
  File "../tf2fluid/graph.py", line 53, in build
    self._gen_newname_for_nodes()
  File "../tf2fluid/graph.py", line 85, in _gen_newname_for_nodes
    ref_name = self.name_generator.get_name(node)
  File "../tf2fluid/utils.py", line 48, in get_name
    ref_name = self.names[node.layer.input[0]]
KeyError: u'InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/cond/Switch:1'`

我打印报错位置 tensorflow2fluid/tf2fluid/utils.py 中 44行
`elif op_name.lower() == "identity":
    print("========")
    print(self.names)
    print("========")
    ref_name = self.names[node.layer.input[0]]`
确实没有找到`Switch:1`

我的模型是在tf slim版本的inceptionv3的基础上增加了fc层，并且使用双塔结构和rank loss，我怀疑是双塔的问题。
我打印出了tensor，出问题的tensor是这样的
`(<tf.Tensor 'InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/cond/Switch:0' shape=() dtype=bool>, <tf.Tensor 'InceptionV3/InceptionV3/Conv2d_1a_3x3/      BatchNorm/cond/Switch:1' shape=() dtype=bool>)`

模型链接: [https://pan.baidu.com/s/1pT-8BNHfOaQdYHj2CVZB6g](url) 提取码: fbs8

可如流联系。

**UPDATE**
尝试了一下使用**develop**分支。
先使用如下教程将上述checkpoint转为.pb
[https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/user_guides/export_tf_model.md](url)
再使用如下教程转paddle
[https://github.com/PaddlePaddle/X2Paddle](url)
报错如下，
```
  File "x2paddle/convert_tf.py", line 269, in <module>
    main()
  File "x2paddle/convert_tf.py", line 251, in main
    define_input_shape, args.paddle_type)
  File "x2paddle/convert_tf.py", line 114, in tf2paddle
    mapper = TFOpMapper(model)
  File "/home/ecom/liuxiang12/env/python_tf_paddle/lib/python2.7/site-packages/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 128, in __init__
    func(node)
  File "/home/ecom/liuxiang12/env/python_tf_paddle/lib/python2.7/site-packages/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 197, in Placeholder
    node.layer_name)
AssertionError: Unknown shape of input nodes[Placeholder_3].
```
Placeholder_3是
`is_training (<tf.Tensor 'Placeholder_3:0' shape=() dtype=bool>,)`
convert_tf.py即为convert.py

**Comment by SunAhong1993** [comment]
> 模型链接: [https://pan.baidu.com/s/1pT-8BNHfOaQdYHj2CVZB6g](url) 提取码: fbs8

好的，这边查看下是什么原因再回复您

**Comment by p1n0cch10** [comment]
> > 模型链接: [https://pan.baidu.com/s/1pT-8BNHfOaQdYHj2CVZB6g](url) 提取码: fbs8
> 
> 好的，这边查看下是什么原因再回复您

请问可以如流联系吗，比较着急。

**Comment by SunAhong1993** [comment]
> > > 模型链接: [https://pan.baidu.com/s/1pT-8BNHfOaQdYHj2CVZB6g](url) 提取码: fbs8
> > 
> > 
> > 好的，这边查看下是什么原因再回复您
> 
> 请问可以如流联系吗，比较着急。

可以的，要不你先使用develop分支尝试下，这是我们最新代码

**Comment by p1n0cch10** [comment]
> > > > 模型链接: [https://pan.baidu.com/s/1pT-8BNHfOaQdYHj2CVZB6g](url) 提取码: fbs8
> > > 
> > > 
> > > 好的，这边查看下是什么原因再回复您
> > 
> > 
> > 请问可以如流联系吗，比较着急。
> 
> 可以的，要不你先使用develop分支尝试下，这是我们最新代码
我在develop分支试了，已经更新到原post，请问如流号是？

**Comment by p1n0cch10** [comment]
> > > > 模型链接: [https://pan.baidu.com/s/1pT-8BNHfOaQdYHj2CVZB6g](url) 提取码: fbs8
> > > 
> > > 
> > > 好的，这边查看下是什么原因再回复您
> > 
> > 
> > 请问可以如流联系吗，比较着急。
> 
> 可以的，要不你先使用develop分支尝试下，这是我们最新代码

我在develop试了，已经更新到原始posts了，请问如流号是？
