### ISSUE TITLE
self.params[node.layer_name + "_cparam2"] = np.squeeze(node.data[ IndexError: list index out of range

### ISSUE THREAD

**Issue by edmundang1994** [PaddlePaddle/X2Paddle#512]
Hi, I have been trying to convert caffe > paddle, however, I keep facing the issue of Indexerror: list index out of range on the file caffe_op_mapper.py. Please help!!

![image](https://user-images.githubusercontent.com/36850212/108604415-c46cbe80-73e8-11eb-89d0-9e830193cb29.png)

The caffe model that I am using, with the prototxt as attached.
[caffemodel.zip](https://github.com/PaddlePaddle/X2Paddle/files/6015926/caffemodel.zip)

**Comment by SunAhong1993** [comment]
You can try reinstall the X2Paddle as follow command：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```
And run as : 
```x2paddle -f caffe -p deploy.prototxt -w baidu_iter_250000.caffemodel -s pd_model_dygraph -pt dygraph```
If this is useful, we willl  update the static method.

**Comment by edmundang1994** [comment]
Yes! Thanks alot! It work like magic!
