### ISSUE TITLE
x2paddle从onnx模型转paddle异常（yolo 目标检测）

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/X2Paddle#515]
![image](https://user-images.githubusercontent.com/26452514/109424440-91e14800-7a1e-11eb-8b8b-d29a6002f0f7.png)
![image](https://user-images.githubusercontent.com/26452514/109424446-9a398300-7a1e-11eb-924f-9955fd2d9162.png)

x2paddle从onnx转paddle后结构中多了几个transpose op导致输出结果顺序混乱，无法和onnx输出对齐。

**Comment by SunAhong1993** [comment]
方便提供下模型到545510262@qq.com吗

**Comment by youngstu** [comment]
> 方便提供下模型到[545510262@qq.com](mailto:545510262@qq.com)吗

我能在如流上（飞桨预测服务群）联系您吗？

**Comment by youngstu** [comment]
> > 方便提供下模型到[545510262@qq.com](mailto:545510262@qq.com)吗
> 
> 我能在如流上（飞桨预测服务群）联系您吗？

信息已经发到群里面了，直接如流沟通方便些~
