### ISSUE TITLE
转tf模型时报错：'utf-8' codec can't decode byte 0xb9 in position 3437: invalid start byte

### ISSUE THREAD

**Issue by Zyq990127** [PaddlePaddle/X2Paddle#517]
‘’‘
模型来源： TensorFlow
模型说明：图像分类模型https://github.com/tensorflow/models/tree/master/research/slim
                  下载的MobileNet_v2预训练模型
模型文件：https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz
转换过程出错提示如下：'utf-8' codec can't decode byte 0xb9 in position 3437: invalid start byte
![图片](https://user-images.githubusercontent.com/73383216/109450736-a1947700-7a86-11eb-8813-6d8b2a76bbcf.png)

```
环境：
win10 anaconda
paddlepaddle-2.0.0rc1-cp37-cp37m-win_amd64.whl
x2paddle-1.0.0rc0
paddlelite-2.8rc0
tensorflow1.14.0

```

**Comment by SunAhong1993** [comment]
该问题已修复，您可重装X2Paddle进行使用，重装方式：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by Zyq990127** [comment]
重装之后还是报错：'utf-8' codec can't decode byte 0xa3 in position 1718: invalid start byte

就是换了一个字符

**Comment by Zyq990127** [comment]
重装之后还是报错：'utf-8' codec can't decode byte 0xa3 in position 1718: invalid start byte
![图片](https://user-images.githubusercontent.com/73383216/109932749-9307c300-7d05-11eb-9b6f-75d797bd830d.png)

**Comment by SunAhong1993** [comment]
> 重装之后还是报错：'utf-8' codec can't decode byte 0xa3 in position 1718: invalid start byte
> ![图片](https://user-images.githubusercontent.com/73383216/109932749-9307c300-7d05-11eb-9b6f-75d797bd830d.png)

你可以截图看下x2paddle_code.py的248行主要是什么吗？

**Comment by Zyq990127** [comment]
这个文件的第248行是：


看起来是参数文件有什么问题。。。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/X2Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午4:34
收件人:&nbsp;"PaddlePaddle/X2Paddle"<X2Paddle@noreply.github.com&gt;;
抄送:&nbsp;"976415080"<976415080@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/X2Paddle] 转tf模型时报错：'utf-8' codec can't decode byte 0xb9 in position 3437: invalid start byte (#517)





  
重装之后还是报错：'utf-8' codec can't decode byte 0xa3 in position 1718: invalid start byte
 
  
你可以截图看下x2paddle_code.py的248行主要是什么吗？

**Comment by SunAhong1993** [comment]
248行是空行？

**Comment by Zyq990127** [comment]
不是啊，图片是没加载出来吗


248行：params = paddle.load('D:\pythontest\garbage_classify\models\pb\pd_model/model.pbparams')






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/X2Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午4:59
收件人:&nbsp;"PaddlePaddle/X2Paddle"<X2Paddle@noreply.github.com&gt;;
抄送:&nbsp;"976415080"<976415080@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/X2Paddle] 转tf模型时报错：'utf-8' codec can't decode byte 0xb9 in position 3437: invalid start byte (#517)





 
248行是空行？

**Comment by SunAhong1993** [comment]
> 不是啊，图片是没加载出来吗 248行：params = paddle.load('D:\pythontest\garbage_classify\models\pb\pd_model/model.pbparams')
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/X2Paddle" <notifications@github.com&gt;; 发送时间:&nbsp;2021年3月4日(星期四) 下午4:59 收件人:&nbsp;"PaddlePaddle/X2Paddle"<X2Paddle@noreply.github.com&gt;; 抄送:&nbsp;"976415080"<976415080@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/X2Paddle] 转tf模型时报错：'utf-8' codec can't decode byte 0xb9 in position 3437: invalid start byte (#517) 248行是空行？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是由于Windows上路径字符串的问题，已修复，请按照前面的方式进行重装X2Paddle。

**Comment by Zyq990127** [comment]
![图片](https://user-images.githubusercontent.com/73383216/109947774-a8381e00-7d14-11eb-8063-716db2727edf.png)
![图片](https://user-images.githubusercontent.com/73383216/109947844-bab25780-7d14-11eb-9a09-addfc24f7665.png)

**Comment by Zyq990127** [comment]
![图片](https://user-images.githubusercontent.com/73383216/109948063-edf4e680-7d14-11eb-94fe-bcd718657003.png)
![图片](https://user-images.githubusercontent.com/73383216/109948142-ff3df300-7d14-11eb-825f-304b152a4a26.png)
重装之后依然报错

**Comment by SunAhong1993** [comment]
突然发现你报的一只是一个warning，不影响转换，你看下inference_model下应该已经文件了（说明转换成功）。

**Comment by Zyq990127** [comment]
inference_model文件夹下是空的



------------------&nbsp;原始邮件&nbsp;------------------







 
突然发现你报的一只是一个warning，不影响转换，你看下inference_model下应该已经文件了（说明转换成功）。

**Comment by SunAhong1993** [comment]
> inference_model文件夹下是空的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 突然发现你报的一只是一个warning，不影响转换，你看下inference_model下应该已经文件了（说明转换成功）。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那D盘下
![image](https://user-images.githubusercontent.com/48579383/110068077-e59db980-7daf-11eb-9fad-e4ed10e5c21b.png)
该文件是否存在？

**Comment by Zyq990127** [comment]
![图片](https://user-images.githubusercontent.com/73383216/110068708-395cd280-7db1-11eb-92f3-db80e00be277.png)
![图片](https://user-images.githubusercontent.com/73383216/110068749-4e396600-7db1-11eb-85eb-7159ffef0b84.png)
model.pbparams文件存在，inference_model文件夹下是空的

**Comment by SunAhong1993** [comment]
为什么你的路径下有个ave_dir？是什么意思？

**Comment by Zyq990127** [comment]
我也不知道为什么有，删掉重新运行一次就没了
![图片](https://user-images.githubusercontent.com/73383216/110197440-a1311d00-7e86-11eb-98d4-cc91ca6a6211.png)
![图片](https://user-images.githubusercontent.com/73383216/110197467-aa21ee80-7e86-11eb-8a40-35d61b89ec37.png)

**Comment by Zyq990127** [comment]
我换了ubuntu操作系统成功转换了，是因为操作系统的问题吗

**Comment by Zyq990127** [comment]
换了ubuntu系统后的输出为：
![图片](https://user-images.githubusercontent.com/73383216/110234215-2fc79c00-7f64-11eb-8996-bce959d666d0.png)
![图片](https://user-images.githubusercontent.com/73383216/110234226-3b1ac780-7f64-11eb-975d-f8068a41c90e.png)
![图片](https://user-images.githubusercontent.com/73383216/110234241-453cc600-7f64-11eb-8920-ffdf02d9ba36.png)
这个转化结果对吗，我怎么觉得inference_model下面不应该是
![图片](https://user-images.githubusercontent.com/73383216/110234259-62719480-7f64-11eb-86fe-e7e5b42f2b72.png)
这样的吗？
我想再转成paddlelite文件但是报错说没有_model_文件

**Comment by Zyq990127** [comment]
model.pdiparams文件是所有参数信息保存在单个文件params中？
model.pdmodel文件是模型的拓扑信息吗？求解，麻烦啦
换了这个命令之后paddle_lite_opt --model_file=model.pdmodel --param_file=model.pdiparams --optimize_out_type=naive_buffer --optimize_out=out --valid_targets=arm
nb文件转换出来了

**Comment by Zyq990127** [comment]
model.pdiparams文件是所有参数信息保存在单个文件params中？
model.pdmodel文件是模型的拓扑信息吗？
换了这个命令之后paddle_lite_opt --model_file=model.pdmodel --param_file=model.pdiparams --optimize_out_type=naive_buffer --optimize_out=out --valid_targets=arm
nb文件转换出来了，但是还是担心自己理解的不对，求解答，麻烦啦！

**Comment by SunAhong1993** [comment]
> model.pdmodel文件是模型的拓扑信息吗？

你这样使用是没问题的，model.pdmodel对应__model__，model.pdiparams对应__params__
