### ISSUE TITLE
onnx2paddle keyerror 0

### ISSUE THREAD

**Issue by wzzwh110** [PaddlePaddle/X2Paddle#528]
模型来源： MMdetection
模型说明： 目标检测模型
我在windows下pip install onnx==1.6.0出了以下问题
‘’‘
assert CMAKE, 'Could not find "cmake" executable!'     AssertionError: Could not find "cmake" execut
’‘’
我直接使用pip install onnx 解决了
但是在转换过程出错提示如下：
```
paddle.__version__ = 2.0.1
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
shape inferencing ...
D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
[WARNING] Incomplete symbolic shape inference
shape inferenced.
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddle\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 264, in main
  File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 171, in onnx2paddle
  File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 420, in __init__
  File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 183, in __init__
  File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 381, in collect_value_infos
KeyError: 0
```
请问如何解决

**Comment by SunAhong1993** [comment]
> 模型来源： MMdetection
> 模型说明： 目标检测模型
> 我在windows下pip install onnx==1.6.0出了以下问题
> ‘’‘
> assert CMAKE, 'Could not find "cmake" executable!' AssertionError: Could not find "cmake" execut
> ’‘’
> 我直接使用pip install onnx 解决了
> 但是在转换过程出错提示如下：
> 
> ```
> paddle.__version__ = 2.0.1
> Now translating model from onnx to paddle.
> model ir_version: 6, op version: 11
> shape inferencing ...
> D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
> [WARNING] Incomplete symbolic shape inference
> shape inferenced.
> Traceback (most recent call last):
>   File "D:\anaconda3\envs\paddle\Scripts\x2paddle-script.py", line 33, in <module>
>     sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
>   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 264, in main
>   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 171, in onnx2paddle
>   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 420, in __init__
>   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 183, in __init__
>   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 381, in collect_value_infos
> KeyError: 0
> ```
> 
> 请问如何解决

方便把onnx模型发送到sunyanfang01@baidu.com吗

**Comment by wzzwh110** [comment]
wzzwh110 issue


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/X2Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/X2Paddle] onnx2paddle keyerror 0 (#528)





  
模型来源： MMdetection
 模型说明： 目标检测模型
 我在windows下pip install onnx==1.6.0出了以下问题
 ‘’‘
 assert CMAKE, 'Could not find "cmake" executable!' AssertionError: Could not find "cmake" execut
 ’‘’
 我直接使用pip install onnx 解决了
 但是在转换过程出错提示如下：
 paddle.__version__ = 2.0.1 Now translating model from onnx to paddle. model ir_version: 6, op version: 11 shape inferencing ... D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead [WARNING] Incomplete symbolic shape inference shape inferenced. Traceback (most recent call last):   File "D:\anaconda3\envs\paddle\Scripts\x2paddle-script.py", line 33, in <module&gt;     sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 264, in main   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 171, in onnx2paddle   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 420, in __init__   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 183, in __init__   File "D:\anaconda3\envs\paddle\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\decoder\onnx_decoder.py", line 381, in collect_value_infos KeyError: 0  
请问如何解决
  
***@***.***吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

tmp.onnx (488.41M, 2021年04月18日 10:10 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0d6339352e471bd64e112e554032501803015f51575406541d56080d071f56065605140d5307041a525b010c0205500053015a02663a62435d13175a085c1a370d&code=0c95f2b7

**Comment by wzzwh110** [comment]
已发送

**Comment by SunAhong1993** [comment]
> 已发送

已收到，近期查看原因后，回复您

**Comment by SunAhong1993** [comment]
这个onnx本身有问题，这边使用如下代码跑onnx前向，会报如下错误：
```
import onnxruntime as rt
import os
import numpy as np
import sys
import pickle
 
model_dir = 'tmp.onnx'
 
sess = rt.InferenceSession(model_dir)
 
inputs_dict = {}
np.random.seed(6)
input_0 = np.random.rand(1, 3, 1024,1024).astype('float32')
np.save('./input.npy', input_0)
print(input_0.shape)
 
inputs_dict[sess.get_inputs()[0].name] = input_0
 
import time
repeats =  1
for i in range(repeats):
    out1, out2 = sess.run(None, input_feed=inputs_dict)
print(out1)
```
![image](https://user-images.githubusercontent.com/48579383/112433598-72b7ab00-8d7d-11eb-97a2-7b9a7e45483b.png)
你那边可以先查看下onnx的问题。

**Comment by wzzwh110** [comment]
> 这个onnx本身有问题，这边使用如下代码跑onnx前向，会报如下错误：
> 
> ```
> import onnxruntime as rt
> import os
> import numpy as np
> import sys
> import pickle
>  
> model_dir = 'tmp.onnx'
>  
> sess = rt.InferenceSession(model_dir)
>  
> inputs_dict = {}
> np.random.seed(6)
> input_0 = np.random.rand(1, 3, 1024,1024).astype('float32')
> np.save('./input.npy', input_0)
> print(input_0.shape)
>  
> inputs_dict[sess.get_inputs()[0].name] = input_0
>  
> import time
> repeats =  1
> for i in range(repeats):
>     out1, out2 = sess.run(None, input_feed=inputs_dict)
> print(out1)
> ```
> 
> ![图像](https://user-images.githubusercontent.com/48579383/112433598-72b7ab00-8d7d-11eb-97a2-7b9a7e45483b.png)
> 你那边可以先查看下onnx的问题。

好的我查看一下 谢谢了
