### ISSUE TITLE
tensorflow2fluid转出的模型Inference时间不正常

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/X2Paddle#53]
tensorflow2fluid将VGG16转成paddle格式，如实例代码。
转出的模型如下：
![image](https://user-images.githubusercontent.com/7035538/61929302-94abc980-afad-11e9-8d4e-1b8f8a357217.png)

按照示例的Inference代码进行ml.ModelLoader后，分别进行100次Inference。
GPU：
![image](https://user-images.githubusercontent.com/7035538/61929626-008e3200-afae-11e9-9dc6-1ce42f0584fd.png)

CPU：
![image](https://user-images.githubusercontent.com/7035538/61929590-f8ce8d80-afad-11e9-8e53-87b95875ce0f.png)

@jiangjiajun   @SunAhong1993  你们看一下是不是有这个问题，这Inference时间不正常。

**Comment by jiangjiajun** [comment]
Inference时间不正常具体是指什么问题呢，是说与其它框架的inference时间对比？

此外可以尝试将模型进行序列化保存（在tensorflow2fluid的ReadMe中有提到），会对图进行裁剪，仅保存需要的子图，之后再使用相应接口加载预测，参考[load_infenrece_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_guides/low_level/inference.html#api-guide-inference)的使用

**Comment by A1exy** [comment]
@jiangjiajun   嗯嗯，我的意思是和我在Tensorflow下做的模型直接调用Inference的时间差太多，caffe2paddle转出的模型与直接调用caffe模型的inference时间差距不太大，还正常。tensorflow2paddle转出的模型GPU下300ms一张224*224*3的图片，应该有问题，Inference的代码是基于官方提供的代码修改的，我先再看看。

**Comment by jiangjiajun** [comment]
> @jiangjiajun 嗯嗯，我的意思是和我在Tensorflow下做的模型直接调用Inference的时间差太多，caffe2paddle转出的模型与直接调用caffe模型的inference时间差距不太大，还正常。tensorflow2paddle转出的模型GPU下29ms一张224_224_3的图片，应该有问题，Inference的代码是基于官方提供的代码修改的，我先再看看。

由于TensorFlow模型中的OP粒度较细，且与PaddleOP对应关系并不像Caffe那么直接，所以转换至Paddle是会有性能的损失，我们也正在尝试解决这个问题

**Comment by A1exy** [comment]
@jiangjiajun    好的，了解

**Comment by jiangjiajun** [comment]
> @jiangjiajun 嗯嗯，我的意思是和我在Tensorflow下做的模型直接调用Inference的时间差太多，caffe2paddle转出的模型与直接调用caffe模型的inference时间差距不太大，还正常。tensorflow2paddle转出的模型GPU下29ms一张224_224_3的图片，应该有问题，Inference的代码是基于官方提供的代码修改的，我先再看看。

此外在CPU上预测时，tensorflow默认是多线程模式，我这边测试在预测时，CPU利用率会达到1500%更多，而Paddle默认是单线程，所以差异会很大。
