### ISSUE TITLE
【论文复现营】报错No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/X2Paddle#589]
# 问题
论文复现的时候，出现报错信息：
 File "/Users/skywalk/github/big_transfer/paddle/train.py", line 2, in <module>
    from x2paddle import torch2paddle
  File "/Users/skywalk/py38/lib/python3.8/site-packages/x2paddle-1.2.0-py3.8.egg/x2paddle/__init__.py", line 3, in <module>
    from .core.program import PaddleGraph
  File "/Users/skywalk/py38/lib/python3.8/site-packages/x2paddle-1.2.0-py3.8.egg/x2paddle/core/program.py", line 19, in <module>
    from paddle.fluid.proto import framework_pb2
ModuleNotFoundError: No module named 'paddle.fluid'

使用的版本：x2paddle 1.2.0
Name: paddlepaddle Version: 2.0.2

不明白为什么2.x版本会出来fluid的代码。

**Comment by SunAhong1993** [comment]
> # 问题
> 论文复现的时候，出现报错信息：
> File "/Users/skywalk/github/big_transfer/paddle/train.py", line 2, in
> from x2paddle import torch2paddle
> File "/Users/skywalk/py38/lib/python3.8/site-packages/x2paddle-1.2.0-py3.8.egg/x2paddle/**init**.py", line 3, in
> from .core.program import PaddleGraph
> File "/Users/skywalk/py38/lib/python3.8/site-packages/x2paddle-1.2.0-py3.8.egg/x2paddle/core/program.py", line 19, in
> from paddle.fluid.proto import framework_pb2
> ModuleNotFoundError: No module named 'paddle.fluid'
> 
> 使用的版本：x2paddle 1.2.0
> Name: paddlepaddle Version: 2.0.2
> 
> 不明白为什么2.x版本会出来fluid的代码。

部分fluid API在2.X中还是可以使用的，该API适用于保存静态图参数时使用的，您可以查看下paddlepaddle是否安装成功，查看方式如下：  
使用 python 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()，
如果出现PaddlePaddle is installed successfully!，说明您已成功安装。

**Comment by skywalk163** [comment]
非常感谢，原来是误创建了一个 名字叫paddle的目录，犯了低级错误。
