### ISSUE TITLE
【论文复现营】x2paddle转换的torch模型与torch模型输出形状及内容均不同，但无报错

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/X2Paddle#594]
模型来源： Pytorch
模型说明： 图像分类模型，其相应repo为[https://github.com/facebookresearch/deit](https://github.com/facebookresearch/deit)
相关文件： github：[https://github.com/geoyee/PaddleTr/tree/main/x2paddle](https://github.com/geoyee/PaddleTr/tree/main/x2paddle)
文件说明：在deit下是pytorch的整个文件，通过torch2paddle.py加载了torch的模型和参数进行转换。pd_model_trace下保存着转换得到的模型参数，两个test.py分别对应torch和paddle使用该模型及参数得到的结果。
说明：转换过程未有出错提示，输出的结果和形状都不相同
控制台输出：
```
['1', '8', '1+cpu']
Now translating model from pytorch to paddle.
Model optimizing ...
Model optimized.
Exporting inference model from python code ('E:\dataFiles\github\PaddleTr\x2paddle\pd_model_trace\x2paddle_code.py')...

W0519 19:49:49.956825 16080 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0519 19:49:49.963822 16080 device_context.cc:330] device: 0, cuDNN Version: 7.6.
```
输出形状：
pytorch：`torch.Size([1, 1000])`
x2paddle：`[1, 197, 1000]`

**Comment by SunAhong1993** [comment]
我们将查看下原因，查看后回复您。

**Comment by geoyee** [comment]
> 我们将查看下原因，查看后回复您。

好的，非常感谢

**Comment by SunAhong1993** [comment]
已修复该问题，可通过下述方式进行重装：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b pt_pro
cd X2Paddle
python setup.py install
```

**Comment by geoyee** [comment]
> 已修复该问题，可通过下述方式进行重装：
> 
> ```
> pip uninstall x2paddle
> git clone https://github.com/SunAhong1993/X2Paddle.git -b pt_pro
> cd X2Paddle
> python setup.py install
> ```

收到，感谢，现在进行尝试，待问题解决我再回来告知！

**Comment by geoyee** [comment]
感谢！形状问题已解决。
