### ISSUE TITLE
【论文复现营】精度对齐中发现torch2paddle.zeros_init_并没有将参数设置为0

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/X2Paddle#620]
bigtransfor论文复现中，发现head处精度无法对齐，相关代码为：
torch代码：
`      if self.zero_head:
        nn.init.zeros_(self.head4.conv.weight)
        nn.init.zeros_(self.head4.conv.bias)`
对应的飞桨代码：
`            if self.zero_head:
                zeros_init_(self.head4.conv.weight)
                zeros_init_(self.head4.conv.bias)
`
经对比，发现飞桨这里并没有把self.head4.conv.weight 设置为0 ，
查找源代码，发现zeros_init_代码为：

Signature: torch2paddle.zeros_init_(param)
Docstring: <no docstring>
Source:   
def zeros_init_(param):
    replaced_param = paddle.create_parameter(
        shape=param.shape,
        dtype=param.dtype,
        default_initializer=paddle.nn.initializer.Assign(
            paddle.zeros(param.shape, param.dtype)))
    paddle.assign(param, replaced_param)
File:      ~/an3/lib/python3.8/site-packages/x2paddle/project_convertor/pytorch/torch2paddle/nn_init.py
Type:      function

通过查看飞桨手册，发现paddle.assign(param, replaced_param)这句用反了，导致 torch2paddle.zeros_init_没有按照预想的将参数设置为0 

assign API手册如下：
`paddle.assign(x, output=None)[源代码]
该OP将输入Tensor或numpy数组拷贝至输出Tensor。
参数：
x (Tensor|np.ndarray|list|tuple|scalar) - 输入Tensor，或numpy数组，或由基本数据组成的list/tuple，或基本数据，支持数据类型为float32, float64, int32, int64和bool。注意：由于当前框架的protobuf传输数据限制，float64数据会被转化为float32数据。

output (Tensor，可选) - 输出Tensor。如果为None，则创建一个新的Tensor作为输出Tensor，默认值为None。

返回：输出Tensor，形状、数据类型、数据值和 x 一致。
`

**Comment by SunAhong1993** [comment]
感谢建议，已提PR修复。
