### ISSUE TITLE
LRN精度问题

### ISSUE THREAD

**Issue by ltcs11** [PaddlePaddle/X2Paddle#628]
模型来源： ONNX model zoo
模型说明： --
模型文件： https://github.com/onnx/models/tree/master/vision/classification/alexnet

转换之后出现精度误差，部分分类Top1均存在偏差

paddle更新2.0+之后，适配了LRN，与X2paddle自定义方式类似
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/LocalResponseNorm_cn.html#localresponsenorm

实际替换opset.py的
"custom_layer:LocalResponseNorm" -> "paddle.nn.LocalResponseNorm"
精度回复正常

**Comment by wjj19950828** [comment]
感谢您的建议，已经对代码进行了修改
