### ISSUE TITLE
【论文复现营】没有这句就报错：from x2paddle import torch2paddle

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/X2Paddle#660]
在完成代码转换工作的时候，发现有时候已经将x2paddle的代码全部替换掉了，但是如果没有这句：from x2paddle import torch2paddle

程序还是会报错，加上就能执行成功。

比如完成的这段代码：

            from x2paddle import torch2paddle
            import paddle

            def max(input, dim_other=None, keepdim=False, *, out=None):
                if dim_other is None:
                    return paddle.max(input)
                elif isinstance(dim_other, paddle.Tensor):
                    return paddle.maximum(input, dim_other)
                else:
                    return paddle.max(input, axis=dim_other, keepdim=keepdim)

            # def mean(input, dim=None, keepdim=False, *, out=None):
            #     if dim is None:
            #         warnings.warn('The output of paddle.mean is not scalar!')
            #         return paddle.mean(input)
            #     else:
            #         return paddle.mean(input, axis=dim, keepdim=keepdim)

            def min(input, dim_other=None, keepdim=False, *, out=None):
                if dim_other is None:
                    return paddle.min(input)
                elif isinstance(dim_other, paddle.Tensor):
                    return paddle.minimum(input, dim_other)
                else:
                    return paddle.min(input, axis=dim_other, keepdim=keepdim)

            def giou_p(bboxes1, bboxes2, eps=1e-06):
                """Calculate overlap between two set of bboxes.
                Note:

                calculate the GIoU between each aligned pair of bboxes1 and bboxes2.
                Args:
                    bboxes1 (Tensor): shape (m, 4) in <x1, y1, x2, y2> format or empty.
                    bboxes2 (Tensor): shape (m, 4) in <x1, y1, x2, y2> format or empty.
                    eps (float, optional): A value added to the denominator for numerical
                        stability. Default 1e-6.
                Returns:
                    Tensor: shape (m, )
                Example:
                    >>> bboxes1 = torch.FloatTensor([
                    >>>     [0., 0., 10., 10.],
                    >>>     [10., 10., 20., 20.],
                    >>>     [32., 32., 38., 42.],
                    >>> ])
                    >>> bboxes2 = torch.FloatTensor([
                    >>>     [0., 0., 10., 20.],
                    >>>     [0., 10., 10., 19.],
                    >>>     [10., 10., 20., 20.],
                    >>> ])
                    >>> overlaps = giou(bboxes1, bboxes2)
                    >>> assert overlaps.shape == (3, 3)
                    >>> overlaps = bbox_overlaps(bboxes1, bboxes2)
                    >>> assert overlaps.shape == (3, )
                """
                # bboxes1 = torch2paddle.create_float32_tensor(bboxes1)
                # bboxes2 = torch2paddle.create_float32_tensor(bboxes2)
                # bboxes11 =paddle.to_tensor(bboxes1)
                # bboxes22 =paddle.to_tensor(bboxes2)

                rows = bboxes1.size(-2)
                cols = bboxes2.size(-2)
                # print(rows)
                assert rows == cols
                area1 = (bboxes1[:, 2] - bboxes1[:, 0]) * (bboxes1[:, 3] - bboxes1[:, 1])
                area2 = (bboxes2[:, 2] - bboxes2[:, 0]) * (bboxes2[:, 3] - bboxes2[:, 1])
                # lt = torch2paddle.max(bboxes1[:, :2], bboxes2[:, :2])
                # rb = torch2paddle.min(bboxes1[:, 2:], bboxes2[:, 2:])
                lt = max(bboxes1[:, :2], bboxes2[:, :2])
                rb = min(bboxes1[:, 2:], bboxes2[:, 2:])
                # wh = (rb - lt).clamp(min=0, max=None)
                wh = (rb - lt).clip(min=0, max=None)
                overlap = wh[:, 0] * wh[:, 1]
                union = area1 + area2 - overlap
                # enclosed_lt = torch2paddle.min(bboxes1[:, :2], bboxes2[:, :2])
                # enclosed_rb = torch2paddle.max(bboxes1[:, 2:], bboxes2[:, 2:])
                enclosed_lt = min(bboxes1[:, :2], bboxes2[:, :2])
                enclosed_rb = max(bboxes1[:, 2:], bboxes2[:, 2:])
                # eps = union.new_tensor([eps])
                eps = union
                # union = torch2paddle.max(union, eps)
                union = max(union, eps)
                ious = overlap / union
                enclose_wh = (enclosed_rb - enclosed_lt).clip(min=0, max=None)
                enclose_area = enclose_wh[:, 0] * enclose_wh[:, 1]
                # enclose_area = torch2paddle.max(enclose_area, eps)
                enclose_area = max(enclose_area, eps)
                gious = ious - (enclose_area - union) / enclose_area
                return gious.numpy()

            bboxes1 = [[0.0, 0.0, 10.0, 10.0], [10.0, 10.0, 20.0, 20.0], [32.0, 32.0, 
                38.0, 42.0]]
            bboxes2 = [[0.0, 0.0, 10.0, 10.0], [0.0, 10.0, 10.0, 19.0], [10.0, 10.0, 
                20.0, 20.0]]
            paddle_bboxes1 = paddle.to_tensor(bboxes1)
            # # print(paddle_bboxes1)
            paddle_bboxes2 = paddle.to_tensor(bboxes2)
            paddle_overlaps = giou_p(paddle_bboxes1, paddle_bboxes2)
            print(paddle_overlaps)

加了不报错，不加就报错：
  File "giou_paddle.py", line 62, in giou_p
    rows = bboxes1.size(-2)
TypeError: 'numpy.int64' object is not callable

**Comment by jiangjiajun** [comment]
Hi, @skywalk163 当前看起来是`bboxes1`这个变量的类型发生了变化，你可以在import和不import的情况下，输出这个bboxes1的type和值，观察下有什么变化

**Comment by skywalk163** [comment]
两种情况输出类型和值一样的。
在import的情况下：
`====== <class 'paddle.Tensor'> Tensor(shape=[3, 4], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[0. , 0. , 10., 10.],
        [10., 10., 20., 20.],
        [32., 32., 38., 42.]])
`

在不import的情况下，带上报错信息：
`====== <class 'paddle.Tensor'> Tensor(shape=[3, 4], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[0. , 0. , 10., 10.],
        [10., 10., 20., 20.],
        [32., 32., 38., 42.]])
Traceback (most recent call last):
  File "giou_paddle.py", line 105, in <module>
    paddle_overlaps = giou_p(paddle_bboxes1, paddle_bboxes2)
  File "giou_paddle.py", line 66, in giou_p
    rows = bboxes1.size(-2)
TypeError: 'numpy.int64' object is not callable`

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/X2Paddle/blob/af4654b6f203a790b40e2a1db72646edf4feffe8/x2paddle/project_convertor/pytorch/torch2paddle/tensor.py#L93

应该是因为X2Paddle在这里重载了tensor的size函数

**Comment by skywalk163** [comment]
谢谢，加了size这个函数后，就正常了。
`

                def add_tensor_function(func):
                    setattr(paddle.Tensor, func.__name__, func)


                # @property
                # def data(self):
                #     return self


                # setattr(paddle.Tensor, "data", data)

                @add_tensor_function
                def size(self, dim=None):
                    if dim is not None:
                        return self.shape[dim]
                    else:
                        return self.shape`

另外发现也可以用shape代替size。
