### ISSUE TITLE
Tensorflow的Yolov3模型转换至paddle模型测试失败

### ISSUE THREAD

**Issue by BruceFreedom** [PaddlePaddle/X2Paddle#709]
模型来源：TensorFlow
模型说明： 其相应repo为 https://github.com/YunYang1994/tensorflow-yolov3
模型文件： 上面repo的预训练模型，经过转换成 pb模型
测试环境： tensorflow-gpu 1.15, x2paddle 1.3.4
测试输入： 416*416的图片

测试过程出错提示如下（重新转换模型测试，如下错误消失...）：
![图片](https://user-images.githubusercontent.com/48776875/143374592-e04ccfda-cf18-42b9-99ab-bcb2a7c0c4a8.png)

**Comment by wjj19950828** [comment]
您好，麻烦可以描述一下应用场景吗，然后上传一下pd模型，这边看一下～

**Comment by wjj19950828** [comment]
@BruceFreedom 您好，这边尝试之后并没有发现转换相关问题，不知是否与paddle版本有关，麻烦更新paddle版本在进行尝试～

**Comment by BruceFreedom** [comment]
> @BruceFreedom 您好，这边尝试之后并没有发现转换相关问题，不知是否与paddle版本有关，麻烦更新paddle版本在进行尝试～

谢谢指导，我昨天一直报图片中的错误，然后上午将整个转换过程重新走了一遍，错误消失了，估计是我自己哪里出了点儿问题
