### ISSUE TITLE
unique_name.generate can't find.

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/X2Paddle#727]
## 问题描述

- 错误信息：

在nn_init.py中找不到 unique_name的出处。

  # to be compatible of fp16 initalizers
  if var.dtype == paddle_dtypes.t_float16:
      out_dtype = paddle_dtypes.t_float32
      out_var = block.create_var(
          name=unique_name.generate(".".join(
              ['masra_init', var.name, 'tmp'])),
          shape=var.shape,
          dtype=out_dtype,
          type=VarDesc.VarType.LOD_TENSOR,
          persistable=False)

**Comment by wjj19950828** [comment]
感谢反馈～已经在这个PR修复～:https://github.com/PaddlePaddle/X2Paddle/pull/728
