### ISSUE TITLE
.pb 转paddle模型失败，附.pb模型

### ISSUE THREAD

**Issue by zuixiaosanlang** [PaddlePaddle/X2Paddle#734]
![image](https://user-images.githubusercontent.com/20105627/149883315-4c8b3568-7972-43c0-9904-fa2e60c0083f.png)

.pb模型：链接：https://pan.baidu.com/s/1oSJ0ps-aFiVyDLC0rul6jA 
提取码：asdf 

模型转换命令：
x2paddle --framework=tensorflow --model=frozen_model.pb --save_dir=pd_model

问题：
1）形状对不上
2）_BatchNorm_Const_2 receives a shape [0], but the expected shape is [64].

应用场景：类似pix2pix，用于图像生成，风格迁移
paddlepaddle              2.2.1
x2paddle                  1.3.5

谢谢

**Comment by wjj19950828** [comment]
感谢反馈，请补充描述一下模型具体应用场景吧，感谢～

**Comment by zuixiaosanlang** [comment]
@wjj19950828 已补充，麻烦帮忙分析一下，为啥转换后会出现上述问题，以及解决方法，非常感谢。

**Comment by zuixiaosanlang** [comment]
@wjj19950828 已补充，麻烦帮忙分析一下，为啥转换后会出现上述问题，以及解决方法，非常感谢。

**Comment by wjj19950828** [comment]
@zuixiaosanlang 这个和[issue#733](https://github.com/PaddlePaddle/X2Paddle/issues/733)是同一问题吗，若是同一问题请关闭吧～

**Comment by zuixiaosanlang** [comment]
@wjj19950828 那个关闭了。麻烦帮忙看看为啥形状出问题了。如果输入都改为320,320,3，就不报形状问题，但是跟.pb的输出结果差异很大。不知是paddle哪些算子转tf误差那么大

**Comment by wjj19950828** [comment]
@zuixiaosanlang 您好，相关问题以及修复

拉取PR代码，重新安装即可：https://github.com/PaddlePaddle/X2Paddle/pull/738
```shell
cd X2Paddle
pip uninstall x2paddle
python setup.py install
```
