### ISSUE TITLE
如何根据修改已有inference模型的输入为“动态shape” ？

### ISSUE THREAD

**Issue by zzcgithub** [PaddlePaddle/X2Paddle#735]
目前已有一些导出的模型参数（model/__params）, 可以通过paddle框架进行正常的推理，但是因为输入的shape已经固定，导致无法进行动态推理/无法使用tensorrt。具体问题如下，模型的输入输出截图截图均由netron可视化得出。

问题1
通过x2paddle将onnx模型转为paddle的模型参数，paddle版本2.1。

如何将输入的shape从1x3x224x224，修改为？x3x224x224 ， 将输出(1x69)改为shape ？x69。

![image](https://user-images.githubusercontent.com/13117136/149953236-e7854dda-f989-4293-a3a6-7d1a35ece188.png)

**Comment by wjj19950828** [comment]
您好，感谢反馈问题，可以参照[文档](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/inference_model_convertor/pytorch2paddle.md#%E6%96%B9%E5%BC%8F%E4%BA%8C%E6%89%8B%E5%8A%A8%E5%8A%A8%E8%BD%AC%E9%9D%99)

关于动态shape的部分，在x2paddle_code.py中手动添加动态输入再动转静～

**Comment by zzcgithub** [comment]
使用“方式二：手动动转静 在自动生成的 x2paddle_code.py 中添加如下代码" 问题解决
