### ISSUE TITLE
onn模型转paddle，算子ReduceSumSquare 不支持

### ISSUE THREAD

**Issue by zuixiaosanlang** [PaddlePaddle/X2Paddle#736]
![image](https://user-images.githubusercontent.com/20105627/150108716-32e496b6-d059-4dfc-a4b2-e086ac5fa8b9.png)

onn模型：链接：https://pan.baidu.com/s/1NfJjTpIvMF-OVI_0L8_bfg 
提取码：asdf 

应用场景：图像生成、风格迁移

**Comment by wjj19950828** [comment]
感谢反馈，这边排期支持一下～

**Comment by wjj19950828** [comment]
@zuixiaosanlang 麻烦上传一下onnx模型，然后描述一下业务场景～

**Comment by zuixiaosanlang** [comment]
@wjj19950828 onn模型已上传，谢谢
