### ISSUE TITLE
.pb转paddle模型，发现输出与.pb输出不一致，附.pb模型

### ISSUE THREAD

**Issue by zuixiaosanlang** [PaddlePaddle/X2Paddle#739]
![image](https://user-images.githubusercontent.com/20105627/150624250-b8a8e071-5a09-4471-8afd-e3c8571ec5c8.png)

pb模型链接：https://pan.baidu.com/s/1tl8-d8JN1HfVpsCT9UymjQ 
提取码：asdf 

这个BN算子转得有问题啊，当那个偏移值不是为0时，输出结果跟.pb不一样

应用场景：风格迁移，PIX2PIX

烦请帮忙分析一下吧

 SpaceToBatchND、BatchToSpaceND bug 这个问题你们修复后，现在是可以直接转换成paddle模型了，但输出结果差很远

**Comment by wjj19950828** [comment]
@zuixiaosanlang 麻烦提供一下相关真实输入(1*640*480*3,npy格式)、TF预测(pb模型)以及Paddle预测脚本吧，这边随机输入之后已经测过是没有diff的

**Comment by zuixiaosanlang** [comment]
可能你用错模型了，你不要用我其他issue的模型啊，用我对应issu的模型。我这个模型是400*300*3的，另一个issue才是640*480的，那个没问题是因为我没恢复模型快照，bn的bata值全是默认值0，输出是一致；当模型训练后，这个值不是0，输出就不一样了，麻烦再试试吧谢谢
@wjj19950828

**Comment by wjj19950828** [comment]
@zuixiaosanlang 您好，关于FusedBatchNorm需要您确认下，提供的pb模型，在```is_traing```属性设置的为True，这个是GAN任务特有的吗
![image](https://user-images.githubusercontent.com/19977378/150933089-094ec587-605a-4ea3-9309-071bf3c83b30.png)
若确认无问题，可拉取https://github.com/PaddlePaddle/X2Paddle/pull/741

手动安装即可～

**Comment by zuixiaosanlang** [comment]
@wjj19950828 没发现dev分支代码有变换呀，我拉取哪个分支代码？

**Comment by wjj19950828** [comment]
@zuixiaosanlang 已合入，重新拉去develop分支即可～
