### ISSUE TITLE
onnx 手动动转静 InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(x0) is not initialized

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/X2Paddle#750]
onnx模型链接: https://pan.baidu.com/s/13-PA1aFGB1KX96X8uG6ovA 提取码: ic63

文本检测dbnet，用mmocr训练， x2paddle --framework=onnx --model=dbnet.onnx --save_dir=dbnet_model 没问题，但手动动转静
在自动生成的 x2paddle_code.py 手动添加以下代码
def main(x2paddle_input):
    # There are 1 inputs.
    # x2paddle_input: shape-[1, 3, 320, 320], type-float32.
    paddle.disable_static()
    params = paddle.load(r'/home/gpu/workspace/X2Paddle/dbnet_model/model.pdparams')
    model = ONNXModel()
    model.set_dict(params, use_structured_name=True)
    model.eval()
    ## convert to jit
    sepc_list = list()
    sepc_list.append(
        paddle.static.InputSpec(
            shape=[-11, 3, 320, 320], name="x0", dtype="float32"))
    static_model = paddle.jit.to_static(model, input_spec=sepc_list)
    paddle.jit.save(static_model, "pd_model_trace/inference_model/model")
    out = model(x2paddle_input)
    return out

if __name__ == "__main__":
    x2paddle_input = torch.randn((1, 3, 320, 320))
    input = torch.Tensor(x2paddle_input)
    #print('input.shape:', input.shape)
    out = main(input)
    print('out.shape:', out.shape)

报如下的错误:
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "x2paddle_code.py", line 88, in forward
        x2paddle_378 = paddle.full(dtype='float32', shape=[1], fill_value=1.0)
        x2paddle_380 = paddle.full(dtype='float32', shape=[1], fill_value=1.0)
        x2paddle_383 = self.conv0(x2paddle_input)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x2paddle_161 = self.relu0(x2paddle_383)
        x2paddle_162 = self.pool0(x2paddle_161)

    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 665, in forward
	out = F.conv._conv_nd(
    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 147, in _conv_nd
	helper.append_op(
    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
	op = Operator(
    File "/home/gpu/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
	for frame in traceback.extract_stack():

    InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(x0) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1595)
      [operator < conv2d > error]  [operator < run_program > error]

    Revise suggestion: 
        1. Please ensure all your sublayers are inheritted from nn.Layer.
        2. Please ensure there is no tensor created explicitly depended on external data, we suggest to register it as buffer tensor. See https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/export_model/principle_cn.html#parameters-buffers for details
部署c++代码的错误如下
-------------------------------------- C++ Traceback (most recent call last): -------------------------------------- Not support stack backtrace yet. ---------------------- Error Message Summary: ---------------------- InvalidArgumentError: The input [nearest_interp_v2_3.tmp_0] shape of trt subgraph is [1,64,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at ..\paddle/fluid/inference/tensorrt/engine.h:100)

**Comment by wjj19950828** [comment]
@zgq91 感谢反馈，这个手动动转静主要问题是onnx为静态shape，输入为[1,3,320,320]，而且onnx模型有shape op，所以对shape强依赖，如下图：
![image](https://user-images.githubusercontent.com/19977378/156984533-610ac8b4-730c-4d9c-8586-ce9337a4a168.png)
解决有两个方法：
1、torch.onnx.export导出动态shape的onnx，再通过x2paddle转换
2、或者在x2paddle_code.py中将对应batch纬度都改为-1
另外有一个问卷：https://iwenjuan.baidu.com/?code=npyd51
麻烦抽空做一下，感谢～

**Comment by zgq91** [comment]
> @zgq91 感谢反馈，这个手动动转静主要问题是onnx为静态shape，输入为[1,3,320,320]，而且onnx模型有shape op，所以对shape强依赖，如下图： ![image](https://user-images.githubusercontent.com/19977378/156984533-610ac8b4-730c-4d9c-8586-ce9337a4a168.png) 解决有两个方法： 1、torch.onnx.export导出动态shape的onnx，再通过x2paddle转换 2、或者在x2paddle_code.py中将对应batch纬度都改为-1 另外有一个问卷：https://iwenjuan.baidu.com/?code=npyd51 麻烦抽空做一下，感谢～

感谢回复，x2paddle_code.py中对应batch维度都改为-1 动转静也没出问题，
![image](https://user-images.githubusercontent.com/18069515/157147115-8faf8284-02de-4e87-9028-4fa177f92346.png)
像nearest_interp_v2_0这样动态shape，tensorrt  c++部署的维度是要自己手动确定？？？

**Comment by wjj19950828** [comment]
@zgq91 这个需要在paddle inference中将动态shape开启，参考[SetTRTDynamicShapeInfo](https://paddleinference.paddlepaddle.org.cn/api_reference/cxx_api_doc/Config/GPUConfig.html#tensorrt)
