### ISSUE TITLE
yolox官方coco预训练模型转换失败

### ISSUE THREAD

**Issue by kouhinn** [PaddlePaddle/X2Paddle#768]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
yolox官方coco预训练模型转换失败。

- 错误信息
========= 1 OPs are not supported yet ===========
========== aten::copy_ ============
Exception: Model is not supported yet.

- 错误截图
![image](https://user-images.githubusercontent.com/42318152/160856182-d9171fa2-b285-465b-b4ae-717e20e8a7cb.png)

## 具体信息

- 转换模型后用处
    - [*] 使用 Paddle 框架/ PaddleInference 推理预测
    - [ ] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
YOLOX：https://github.com/Megvii-BaseDetection/YOLOX   最新版
- 应用场景
用于移动端业务下的检测业务
- 版本信息
PaddlePaddle => paddlepaddle-gpu       2.2.2
X2Paddle => develop最新版
来源框架版本(PyTorch/TF/ONNX/Caffe) =>PyTorch 1.7.1 (截图conda显示名未更新)

- 您的联系方式(邮箱/微信/电话)

**Comment by wjj19950828** [comment]
@kouhinn 我这边有验证yolox_s.pth这个模型没有遇到你说的相关问题，最好给我一个最小复现代码包括模型，打包到百度云

另外，这个aten::copy是已知问题，主要是因为forward函数中有inplace操作导致

只要有两个解决方案：
1、去掉或者替换PyTorch中相关inplace相关代码
2、导出ONNX，再从ONNX转到Paddle，这个之前验证是可以走通的

**Comment by kouhinn** [comment]
这个代码就是官方原来的代码（https://github.com/Megvii-BaseDetection/YOLOX  最新版），这个yolox_s.pth也是官方提供的（https://github.com/Megvii-BaseDetection/YOLOX 里边的yolox_s下载链接）。
同样的内容打包到百度网盘:
链接：https://pan.baidu.com/s/1rvm4uwPLwGps8tt7DHo1bg 
提取码：j5uh 
--来自百度网盘超级会员V6的分享
> @kouhinn 我这边有验证yolox_s.pth这个模型没有遇到你说的相关问题，最好给我一个最小复现代码包括模型，打包到百度云


好的。谢谢。如下方案我先试试。
> 另外，这个aten::copy是已知问题，主要是因为forward函数中有inplace操作导致
> 
> 只要有两个解决方案： 1、去掉或者替换PyTorch中相关inplace相关代码 
2、导出ONNX，再从ONNX转到Paddle，这个之前验证是可以走通的

**Comment by wjj19950828** [comment]
@kouhinn 根据你发给我的代码，需要在转换前加上```model.head.decode_in_inference = False```，因为部署时需要将decode去掉，如下图
![image](https://user-images.githubusercontent.com/19977378/161188598-3ded3d4a-1439-440c-86bc-72238cde3fbc.png)

因为decode阶段有[inplace操作](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L249)，导致出现```aten::copy```，这个 tvm 中有相关讨论，不予支持 https://github.com/apache/tvm/pull/7513

**Comment by kouhinn** [comment]
好的，谢谢！
