### ISSUE TITLE
利用X2paddle将pytorch迁移到paddle似乎会内存泄漏

### ISSUE THREAD

**Issue by WithHades** [PaddlePaddle/X2Paddle#774]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
利用x2paddle将512x512_diffusion.pt转换到paddle模型后，paddle模型似乎在conv2d处内存泄漏。
- 错误信息
Out of memory error on GPU 0. Cannot allocate 30.000244MB memory on GPU 0, 31.714722GB memory has been allocated and available memory is only 4.625000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)
- 错误截图

## 具体信息
aistudio地址：https://aistudio.baidu.com/ibdgpu3/user/285070/3822973/lab

- 转换模型后用处
    - [x] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
guided-diffusion：https://github.com/openai/guided-diffusion
迁移模型为512x512_diffusion.pt (https://openaipublic.blob.core.windows.net/diffusion/jul-2021/512x512_diffusion.pt)
- 应用场景
用于文本生成图像
- 您的联系方式(邮箱/微信/电话)

**Comment by wjj19950828** [comment]
@WithHades 看着像显存不够导致，调小batch、图片大小试试

**Comment by WithHades** [comment]
> @WithHades 看着像显存不够导致，调小batch、图片大小试试

十分感谢回复！模型输入大小是[1, 3, 768, 1280]，感觉不太应该是显存不够导致的。我实验环境是至尊版，有32G显存。原版pytorch模型是可在16G内存运行。具体爆显存问题是：x954 = self.conv2d23(x947)这行代码。x947大小也是[1, 3, 768, 1280]。不太清楚问题出哪儿了。我尝试其他模型康康

**Comment by WithHades** [comment]
@wjj19950828 确实是显存不够，将channels/2就可以了。很奇怪，原版torch模型可以在16GB显存跑，但是x2paddle转换的在32G显存都会爆，我手动转换的模型代码也会爆==
