### ISSUE TITLE
AttributeError: module 'convert' has no attribute '_get_parser'

### ISSUE THREAD

**Issue by 1chang37** [PaddlePaddle/X2Paddle#784]
parser = convert._get_parser()
AttributeError: module 'convert' has no attribute '_get_parser'

**Comment by wjj19950828** [comment]
@1chang37 您好，麻烦根据Issue模版进行填写，目前信息看不出具体问题

**Comment by 1chang37** [comment]
> @1chang37 您好，麻烦根据Issue模版进行填写，目前信息看不出具体问题

在进行TensorFlow 转换paddle时遇到的错误
平台信息：
paddlepaddle: 2.2.0
ubuntu 18.04


代码内容 co.py
import convert as convert
import argparse
#parser = convert._get_parser()
parser = convert._get_parser()
parser.meta_file = "checkpoint/model.meta"
parser.ckpt_dir = "checkpoint"
parser.in_nodes = ["inputs"]
parser.input_shape = ["None,224,224,3"]
parser.output_nodes = ["vgg_16/fc8/squeezed"]
parser.use_cuda = "True"
parser.input_format = "NHWC"
parser.save_dir = "paddle_model"

convert.run(parser)

错误信息：
X2Paddle/tf/ckpt/16# python3 co.py
Traceback (most recent call last):
  File "co.py", line 4, in <module>
    parser = convert._get_parser()
AttributeError: module 'convert' has no attribute '_get_parser'


>
