### ISSUE TITLE
pb转换成飞桨模型一直在运行就是没结果

### ISSUE THREAD

**Issue by llwwrr** [PaddlePaddle/X2Paddle#816]
![图片](https://user-images.githubusercontent.com/107793491/174479648-3f0a2d90-0c79-420f-9ad3-9ac8454cb74f.png)

**Comment by wjj19950828** [comment]
@llwwrr 目前X2Paddle已经去掉-pt选项，麻烦将X2Paddle以及Paddle版本更新到最新再进行尝试～

另外有两个问题可能需要您描述一下：
1、您具体的业务场景
2、为什么有转到Paddle部署的需求呢？

感谢～

**Comment by llwwrr** [comment]
1.学生学习用
2.将TensorFlow模型移植到edgeboard
