### ISSUE TITLE
onnx转paddle, reshape层维度错误

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/X2Paddle#839]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述

- 错误信息
pytorch转onnx（batchsize=1），然后通过x2paddle转paddle后，使用paddleSlim量化时，出现维度不匹配错误，经定位是由于转paddle后
reshape层的输出维度是[1, -1] ，导致batch>1时就出现了维度不匹配错误。手动改成[-1, channel]后就正常了
- 错误截图

## 具体信息

- 转换模型后用处
    - [ ] 使用 Paddle 框架/ PaddleInference 推理预测
    - [x] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
YOLOX：https://github.com/Megvii-BaseDetection/YOLOX
- 应用场景
用于移动端业务下的检测业务
- 版本信息
PaddlePaddle => :grey_question:
X2Paddle => :grey_question:
来源框架版本(PyTorch/TF/ONNX/Caffe) => :grey_question:
- 您的联系方式(邮箱/微信/电话)

**Comment by wjj19950828** [comment]
@HaoLiuHust 如果需要动态shape（BS=-1），麻烦在导出ONNX是将BS设置为-1，而非1，动态shape导出ONNX[参考文档](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/inference_model_convertor/pytorch2paddle.md#%E6%96%B9%E5%BC%8F%E4%B8%80pytorch-onnx-paddle)

另外，可以描述一下以下两个问题吗：
1、具体业务场景
2、为什么有转到Paddle部署的需求呢？

**Comment by HaoLiuHust** [comment]
> @HaoLiuHust 如果需要动态shape（BS=-1），麻烦在导出ONNX是将BS设置为-1，而非1，动态shape导出ONNX[参考文档](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/inference_model_convertor/pytorch2paddle.md#%E6%96%B9%E5%BC%8F%E4%B8%80pytorch-onnx-paddle)
> 
> 另外，可以描述一下以下两个问题吗： 1、具体业务场景 2、为什么有转到Paddle部署的需求呢？

使用Paddle-lite部署，所以需要转到paddle然后使用PaddleSlim量化。首先通过x2paddle转成了paddle。转换出来后再去量化，然后就报了维度不匹配的错误

**Comment by wjj19950828** [comment]
@HaoLiuHust 因为ONNX和Paddle的输入是对应的，如果ONNX的bs为1，那么对应Paddle的输入必须要求bs为1，可以导出动态shape的ONNX，然后再进行转换～

**Comment by HaoLiuHust** [comment]
> @HaoLiuHust 因为ONNX和Paddle的输入是对应的，如果ONNX的bs为1，那么对应Paddle的输入必须要求bs为1，可以导出动态shape的ONNX，然后再进行转换～

明白，问题已经解决了。有个地方会有点误导：
![image](https://user-images.githubusercontent.com/7233091/180695688-b063fada-e713-46ec-94a6-eb7d32fc165a.png)
如果是一个batch=1的这么转，reshape之后的层的batch数是错误的，前面会变成batch=-1. 如果把reshape层改下就好了
