### ISSUE TITLE
yolov7 onnx2paddle :convert failed node:onnx__Concat_396, op_type is Resize

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/X2Paddle#877]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
使用pt转onnx后，onnx2paddle出错，x2paddle不支持Resize算子吗？
- 错误信息
- 错误截图

![image](https://user-images.githubusercontent.com/49974432/185089161-201d88d2-e4cc-4044-bc31-610615afe2eb.png)

## 具体信息

- 转换模型后用处
    -使用 Paddle 框架/ PaddleInference 推理预测

- 模型来源
YOLO7：

**Comment by wjj19950828** [comment]
@wj920291253 麻烦提供一下ONNX模型吧

另外，可以描述一下以下两个问题吗：
1、具体业务场景
2、为什么有转到Paddle部署的需求呢？

感谢～

**Comment by wj920291253** [comment]
@wjj19950828 已经解决了，从.pt转换为.onnx时 optset version设为9 就能完成转换了

**Comment by Hap-Zhang** [comment]
@wj920291253 
您好，请问您将optset version设为9时再进行转onnx不会报错吗？
ONNX: export failure ❌ 1.6s: step!=1 is currently not supported
