### ISSUE TITLE
tf model  convert error

### ISSUE THREAD

**Issue by aa12356jm** [PaddlePaddle/X2Paddle#90]
tf model  convert error:    Exception: OP: [ResizeBilinear] not support yet

**Comment by jiangjiajun** [comment]
Hi，你好，ResizeBillinear我会尽快添加上去。这个OP主要用在检测模型中，但目前x2paddle还并未在TensorFlow模型上测试检测模型，我目前在尝试支持YOLO-V3，如果方便的话可以告知我你需要转换的模型，以及相应的代码实现参考，谢谢~

**Comment by aa12356jm** [comment]
我转换的这个模型是人脸检测的模型，网络结构和[这个](https://github.com/deepinsight/insightface/tree/master/RetinaFace)基本一致，我用tf重写了一遍。模型和代码都在公司内部，不方便拿出来分享，您可以参考[这个](https://github.com/deepinsight/insightface/issues/669)开源模型，结构基本一样哈，

**Comment by jiangjiajun** [comment]
> 我转换的这个模型是人脸检测的模型，网络结构和[这个](https://github.com/deepinsight/insightface/tree/master/RetinaFace)基本一致，我用tf重写了一遍。模型和代码都在公司内部，不方便拿出来分享，您可以参考[这个](https://github.com/deepinsight/insightface/issues/669)开源模型，结构基本一样哈，

在转换TensorFlow模型时，X2Paddle是根据模型的计算图来进行转换的，所以我暂时无法通过别的框架模型代码来分析。
我已经把ResizeBilinear添加上去，你可以试用下，有问题的话可以继续在此Issue下交流：）

**Comment by wanjinchang** [comment]
@aa12356jm 你好!我也尝试用tf写了这个(https://github.com/deepinsight/insightface/issues/669)网络结构,然后把mxnet模型转为tf模型,但是一直得不出正确的结果,检测不出人脸,检查了转换过程,没发现问题,请问你用tf重写的时候需要注意什么问题吗？

**Comment by wanjinchang** [comment]
@aa12356jm 你好!我也尝试用tf写了这个(https://github.com/deepinsight/insightface/issues/669)  网络结构,然后把mxnet模型转为tf模型,但是一直得不出正确的结果,检测不出人脸,检查了转换过程,没发现问题,请问你用tf重写的时候需要注意什么问题吗？

**Comment by wanjinchang** [comment]
@aa12356jm 你好!我也尝试用tf写了[这个](deepinsight/insightface#669) 网络结构,然后把mxnet模型转为tf模型,但是一直得不出正确的结果,检测不出人脸,检查了转换过程,没发现问题,请问你用tf重写的时候需要注意什么问题吗？

**Comment by aa12356jm** [comment]
@jiangjiajun 刚使用最新的代码进行了转换，错误信息如下：

`WARNING:tensorflow:From /home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/decoder/tf_decoder.py:204: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
Total nodes: 455
========== Use infer_shape_tensor for tensor:  rf/oup_1/Reshape/shape
Traceback (most recent call last):
  File "/home/trainer/anaconda3/envs/tf19_py36/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.4.3', 'console_scripts', 'x2paddle')()
  File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/convert.py", line 158, in main
    tf2paddle(args.model, args.save_dir)
  File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/convert.py", line 84, in tf2paddle
    mapper = TFOpMapper(model)
  File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 103, in __init__
    func(node)
  File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 974, in Softmax
    axis = nhwc_dim_to_nchw(input, axis)
  File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 40, in nhwc_dim_to_nchw
    char = tf_data_format[dim]
TypeError: list indices must be integers or slices, not NoneType`

**Comment by aa12356jm** [comment]
@wanjinchang 为什么要转换mxnet模型？我们这边是全部重新写的，重新训练，也是很多坑，现在效果还不错

**Comment by wanjinchang** [comment]
作者开源那个模型效果可以,然后我也在一边训练一边转模型,看哪个方法快就用哪个,但是训练出来效果不好,你的数据是用RetinaFace公开的数据么?

**Comment by aa12356jm** [comment]
是的，我们就是用的他们公开的数据，不过他们的训练数据标注了很多小人脸，对hard face的检测比较好，但是在实际使用中也会导致误检比较高，如果你使用的场景不需要检测小人脸，可以做一下数据处理，将标注的小人脸去掉

**Comment by jiangjiajun** [comment]
> @jiangjiajun 刚使用最新的代码进行了转换，错误信息如下（你可以给我留一个邮箱，我把模型pb文件单独发给你调试看看）：
> 
> `WARNING:tensorflow:From /home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/decoder/tf_decoder.py:204: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version. Instructions for updating: Use tf.gfile.GFile. Total nodes: 455 ========== Use infer_shape_tensor for tensor: rf/oup_1/Reshape/shape Traceback (most recent call last): File "/home/trainer/anaconda3/envs/tf19_py36/bin/x2paddle", line 11, in <module> load_entry_point('x2paddle==0.4.3', 'console_scripts', 'x2paddle')() File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/convert.py", line 158, in main tf2paddle(args.model, args.save_dir) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/convert.py", line 84, in tf2paddle mapper = TFOpMapper(model) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 103, in __init__ func(node) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 974, in Softmax axis = nhwc_dim_to_nchw(input, axis) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 40, in nhwc_dim_to_nchw char = tf_data_format[dim] TypeError: list indices must be integers or slices, not NoneType`

jiangjiajun#baidu.com

**Comment by jiangjiajun** [comment]
> @aa12356jm 你好!我也尝试用tf写了[这个](deepinsight/insightface#669) 网络结构,然后把mxnet模型转为tf模型,但是一直得不出正确的结果,检测不出人脸,检查了转换过程,没发现问题,请问你用tf重写的时候需要注意什么问题吗？

由于TensorFlow和Paddle中部分OP机制不同，而且此外TF模型都默认为NHWC输入，而Paddle为NCHW输入，所以在转换过程中，存在部分`axis`参数的转换计算，根据你的模型，我fix了一些问题，你可以重新安装尝试转换
```
pip uninstall x2paddle
pip install git+https://github.com/PaddlePaddle/X2Paddle.git@develop
```

自行转换后，可以测试下两个模型的diff，需要注意的是在paddle中输入的格式为NCHW，输出也是NCHW（TensorFlow为NHWC）  

如若仍存在其它问题，可继续提新的Issue反馈 ：）

**Comment by jiangjiajun** [comment]
> @jiangjiajun 刚使用最新的代码进行了转换，错误信息如下（你可以给我留一个邮箱，我把模型pb文件单独发给你调试看看）：
> 
> `WARNING:tensorflow:From /home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/decoder/tf_decoder.py:204: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version. Instructions for updating: Use tf.gfile.GFile. Total nodes: 455 ========== Use infer_shape_tensor for tensor: rf/oup_1/Reshape/shape Traceback (most recent call last): File "/home/trainer/anaconda3/envs/tf19_py36/bin/x2paddle", line 11, in <module> load_entry_point('x2paddle==0.4.3', 'console_scripts', 'x2paddle')() File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/convert.py", line 158, in main tf2paddle(args.model, args.save_dir) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/convert.py", line 84, in tf2paddle mapper = TFOpMapper(model) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 103, in __init__ func(node) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 974, in Softmax axis = nhwc_dim_to_nchw(input, axis) File "/home/trainer/anaconda3/envs/tf19_py36/lib/python3.6/site-packages/x2paddle-0.4.3-py3.6.egg/x2paddle/op_mapper/tf_op_mapper.py", line 40, in nhwc_dim_to_nchw char = tf_data_format[dim] TypeError: list indices must be integers or slices, not NoneType`

尝试一下新的代码
```
pip uninstall x2paddle
pip install git+https://github.com/PaddlePaddle/X2Paddle.git@develop
```
自行转换后，可以测试下两个模型的diff，需要注意的是在paddle中输入的格式为NCHW，输出也是NCHW（TensorFlow为NHWC）

**Comment by aa12356jm** [comment]
@jiangjiajun 你好，我这边可以转换成功，但是转换出来的为什么是很多个文件？在部署的时候不方便吧？不能合并为一个模型文件吗？

**Comment by jiangjiajun** [comment]
> @jiangjiajun 你好，我这边可以转换成功，但是转换出来的为什么是很多个文件？在部署的时候不方便吧？不能合并为一个模型文件吗？

X2Paddle模型转换后，会有两个目录
`model_with_code`: 生成参数文件和模型代码文件  
`inference_model`: 生成的参数文件和序列化的模型结构文件

一般用`inference_model`进行部署，目前里面的参数是分开保存的，主要是为了适应PaddleLite目前的模型加载形式，如果你要将所有的参数文件合为一个文件，有如下两个方法，  
1. 使用Paddle加载inference_model，并重新调用save_inference_model方法保存模型，调用时，指定模型文件名和参数文件名即可；  
2. 修改`X2Paddle/core/op_mapper.py`  
原代码
```
            fluid.io.save_inference_model(dirname=os.path.join(
                save_dir, "inference_model"),
                                          feeded_var_names=input_names,
                                          target_vars=outputs,
                                          executor=exe,
                                          params_filename=None)
```
修改为
```
            fluid.io.save_inference_model(dirname=os.path.join(
                save_dir, "inference_model"),
                                          feeded_var_names=input_names,
                                          target_vars=outputs,
                                          executor=exe,
                                          params_filename="params")
```

**Comment by aa12356jm** [comment]
ok

**Comment by wanjinchang** [comment]
@aa12356jm 谢谢!你们tensorflow复现出来的mnet.25推断时间和论文的差不多吗?

**Comment by siyiding1216** [comment]
> @wanjinchang 为什么要转换mxnet模型？我们这边是全部重新写的，重新训练，也是很多坑，现在效果还不错。你可以先看看生成的baseanchor是否正确

你们有做mobilenet加上quantization的训练吗
