### ISSUE TITLE
代码typo errror

### ISSUE THREAD

**Issue by CatIIIIIIII** [PaddlePaddle/X2Paddle#919]
请检查
https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/project_convertor/pytorch/torch2paddle/io.py#L172

应该是把self打错成seld了

**Comment by wjj19950828** [comment]
@BrutalStark 感谢反馈，问题已经修复：https://github.com/PaddlePaddle/X2Paddle/pull/920
