### ISSUE TITLE
import x2paddle 时报错

### ISSUE THREAD

**Issue by sunny714822** [PaddlePaddle/X2Paddle#929]
import x2paddle 时报错type object 'paddle.fluid.libpaddle.VarBase' has no attribute '__getitem__'

![image](https://user-images.githubusercontent.com/85465833/210634588-e2d05b1b-098a-4834-85b9-643b155d1c9a.png)

**Comment by wjj19950828** [comment]
@sunny714822 具体Paddle以及X2Paddle版本是多少呢

**Comment by SmallRedFeel** [comment]
请问这个问题解决了嘛

**Comment by SmallRedFeel** [comment]
> @sunny714822 具体Paddle以及X2Paddle版本是多少呢

请问这个问题解决了嘛

**Comment by 2jjjd** [comment]
请问这个问题解决了嘛
