### ISSUE TITLE
from x2paddle import models报错

### ISSUE THREAD

**Issue by yhz5256** [PaddlePaddle/X2Paddle#957]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述

- 错误信息
- type object 'paddle.fluid.libpaddle.VarBase' has no attribute '__getitem__'
- 错误截图
![image](https://user-images.githubusercontent.com/22793745/227201275-4266ad0b-1ef5-4875-8703-0b7db1022b12.png)

**Comment by wjj19950828** [comment]
@yhz5256 目前问题已经修复

相关PR:https://github.com/PaddlePaddle/X2Paddle/pull/963
